### ISSUE TITLE
Fixing W3TC issues

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/fix-w3tc#1]
Hello @ftownes !

I hope you don't mind if I publicly fix & customize your plugin.
https://github.com/szepeviktor/fix-w3tc/blob/master/README.md

Please comment.

All the best!

**Comment by qriouslad** [comment]
I just wanted to say thank you @szepeviktor!

Your mods have been very useful, and I have it installed on all my important sites. How can I buy you a cup of coffee? (read: donate) 

Cheers ;-)

**Comment by szepeviktor** [comment]
Thank you.
https://szepe.net/wp-donate/
