### ISSUE TITLE
Page cache exceptions won't work (ssl)

### ISSUE THREAD

**Issue by MaciejKrawczyk** [szepeviktor/fix-w3tc#109]
Hello. I noticed that there is something wrong with page cache exception rules. My website uses ssl. By default the option to cache https requests is disabled, so nothing gets cached. When I enable that option - almost everything gets cached, regardless of exceptions. For example, wp-login.php cached, pages with query strings - cached, even though the option to cache them is disabled. Only logged in users don't get cached. Defining DONOTPAGECACHE constant works, which is what I'm going to use, it is more flexible than regex matching rules anyway. Just wanted to report this issue.

**Comment by amiga-500** [comment]
Oops...just checked and noticed it does indeed cache files like _wp-login.php_   Sorry about that!  The fix has been implemented.  Give it a try to see if it resolves all your other problems too.   If it doesnt i will give it a more thorough check.

To save you time just open the file: _w3-total-cache/lib/W3/PgCache.php_ and [remove line 702](https://github.com/szepeviktor/fix-w3tc/pull/110/files#diff-e3bbfbcd5b5d89c84fce98d7d5f8b4b4L702).  It is the line that says: 
```php
$accept_uri[] = $_SERVER['PHP_SELF'];
```

**Comment by MaciejKrawczyk** [comment]
I can confirm it works properly now. Thank you for fixing this.
