### ISSUE TITLE
Prevent updating

### ISSUE THREAD

**Issue by emmtre** [szepeviktor/fix-w3tc#115]
Code suggestion if you want to prevent updating to W3 Total Cache plugin.

```
//* Disable plugin updates
add_filter('site_transient_update_plugins', 'disable_w3tc_plugin_updates');
function disable_w3tc_plugin_updates( $value ) {
	if( $value ) {
		unset( $value->response['w3-total-cache/w3-total-cache.php'] );
	}
	return $value;
}
```

**Comment by amiga-500** [comment]
@emmtre  just wanted to say thanks for the suggestion.  Just wanted to give you a heads up that i've added a "_Hide Plugin Update Notification_" checkbox under General Settings' Miscellaneous area (see pic below).  By default it is unchecked.  When you check it on (enable it), the Wordpress update notification message for w3tc will now go away.

![updatenotification](https://cloud.githubusercontent.com/assets/5191497/18974258/f06611a0-866f-11e6-976e-e0709a0c478e.jpg)

**Comment by emmtre** [comment]
If you don't use the if conditional before unset it will cause a PHP warning.
PHP Warning:  Attempt to modify property of non-object in /public_html/wp-content/plugins/w3-total-cache/inc/define.php on line 1652

**Comment by nigrosimone** [comment]
@emmtre thank you! i have added a `if` control
