### ISSUE TITLE
change the self update url which pull the new version from wordpress plugins directory

### ISSUE THREAD

**Issue by rabin-io** [szepeviktor/fix-w3tc#119]
for peoples which don't want to switch to the original version.

**Comment by nigrosimone** [comment]
https://github.com/szepeviktor/fix-w3tc/issues/115

**Comment by amiga-500** [comment]
@nigrosimone should i add this into fix-w3tc? I was debating it because yea as @rabin-io mentions there are people who dont want to switch yet, meaning there are people that will want to switch when w3tc 0.9.5 does work out its several bugs.  So i was sitting on the fence whether to put in such a feature or not.  

I could add a checkbox on the dashboard that allows the user to "_Hide Update Notifications_" but by default it is unchecked (meaning: when they install fix-w3tc it will show the new version notification message on the Plugins page, but by navigating to the fix-w3tc dashboard and checkmarking the "_Hide Update Notification_" it will no longer appear).

It's up to you, you're the lead on this project.  I am neutral on the matter since as you did with @rabin-io there is a solution made available right now in the threads.

**Comment by nigrosimone** [comment]
> @nigrosimone should i add this into fix-w3tc? [...] It's up to you, you're the lead on this project

thank you for considering me the "lead", but this is an open source project and it's not mine. You're free to do what you think is right for the project.

My 5 cents.

> I could add a checkbox on the dashboard that allows the user to "Hide Update Notifications" [...]

I think this is the best choise for the users.

side note: @amiga-500 why you don't have asked frederik to enter in official W3TC repository? Your contribution to this project has been outstanding, you can be a great help in the official repository.

**Comment by charlesLF** [comment]
> side note: @amiga-500 why you don't have asked frederik to enter in official W3TC repository? Your contribution to this project has been outstanding, you can be a great help in the official repository.

Perhaps we should talk about this on the slack channel that you created (https://fix-w3tc.slack.com/). @nigrosimone I sent you my email so you can send the invite. @amiga-500, it'd be great if you can join too by sending your email to @nigrosimone (nigro.simone@gmail.com).

**Comment by amiga-500** [comment]
@rabin-io just wanted to give you a heads up that i've added a "_Hide Plugin Update Notification_" checkbox under General Settings' Miscellaneous area (see pic below).  By default it is unchecked.  When you check it on (enable it), the Wordpress update notification message for w3tc will now go away.

I've merged it into to _Master_ but haven't created a new release yet that incorporates it.  So you'll have to [download Master](https://github.com/szepeviktor/fix-w3tc/archive/master.zip) for now.  Alternatively, you can just download the related Master files that provide it:

**`inc/define.php`** = [download](https://raw.githubusercontent.com/szepeviktor/fix-w3tc/9db58cc16e09e7cfd48e69a1d983c72c56518002/inc/define.php)
**`inc/options/general.php `** = [download](https://raw.githubusercontent.com/szepeviktor/fix-w3tc/9db58cc16e09e7cfd48e69a1d983c72c56518002/inc/options/general.php)
**`lib/W3/ConfigKeys.php`** = [download](https://raw.githubusercontent.com/szepeviktor/fix-w3tc/9db58cc16e09e7cfd48e69a1d983c72c56518002/lib/W3/ConfigKeys.php)
**`lib/W3/Root.php`** = [download](https://raw.githubusercontent.com/szepeviktor/fix-w3tc/9db58cc16e09e7cfd48e69a1d983c72c56518002/lib/W3/Root.php)
**`lib/W3/UI/Settings/General.php`** = [download](https://raw.githubusercontent.com/szepeviktor/fix-w3tc/9db58cc16e09e7cfd48e69a1d983c72c56518002/lib/W3/UI/Settings/General.php)

![updatenotification](https://cloud.githubusercontent.com/assets/5191497/18974258/f06611a0-866f-11e6-976e-e0709a0c478e.jpg)

**Comment by amiga-500** [comment]
> side note: @amiga-500 why you don't have asked frederik to enter in official W3TC repository? Your contribution to this project has been outstanding, you can be a great help in the official repository.

Much appreciated.  Yea i am still debating this.  I probably will join you guys too.  It'll be nice to have familiar faces there :) .  I'm starting to wind down my support for fix-w3tc now that the official 0.9.5 is out but figured to resolve the remaining issues that were recently brought up.  Once done i'll decide.

Cheers
Kimberly

**Comment by rabin-io** [comment]
Thanks @amiga-500 , I saw the commit. much appreciated. thank you
