### ISSUE TITLE
Server error 500 when Page Cache is enabled

### ISSUE THREAD

**Issue by maelga** [szepeviktor/fix-w3tc#120]
Version **0.9.4.5.4** throughs server error 500 when Page Cache is enabled. I'm using PHP7.

My server error log shows:
- PHP Parse error: syntax error, unexpected ‘<‘, expecting end of file in /home/mydomain.com/fghgh/public_html/wp-content/plugins/w3-total-cachelib/W3/PgCache.php(1511) : eval()'d code on line 1
- PHP Fatal error: Exception thrown without a stack frame in Unknown on line 0

I also have the same error when using the latest official **v0.9.5**, the error log is then:
- PHP Parse error: syntax error, unexpected ‘<‘, expecting end of file in /home/mydomain.com/fghgh/public_html/wp-content/plugins/w3-total-cache/PgCache_ContentGrabber.php(1460) : eval()’d code on line 1
- PHP Fatal error: Exception thrown without a stack frame in Unknown on line 0

Any idea what goes wrong?

**Comment by amiga-500** [comment]
It might not be an error with w3tc.  Seems like you have an error within your php code inside the fragment caching comment tags.  However, to know if it is a bug.. if possible, can you paste the contents of your _mfunc_ comment lines, including the tags themselves (ie, _ **(your php code)** _)?

**Comment by amiga-500** [comment]
@maelga still waiting to hear back from you.

**Comment by maelga** [comment]
Thanks Kimberly.
I have removed the mfunc comments and don't get any error 500 anymore.
Seems more like a php issue with my code indeed.

**Comment by amiga-500** [comment]
Ahhh...thanks for the update.  Ok i will consider the issue resolved. :)
