### ISSUE TITLE
Performance admin menu bar links to Support page

### ISSUE THREAD

**Issue by Tarun80** [szepeviktor/fix-w3tc#125]
When you hover Performance in the Admin menu bar, there's a link to Support. That support page is a dead page that only says "Sorry, you are not allowed to access this page."

![Admin menu bar](https://i.imgur.com/4mgH3BK.png)

I believe that menu item should either be removed, or replaced with information leading to this repository and other useful information.

**Comment by amiga-500** [comment]
Thanks for letting us know.  I willl take care of it now!
