### ISSUE TITLE
Stop updates from old version

### ISSUE THREAD

**Issue by jeffmcneill** [szepeviktor/fix-w3tc#131]
It seems this fixed version wants to get updates from the old (Townes) version, when that one is updated. Instead, getting new versions from Github would be great. At least disable the updates from the Townes (non-fixed) version.

**Comment by amiga-500** [comment]
Hi @jeffmcneill .. the "_fixed_" version has an option to disable the updates from the Townes version already.  Just check under General Settings > Miscellaneous (see pic below)

![f06611a0-866f-11e6-976e-e0709a0c478e](https://cloud.githubusercontent.com/assets/5191497/19020360/369944f2-8874-11e6-9c9d-4704aebddf7e.jpg)

**Comment by jeffmcneill** [comment]
I don't see this option in the latest release. Is it in main?

**Comment by nigrosimone** [comment]
i have the latest [0.9.4.5.5](https://github.com/szepeviktor/fix-w3tc/releases/tag/0.9.4.5.5) and i see the option in Performance > General Settings > Miscellaneous

**Comment by jeffmcneill** [comment]
Thanks @nigrosimone I see the option now. This was released yesterday I think, which is why the earlier release did not show it. Thanks @amiga-500 also for your speedy response to this issue. Happy to be on your version of W3TC. I've used this for years, but it now seems to be working much better. ^_^
