### ISSUE TITLE
Updates and forks

### ISSUE THREAD

**Issue by afragen** [szepeviktor/fix-w3tc#133]
I'm coming here from an issue posted to GitHub Updater, https://github.com/afragen/github-updater/issues/460

If this fork would simply use GitHub Updater for updates and not delete or rename any repositories when installing I think your issues with updates, #115 #131 would go away. Updates would come from this plugin and not the main file.

**Comment by nigrosimone** [comment]
`fix-w3tc` for work needs to be installed in `w3-total-cache` folder
