### ISSUE TITLE
[0.9.5] Flush disk enhanced cache not work

### ISSUE THREAD

**Issue by nigrosimone** [szepeviktor/fix-w3tc#136]
**Issue with 0.9.5**

From admin bar  `Performance` > `Page Modules` > `Page cache: current page` don't work for me, not flush the current page cache.

I have a multisite installation path based with different site on some path, eg.:

    http://yoursite.com/
    http://yoursite.com/it/
    http://yoursite.com/fr/

If i try to flush a page (not post) from admin bar `Performance` > `Page Modules` > `Page cache: current page`, eg.:

    http://yoursite.com/fr/mypage/

`delete()` on `Cache_File_Generic.php` try to delete:

    /wp-content/cache/page_enhanced/yoursite.com/_index.html
    /wp-content/cache/page_enhanced/yoursite.com/_index.html_gzip
    /wp-content/cache/page_enhanced/yoursite.com/wp-admin/network/admin.php/_index.htm
    /wp-content/cache/page_enhanced/yoursite.com/wp-admin/network/admin.php/_index.html_gzip
    /wp-content/cache/page_enhanced/yoursite.com/feed/_index.html
    /wp-content/cache/page_enhanced/yoursite.com/feed/_index.html_gzip

the right file to delete:

    /wp-content/cache/page_enhanced/yoursite.com/fr/mypage/_index.html
    /wp-content/cache/page_enhanced/yoursite.com/fr/mypage/_index.html_gzip

are not in the list and the list has some mistakes:

    /wp-content/cache/page_enhanced/yoursite.com/wp-admin/network/admin.php/_index.htm
    /wp-content/cache/page_enhanced/yoursite.com/wp-admin/network/admin.php/_index.html_gzip

this make me crazy,  w3tc seems to not have implemented the code for flush "page", i don't found it!

**Comment by charlesLF** [comment]
@cesco69 and @nigrosimone, do you mind trying out [this patch](https://github.com/charlesLF/fix-w3tc/commit/ee1421db3e6f150179c6c72af35b01a5bd6c2460) and seeing if it fixes the problem? https://github.com/charlesLF/fix-w3tc/commit/ee1421db3e6f150179c6c72af35b01a5bd6c2460

**Comment by cesco69** [comment]
@charlesLF yep! now works! tanks!

**Comment by nigrosimone** [comment]
Works!
