### ISSUE TITLE
db caching error "mysqli_num_fields() expects parameter 1 to be mysqli_result, boolean given"

### ISSUE THREAD

**Issue by nigrosimone** [szepeviktor/fix-w3tc#14]
`mysqli_num_fields() expects parameter 1 to be mysqli_result, boolean given in /wp-includes/wp-db.php on line 3013`

it seems to have occurred right after upgrading to WordPress 4.5.

If you turn W3TC db caching off, the problem disappears, but no more caching.

**Comment by amiga-500** [comment]
I noticed Wordpress dev stopped using the "@" error suppressor for mysqli_num_fields() in wp-db.php starting at 4.5.  So it's very possible this error msg was occurring prior to 4.5 but was being suppressed.  

So this db cache fix might simply need a condition check or @ in the corresponding w3tc file (Db.php? DbCache.php?) that is indirectly calling the load_col_info() function of wp-db.php (the function that is throwing  this error message).

From a quick cursory glance it might be w3tc calling the __get() overload.  When i have time  I'll have a closer look.

**Comment by nigrosimone** [comment]
you're right...

**Comment by amiga-500** [comment]
I decided to have a look at this bug and for the life of me i cannot recreate it on my end.  I get no error warnings and w3tc's Database Caching works perfectly for me (its enabled).  What is a sure way for me to see this bug?

For my test system i currently have:

1. WP 4.6 installed (fresh install)
2. PHP 7.0.9 active
3. Latest fix-w3tc build
4. Enabled WP_DEBUG via wp-config.php (have it redirecting to /wp-content/debug.log instead of on-screen -- nothing is ever written out to it)
5. w3tc is enabled and Database Caching (set to: "Disk") is enabled.  Note: I didn't enable anything else; everything is at their default value.

Based on the that setup i see no php warnings/errors of any kind and database caching is working -- a "db" directory is generated and several cached sql/result files are made (and being made).

Thanks for the assist,
Kimberly

**Comment by nigrosimone** [comment]
I also investigated but could not find anything wrong in chache db.

**Comment by Volnus** [comment]
I can also confirm there are no errors with this. Can we look at suppressing the error again?

**Comment by rabin-io** [comment]
@Volnus, I disagree with simply suppressing a error message.
I perfer to add `error_log` before the command, and in case `mysqli_result` is boolean then dump a bunch of debug information to help with the mater for the next time. Maybe the problem is a simple change between PHP version when in old version you will get a boolean, but in the newer version you get an object.

**Comment by amiga-500** [comment]
I think i'll refocus back on this old elusive issue...if it is even an issue (the db cache still works fine).  Last i checked i was not even able to get any warning or error message of any kind.    I'll put back the wordpress 0.9.4.1 on a live server  and compare it against fix-w3tc to see if the error message only occurs for that older version.  This will hopefully put to rest if this issue had indirectly been resolved long ago (so no warning messages either) with all our updates to fix-w3tc.  Will be fun to get back into this issue.

Kimberly

**Comment by nigrosimone** [comment]
I have already investigate, try tk replicate without success. For me is not a real bug.

**Comment by mkormendy** [comment]
Just as an unrelated follow up. I get this issue with WP-CLI errors and WP-Migrate-DB on a cron-sync. I have modified wp-db and dump the var to logs before the call that creates the warning. So far, it outputs objects with arrays inside. PHP 5.6 here, apache 2.4 on CentOS. I also have W3 Total Cache installed so that's why I find this *remotely* relevant.

**Comment by amiga-500** [comment]
@mkormendy thanks for the info!

**Comment by mkormendy** [comment]
No problem.

I was able to capture cases where, for whatever reason, the mysqli_query() call would produce a boolean true value, and in some cases a boolean false value. 

To fix it on my end (while this isn't a suggested permanent solution) I ended up modifying the wp-db.php file in the wp-includes folder to accommodate when the query returns a boolean:

```
/**
 * Load the column metadata from the last query.
 *
 * @since 3.5.0
 *
 * @access protected
 */
protected function load_col_info() {
	if ( $this->col_info )
		return;
	if ( !is_bool( $this->result ) ) {
		if ( $this->use_mysqli ) {
			$num_fields = mysqli_num_fields( $this->result );
			for ( $i = 0; $i < $num_fields; $i++ ) {
				$this->col_info[ $i ] = mysqli_fetch_field( $this->result );
			}
		} else {
			$num_fields = mysql_num_fields( $this->result );
			for ( $i = 0; $i < $num_fields; $i++ ) {
				$this->col_info[ $i ] = mysql_fetch_field( $this->result, $i );
			}
		}
	}
}
```

**Comment by nicooprat** [comment]
Hi, any news on this one? Getting the issue only when not logged-in. Using WP 4.8 latest and W3 Total Cache up to date too.

The issue disappears if I uncheck then check again the database caching in general settings, but sometimes reappears for no apparent reason.

**Comment by charlesLF** [comment]
Hey @nicooprat:

1.  Are you using the 0.9.5.x branch of w3tc?
2. What cache storage are you using? (File-based, memcached, redis, ...)?
3. What other cache types do you have active (object cache?)
4. Plugins? Themes?
5. PHP version?

**Comment by nicooprat** [comment]
Thanks for your quick answer.

1. Have to admit that I didn't see at the moment that I was on the repo of a fork. So no, I'm using the latest official release.
2. Disk: enhanced
3. Page cache + minify + database cache + object cache (disk)
4. Custom theme (based on Roots Sage 9) + [complete list of extensions](https://framapic.org/2vAxJQnoIAhl/P2E5vvqG4c4b.png)

Next time the issue appears I'll try to replace W3TC by this community fix!

**Comment by charlesLF** [comment]
No problem!
This particular issue is one of those mysteries that have went unsolved, and somehow disappeared at some point.

If you do end up having this issue again in the future, feel free to post about it and I'd look into it :)

**Comment by nicooprat** [comment]
Just had this issue again. Tried to switch Page cache from advanced to basic and it disappeared. I wanted to try every setting one by one but I guess it just regenerated the cache by changing this setting, so it might not be related. Pretty frustrating!

**Comment by GiuseppeIuculano** [comment]
I've the same error, wordpress 4.8 multisite

**Comment by charlesLF** [comment]
Thanks for the info @nicooprat . I will try to replicate on my side.

@Derevko : which w3tc version are you using, and what cache storage engine?

**Comment by laserjobs** [comment]
Got this error in the middle of the night. 

E_WARNING: mysqli_num_fields() expects parameter 1 to be mysqli_result, null given

Stack trace
…at /html/wp-includes/
wp-db.php (3091)
…at /html/wp-includes/
wp-db.php (682)
… html/wp-content/plugins/w3-total-cache/
DbCache_WpdbInjection_QueryCaching.php (161)
….html/wp-content/plugins/w3-total-cache/
DbCache_Wpdb.php (152)
…at /html/wp-includes/
wp-db.php (2280)
… /html/wp-includes/
comment.php (634)
… /html/wp-includes/
comment.php (1943)
… /html/wp-includes/
comment.php (3095)
… /html/
wp-comments-post.php (25)

WP 4.8.1
Not multisite
PHP 7.0
MySql 5.6
Memcached database in W3 Total Cache

**Comment by jakub-dvoracek** [comment]
We have the same issue.
Wordpress v4.8.1
W3CTC v0.9.5.4
PHP v5.6

The warning appears only if Database cache is enabled (and method set to disk, I didn´t tested any other methods). And only if user is not logged in.

**Comment by maxleistner** [comment]
Same here...

Wordpress v4.9.1
W3CTC v0.9.6
PHP v7.1

The warning appears only if Database cache is enabled (and method set to disk, I didn´t tested any other methods). And only if user is not logged in.

**Comment by dimizu** [comment]
Same here with:
Wordpress 4.9.1
W3CTC Version 0.9.6

The warning appears only if Database cache is enabled and only if user is not logged in and only when I have an `'` apostrophe charater in the title of my post/page/custom post type.

**Comment by bethal** [comment]
Same issue here:

WordPress 4.9.6
W3TC 0.9.7
Database cache is enabled

The warning appears for non-logged Users and when logged in, it disappears.

**Comment by neoswf** [comment]
Me as well. Suddenly it started appearing...

**Comment by arikw** [comment]
I'm getting the following errors randomly
[21-Aug-2018 14:49:31 UTC] PHP Warning:  mysqli_query(): (HY000/126): Incorrect key file for table '/tmp/#sql_2736_5.MYI'; try to repair it in /home/xxxx/public_html/yyyy/wp-includes/wp-db.php on line 1924
[21-Aug-2018 14:49:31 UTC] Incorrect key file for table '/tmp/#sql_2736_5.MYI'; try to repair it
[21-Aug-2018 14:49:31 UTC] PHP Warning:  mysqli_num_fields() expects parameter 1 to be mysqli_result, boolean given in /home/xxxx/public_html/yyyy/wp-includes/wp-db.php on line 3182

**Comment by semproz** [comment]
Hi,
Got the same problem "mysqli_num_fields() expects parameter 1 to be mysqli_result, boolean given in" EveryWHERE.

appear when DB cache "ON"

WP 4.9.8
W3TC Version 0.9.7

hope you can find any solution

thanks!

**Comment by ozguryaazici** [comment]
found the problem. If you are using w3tc you need to pay attention to the use of lazyloading. Lazyload gives errors.
