### ISSUE TITLE
Disable original W3 update notification

### ISSUE THREAD

**Issue by E-VANCE** [szepeviktor/fix-w3tc#149]
The update notification is nagging me quite a bit and can lead people to think that an auto-update would be possible – suggesting to disable the W3 notification and instead introduce a GitHub plugin updater like https://github.com/afragen/github-updater.

**Comment by amiga-500** [comment]
Hi @E-VANCE  .. the option to disable the update notification already exists.  Just look under _Performance_ > _General Settings_ > _Miscellaneous_ .  See the attached pic below.  It's unchecked by default, so you'll have to enable it.

![f06611a0-866f-11e6-976e-e0709a0c478e](https://cloud.githubusercontent.com/assets/5191497/19020360/369944f2-8874-11e6-9c9d-4704aebddf7e.jpg)
