### ISSUE TITLE
Include minfied javascript and css in the HTML

### ISSUE THREAD

**Issue by juandavm** [szepeviktor/fix-w3tc#150]
Could be great for AMP, Service Workers, and prefetching to have the possibility of append the minfied javascript and css in the HTML. The way to do it can be: instead of write the html include with the file src tag, write the entire file content generated to it.

I believe that can not be too much complex add this option, but I don't have knowledge of the plugin core. ¿It can be easily done?

Thanks in advance for the consideration.

**Comment by amiga-500** [comment]
True.  It wouldn't be hard to implement at all.  I will eventually look to putting in this feature for ya, eventually.

**Comment by amiga-500** [comment]
Hi @juandavm ... For the fun of it i've added in a new feature just for ya that now allows the inline embedding of minified JS and CSS content directly into the HTML page.

Under _**Minify > JS > Embed Type**_ you will see a new drop-down item called `Inline Content` and under _**Minify > CS**_ you will see a new checkbox item called `Inline Content`.

Cheers
Kimberly
