### ISSUE TITLE
Should I use Redis Object Cache or this W3 Plugin, or are they intended to be used together?

### ISSUE THREAD

**Issue by LZL0** [szepeviktor/fix-w3tc#152]
Should I use Redis Object Cache or this W3 Total Cache Plugin to cache my database, or are they intended to be used together?
https://hu.wordpress.org/plugins/redis-cache/
If these two are separate, which one is faster and more reliable?

Any answer would be appreciated. :)

**Comment by charlesLF** [comment]
Hey @LZL0,

You should only use one of the two plugins.

I haven't run any benchmarking, so I can't tell you which one to pick.

Cheers

**Comment by LZL0** [comment]
Thanks for the response

**Comment by LZL0** [comment]
Reopening... I am doing some benchmarking, I am quite curious.

**Comment by charlesLF** [comment]
I would be very interested in seeing those benchmarking results. Thanks! :)

**Comment by LZL0** [comment]
Okay, I have to check on my setup, although it should work none of the methods above make any difference in terms of load time. The issue must be on my end.
