### ISSUE TITLE
Hi, which branch should I use?

### ISSUE THREAD

**Issue by SteelMill** [szepeviktor/fix-w3tc#154]
Hi,

Apologies for posting a "noob" question, but may i know which version of the fix should I download? I've been reading around here, seems like there's 2 branches.

The original 0.9.4.5 fix, and upon the 0.9.5 release there's a branch for it. Please advise if I should use the 0.9.5.1 branch.

Thanks for all your help to fix this awesome plugin, you guys are awesome!

**Comment by nigrosimone** [comment]
Version 0.9.4.5 is more tested and stable.

**Comment by charlesLF** [comment]
Hey @SteelMill,

Basically what @nigrosimone said.

The master branch contains the most stable version of the plugin.
The 0.9.5 branch is an on-going effort to fix the bugs in the new release of W3TC. It is far from optimal, and I wouldn't recommend using it on a live website.
