### ISSUE TITLE
Question about w3tc official repository.

### ISSUE THREAD

**Issue by nigrosimone** [szepeviktor/fix-w3tc#156]
sorry if i use this place, for this question, but only here i can talk with all persons concerned on the question.

@ftownes 16 days ago [says](https://github.com/szepeviktor/fix-w3tc/issues/57#issuecomment-249866454):

> [...] We had planned to open up the repository to the public closer to v1.0 release, but could be convinced to change that plan. [...] @nigrosimone, @rabin-io, @volnus, @FPCSJames I caught up with @szepeviktor on a call earlier this week.

someone was contacted by @ftownes? there are news about it?

**Comment by FPCSJames** [comment]
I certainly wasn't.

**Comment by szepeviktor** [comment]
I propose not to be theoretical and apply fixes on top of 0.9.5

**Comment by szepeviktor** [comment]
I think no one should commit to master but open PR-s and **stricly** manage a list of fixes.
This list should be checked when we rebase to a new W3TC release.

@nigrosimone Are you sure https://github.com/szepeviktor/fix-w3tc/tree/w3tc-0-9-5 contains all fixed from master?

**Comment by szepeviktor** [comment]
We could call this list *changelog*.

**Comment by nigrosimone** [comment]
>  Are you sure https://github.com/szepeviktor/fix-w3tc/tree/w3tc-0-9-5 contains all fixes from master?

I do not know for sure ... but I think not.

**Comment by nigrosimone** [comment]
Little update from https://www.w3-edge.com/weblog/2016/09/w3-total-cache-v0-9-5-1/

> Looking forward, we’ll be re-visiting our plans for making the github repository public, making our tests available and sharing the roadmap for those who are interested in helping us accelerate it.
