### ISSUE TITLE
Releasing your version as a seperate plugin?

### ISSUE THREAD

**Issue by danger89** [szepeviktor/fix-w3tc#165]
I love this version, since it fixes a lot of issues W3TC themselves won't fix, like PHP7 and APC.

However, for convenient it would be wonderful if you can release this community edition on https://wordpress.org/plugins/. (Maybe rename the project, I don't know?)

I hope you agree?

Kind regards,
Melroy

**Comment by nigrosimone** [comment]
Hi, we have talked a lot [here](https://github.com/szepeviktor/fix-w3tc/issues/57) and we decided to stay on github.

It is not a final decision, but for the moment it's the best choice.

Thank for your interest in this project.
