### ISSUE TITLE
TODO-s

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/fix-w3tc#17]
- revert NewRelic support
- https://github.com/wimg/PHPCompatibility

**Comment by stevesearer** [comment]
@szepeviktor Sorry to hijack this issue thread -- I wanted to ask if there was a preferred way of asking troubleshooting-related questions. 

I'd like to be sensitive to the fact that your voluntarily maintaining this, but had a couple w3tc items I had questions about and wasn't sure if opening an issue was the proper way to ask (without accidentally turning this repo into a github version of the w3tc support forum).

**Comment by nigrosimone** [comment]
@stevesearer unfortunately, here we are a few people, if you need assistance abuot W3TC use the official forum where there's a lot more people. If you have a problem with W3TC-FIX open a issue here.

**Comment by stevesearer** [comment]
@nigrosimone that was what I wanted to know - thanks for your help and for fix-w3tc!

**Comment by szepeviktor** [comment]
Hello @stevesearer !

Actually this is @nigrosimone 's project, I don't do anything here.

Although I provide hourly/monthly rated support for WordPress development and maintenance: viktor@szepe.net
