### ISSUE TITLE
Idea for update/new releases notification

### ISSUE THREAD

**Issue by nigrosimone** [szepeviktor/fix-w3tc#171]
Github has a feed for project releases

https://github.com/szepeviktor/fix-w3tc/releases.atom

we can use this for notification new releases in the fix-w3tc dashboard and/or wp-admin area.

Plus: we can build a custom automatic update procedure (like wordpress.org) see: http://wordpress.stackexchange.com/questions/13/updates-for-a-private-plugin

- [x] fix-w3tc dashboard widget (https://github.com/szepeviktor/fix-w3tc/pull/173)
- [ ] wp-admin area notification
- [ ] custom automatic update procedure (like wordpress.org)

**Comment by amiga-500** [comment]
Ahh that's interesting. Didn't know such a thing existed.

**Comment by nigrosimone** [comment]
@amiga-500 i have added (in the master) a simple widget in the w3tc dashboard.

**Comment by amiga-500** [comment]
AWESOME!
