### ISSUE TITLE
Error when trying to replace official W3TC release

### ISSUE THREAD

**Issue by jkirker** [szepeviktor/fix-w3tc#177]
Simple way to get around this?

Also, noticed the new ver of W3TC makes it appear that fragment caching will not work unless subscribed.  Do you know if this is or isn't the case?  I have some dynamic content which needs to be displayed properly.

AH01071: Got error 'PHP message: PHP Fatal error:  Cannot redeclare w3_is_dbcluster() (previously declared in /home/domain/domains/domain.com/public_html/wp-content/plugins/w3-total-cache/inc/define.php:17) in /home/domain/domains/domain.com/public_html/wp-content/plugins/fix-w3tc-master/inc/define.php on line 186\n', referer: http://domain.com/wp-admin/plugins.php?plugin_status=all&paged=1&s

**Comment by progcode** [comment]
Hi @jkirker,

please follow this steps to active this plugin:

- Deactivate your existing W3 Total Cache plugin (if it exists). DO NOT CLICK THE "DELETE" BUTTON!
- Use FTP or some other file manager to navigate to /wp-content/plugins/ and delete your existing w3-total-cache plugin directory.
- Download and unpack: 0.9.4.5.6 into /wp-content/plugins/
- Rename the extracted directory from fix-w3tc-0.9.4.5.6 to w3-total-cache
- Activate the W3 Total Cache plugin

**Comment by jkirker** [comment]
Got it.  Thank you.  Is Fragment caching still fully supported in fix-w3tc?

**Comment by amiga-500** [comment]
Hi as well, @jkirker 

Yes the [fragment caching](https://www.justinsilver.com/technology/wordpress/w3-total-cache-fragment-caching-wordpress/) feature should work -- but just realize it will require you to use _Disk: Basic_ mode :cry: 

Cheers,
Kimberly

**Comment by jkirker** [comment]
Thank you Kimberly.  For testing purposes I purchased the full license ($99) as it seems the implementation for this has changed recently.  I also use Genesis for the most part so I'm going to do some testing to see if it'd make sense to go that route.  Hate to spend the money but if it'll help performance it may be worthwhile.   Thank you again!!
