### ISSUE TITLE
Checking: 0.9.4.5.6 released two days ago? Rerelease?

### ISSUE THREAD

**Issue by Tarun80** [szepeviktor/fix-w3tc#180]
I noticed that 0.9.4.5.6 says it was released two days ago. Though, I got the one released around November 9th.

With how the version numbers match I was wondering if this is a rerelease or if there were any changes between the two? It did look like a changelog was added into the Github release post, and appears to match the release on Nov 9th.

Sorry for the trouble with this question.

**Comment by amiga-500** [comment]
Hi @Tarun80 ... you can disregard the date issue.  It's all good.

**Comment by Tarun80** [comment]
Thanks Kimberly, appreciate it!
