### ISSUE TITLE
This isn't an issue yet - but... (StackPath)

### ISSUE THREAD

**Issue by jkirker** [szepeviktor/fix-w3tc#185]
I'm curious if anyone is looking at writing code to interface with StackPath's API.  StackPath has acquired MaxCDN and they are in the process of merging.  I had a conversation with a MaxCDN person who said it was unknown whether or not they'd continue to use the MaxCDN api or migrate to StackPath's or use both.  The cool think about StackPath is that SSL is included as part of their CDN solution where MaxCDN charges $99/month to acquire and manage the keys.  It might be something worth looking at.  Not sure how much work it'd be to add it - but it'd certainly create some additional value to folks who want to support SSL.

**Comment by amiga-500** [comment]
Sounds like it could be fun!  When doing the bug fixes for RackSpace CDN it got me intrigued by all of this.  So trying my hand with StackPath APIs would be pretty cool.

## Update
I notice this [recent article](https://support.stackpath.com/hc/en-us/articles/222730587-WordPress-with-W3-Total-Cache-StackPath-CDN-Setup-Guide) on StackPath where despite acquiring MaxCDN they are still advocating the use of it to communicate with their own CDN.  I have to figure when the dust settles Stackpath will likely keep both APIs.
