### ISSUE TITLE
Any issues if using with WP 4.7

### ISSUE THREAD

**Issue by lukecav** [szepeviktor/fix-w3tc#190]
Seems like the original version is having issues causing white screen of death when using it on WordPress 4.7.

Does the fork have any issues in WP 4.7?

https://wordpress.org/support/topic/read-this-first-wordpress-4-7-master-list/#post-8521428

W3 Total cache – Version 0.9.5.1 is incompatible with WordPress 4.7 and you may need to remove it to access your site (Removing the plugin directory is not enough, you also need to remove the db.php, advanced-cache.php and object-cache.php files manually from the wp-content/ directory).

**Comment by amiga-500** [comment]
Not that we know of.  Works fine. 

There is also the w3tc-0-9-5 branch in this repo that drops in patches.  You might want to give that a spin too and see if that resolves your problem.

**Comment by nigrosimone** [comment]
Hi Luke, i have tested on my dev-server "fix-w3tc-0-9-5" branch with wordpress 4.7 (multisite) and it work as expected. Some minutes ago i have update w3tc-0-9-5 branch (for fix a bug with redis)  and all unit tests from 3.7 to 4.7 wordpress version and from 5.3 to 7.1 php version are passed correctly. Probably, the error appears with specific configuration. 

We need more details, eg .: error log

**Comment by nigrosimone** [comment]
Another strange thing is: in the official support forum only two user has reported this issue https://wordpress.org/support/topic/w3-total-cache-offline-website-after-wc-4-7/

**Comment by Tarun80** [comment]
I upgraded to 4.7 on two sites and have had no problems with it and WordPress itself.

**Comment by lukecav** [comment]
Okay good to know, since the issue came up on #forum this morning.

@nigrosimone 
I get around in the WordPress community, mostly trying to help people where I can.

**Comment by lukecav** [comment]
The other one was
https://wordpress.org/support/topic/w3-total-cache-error-white-screen-of-death/

**Comment by nigrosimone** [comment]
@lukecav i have tried to replicate the issue without success. fix-w3tc-0-9-5 works.

**Comment by amiga-500** [comment]
@nigrosimone, tarun80 is talking about fix-w3tc

**Comment by Tarun80** [comment]
Sorry, I should have specified. Fix-W3TC is indeed what I was referring to. Went back and edited my post to clarify.
