### ISSUE TITLE
Some snow plugins don't work with Fix W3TC enabled

### ISSUE THREAD

**Issue by Tarun80** [szepeviktor/fix-w3tc#191]
On a guild website that I run I looked into a plugin to add snow to the frontpage to be festive. Unfortunately I encountered an issue when I tried to use either plugin. 

So far I've tried two plugins:
* [Super Snow](https://wordpress.org/plugins/wp-super-snow/)
* [Snow Flurry](https://wordpress.org/plugins/snow-flurry/)

Interestingly enough, when I disabled Fix-W3TC both plugins work. I attempted to whitelist the *.js files used and unfortunately this did not help. I believe it's because these plugins add javascript code at the end of the body tag.

I'd rather do without snow and have the site loading extremely well. Fix-W3TC is far too valuable!

**Comment by amiga-500** [comment]
Hi @Tarun80!  I will have a look at both plugins now and see if i can fix it.

**Comment by Tarun80** [comment]
Thanks! I poked around with some of the settings to no avail. I can only assume it's cause of the small `<script>` section that gets added that's where the problem may be.

**Comment by amiga-500** [comment]
Hi @Tarun80 

### Super Snow
Seems to works pefectly for me.  I will play with it more to hopefully get it to break.

### Snow Flurry
I found the problem. In the _/wp-content/plugins/snow-flurry/js/_**h5ab-snow-flurry.min.js** file the author has the line **`+i+ +o`**.  He is unnecessarily adding "+" symbol infront of two variables.  The line is simply adding two variables together.  When the minify engine runs it removes the space so it now looks like **`+i++o`**.  That is no longer two variables being added, its a syntax error.  There is no reason the author should have added those "+" signs.

So to get Snow Flurry to work

1. Open _/wp-content/plugins/snow-flurry/js/_**h5ab-snow-flurry.min.js**
2. Search for **`+i+ +o`**
3. Replace it with: **`i+o`**
4. Enjoy

I will now return to _Super Snow_ to figure out how to make it _not_ work so i can hopefully see what u are seeing. :pray:

Cheers
Kimberly :octocat:

**Comment by Tarun80** [comment]
If it helps, I can provide more information (url, other plugins) and the config I use. Could be something on the server end.

It just struck me as odd that it worked when Fix-W3TC was disabled.

**Comment by amiga-500** [comment]
For Super Snow, yea it is very likely due to the javascript ordering being placed in the wrong position among the other plugins js files when minified.  Super Snow only has 1 file being included: _wp-super-snow/src/client-s/js/_**snow.min.js**

For the fun of it, keep w3tc enabled but disabling minify.  It should now work fine.  

I assume you are using Minify: **Auto** mode?  Or are you using **Manual** mode?

Yea what other plugins are you using?  I will install them too.

**Comment by Tarun80** [comment]
An update: Reset to default settings and Super Snow now works. Now to figure out what setting caused it to stop working.

I'm using Manual Mode, with most of the recommendations from GTMetrix and the Hueman theme recommendations.

Thanks for the help!

**Comment by Tarun80** [comment]
Further narrowed, it's part of the JS Minify.

**Comment by amiga-500** [comment]
Since u are using manual mode i figure you have 

`http://0ssd.com/wp-content/plugins/wp-super-snow/src/client-s/js/snow.min.js?ver=151204`

in your JS Minify list?

**Comment by Tarun80** [comment]
Actually, I do not. I held off adding that until it was working.

**Comment by amiga-500** [comment]
Yea, add it in  It is definitely needed to get it working.

**Comment by Tarun80** [comment]
So this is interesting indeed.

`wp-includes/js/jquery/jquery.js`

Add that, and it will break. Nothing will display for the snow. How strange.

**Comment by amiga-500** [comment]
oh jquery is definitely needed...usually the first thing (and only once) in your js list...for example my list looks like this (note how my jquery is the first entry, and my snow.min.js is my 5th).  It doesnt really matter where snow.min.js is as long as it comes after jquery.  You don't want to have more than 1 jquery.js btw

![snip](https://cloud.githubusercontent.com/assets/5191497/21033495/9a53c5f0-bd7e-11e6-91d7-fa9cd6a65c27.jpg)

**Comment by Tarun80** [comment]
Solved it.

Before `</head>` 	x Minify Combine only

When set to `Non-blocking using "async"` you can keep jquery.js in there and it will load just fine.

**Comment by amiga-500** [comment]
Ahhhhh...great to hear its working!

**Comment by amiga-500** [comment]
To be complete, i should point out that for Snow Flurry, the other plugin, i totally forgot to say that you could have also added the line: _`h5ab-snow-flurry.+\.js`_ into the _Never Minify the Following JS Files_ field and it would have solved that snow plugin's coding issue.

Cheers
