### ISSUE TITLE
Rebranding Questions

### ISSUE THREAD

**Issue by amiga-500** [szepeviktor/fix-w3tc#195]
Hi @nigrosimone and @szepeviktor 

Some questions:

1. This repo's name shown above is _szpeviktor/fix-w3tc_. Would it be better to rename the **_fix-w3tc_** part to **_w3-total-cache-fixed_** instead? I was figuring because _w3-total-cache-fixed_ is more descriptive on what this repo is about.  It's changeable via _Settings > Repository Rename_.  Interestingly, if it were renamed, visitors to the old page (fix-w3tc) are automatically redirected to the new one (w3-total-cache-fixed) by github.  I am totally fine with keeping it as _fix-w3tc_ though.

2. Although we have a "_Hide Plugin Update Notification_" feature which hides notifications properly, when _fix-w3tc_ is deactivated in WordPress users will now see the WordPress update notification for the official w3tc release.  Sadly, it's not possible to hide this, and as such, it has understandably caused confusion by users thinking our fix (v0.9.4.x generation) has been updated to v0.9.5.1 because it's doing a version check against the official w3tc release on WordPress plugin site.   This occurs because we are using the same folder name: _w3-total-cache_ as the official plugin.  Should i rename our plugin's directory to _w3-total-cache-fixed_ so that it will permanently cut off ties from the official release which would then stop the notification messages from ever appearing?

I've added in a [GitHub Plugin Updater](https://github.com/radishconcepts/WordPress-GitHub-Plugin-Updater) into our plugin to make updating easier.  However, it would require that we rebrand the directory name for it to work correctly (see # 2 above).  I am just testing it out to make sure it works.  It pretty much acts like a Wordpress update notification but doing a version check against this github repo, allowing the user to download the latest repo release right from the plugin page.

Thanks for the assist
Kimberly :octocat:

**Comment by amiga-500** [comment]
Hi @szepeviktor just reaching out to get your thoughts.

**Comment by nigrosimone** [comment]
1. This repo's name shown above is szpeviktor/fix-w3tc. Would it be better to rename the fix-w3tc part to w3-total-cache-fixed instead?

Only @szepeviktor the owner of the repository can. No problem for me.

2. Although we have a "Hide Plugin Update Notification" [..] it's not possible to hide this

strange... it works for me.

3. I've added in a GitHub Plugin Updater into our plugin to make updating easier. 

Perfect! this is really good idea. But if you want re-brand, why you don't consider the idea to make a new official plugin?
Frederik is gone again, latest release w3tc is totally unstable and the community needs a new man/woman really interested in the maintenance of  "web performance optimization" plugin (like w3tc). You have the skills, and i think, the help of fix-guys  (like me).

**Comment by szepeviktor** [comment]
> w3-total-cache-fixed

You decide.

I think you should attach a proper WP.org conform zip to the releases and direct users to use only that.

> don't have times for maintenance a big project like this

I agree.

**Comment by szepeviktor** [comment]
Last 2 weeks
![2w](https://cloud.githubusercontent.com/assets/952007/21287491/0b1a9210-c46d-11e6-9e16-e8c00e8edee5.png)

**Comment by charlesLF** [comment]
I support the idea of having a proper plugin installable via .zip (without the need to rename folders, etc...).

We could follow an approach similar to what [NextCellent](https://wordpress.org/plugins/nextcellent-gallery-nextgen-legacy/) did when they forked away from NextGen.
> this plugin will gracefully deactivate if detects NextGEN is working (any version) to avoid compatibility issues.

Basically, the plugin would be installed as any other zip plugin would. If it detects that W3TC (official) exists, it will show an admin message stating that the "fix" version requires you to disable w3tc first.

There are some places in the code where the plugin name is hardcoded, so we will need to identify those and change them.

**Comment by szepeviktor** [comment]
> There are some places in the code where the plugin name is hardcoded, so we will need to identify those and change them.

If we exit - upon detecting original w3tc - in the mail plugin file we don't have to care about these.

**Comment by charlesLF** [comment]
> If we exit - upon detecting original w3tc - in the main plugin file we don't have to care about these.
Correct, I meant to type "plugin folder" instead of "plugin name"
Basically constants such as "W3TC_DIR", "W3TC_FILE", that are defined as such:

```
define('W3TC_FILE', 'w3-total-cache/w3-total-cache.php');
define('W3TC_DIR', WP_PLUGIN_DIR . '/w3-total-cache');
```

These would need to point to the "rebranded" folder name.

**Comment by szepeviktor** [comment]
Ok.

**Comment by amiga-500** [comment]
Hi @szepeviktor, thanks for the reply.

Yes can you:

1. Rename this repository name from _fix-w3tc_ to **_w3-total-cache-fixed_**
2. Change this repository description (as seen at the top of this page when on the "Code" tab) to:
_**A community driven build of W3 Total Cache.  The aim is to continuously incorporate fixes, improvements, and enhancements over the official Wordpress release of W3 Total Cache.**_

> I think you should attach a proper WP.org conform zip to the releases and direct users to use only that. So no Rename the extracted directory from fix-w3tc-0.9.4.6 to fix-w3-total-cache._

Agreed.  But just to be clear: You are saying i create a zip file that represents the latest release, then i create a "New Release" here on GitHub and attach it.  By doing this then this should force Github to hide its default "Download Source" zip link (the link that has always required the renaming).  Correct?

Much appreiciated.
Kimberly :octocat:

**Comment by amiga-500** [comment]
Hi @nigrosimone, thanks as well for a reply

> _But if you want re-brand, why you don't consider the idea to make a new official plugin?__

Yea the issue is i too am starting to shift my attention away from this and don't want to dedicate a lot of my time on a huge project.  I just prefer to once in a while jump in to fix some active issue(s) that some users may be having as an intellectual challenge before disappearing again. :stuck_out_tongue:

Cheers,
Kimberly :octocat:

**Comment by szepeviktor** [comment]
> force Github to hide its default "Download Source" zip link

No :(

**Comment by amiga-500** [comment]
Hi @charlesLF ...and thanks to you too for a reply.

> _These would need to point to the "rebranded" folder name._

Bingo!  I found a few other files outside the define.php which hardcoded w3-total-cache.  I made the changes and it all works smoothly.

> _Basically, the plugin would be installed as any other zip plugin would. If it detects that W3TC (official) exists, it will show an admin message stating that the "fix" version requires you to disable w3tc first._

Hey that's useful.  I will implement that too along with the plugin folder rebranding.

Regards
Kimberly :octocat:

**Comment by szepeviktor** [comment]
Done renaming the project.

**Comment by szepeviktor** [comment]
> force Github to hide its default "Download Source" zip link

But you may call the uploaded zip `w3-total-cache-fixed-DOWNLOAD-THIS.zip`

**Comment by amiga-500** [comment]
> _Done renaming the project._
> _But you may call the uploaded zip w3-total-cache-fixed-DOWNLOAD-THIS.zip_

As always...much appreciated! 💘

**Comment by charlesLF** [comment]
>  I just prefer to once in a while jump in to fix some active issue(s) that some users may be having as an intellectual challenge before disappearing again.

+1 for the "intellectual challenge" part :laughing:

**Comment by amiga-500** [comment]
Oh I was successfully able to get update notifications and installs working from within the WP plugin page 😀.  It uses a non-intrusive GitHub updater embeded within w3tc.  I had to make bug fixes though to it to get it to work properly.  I even have it showing plugin details when they click the "_View Details_" button.

Essentially, it acts just like any other WordPress plugin from within the admin page.  So once a person manually installs our zip from here for the first time (to get this feature) then they shouldn't have to ever return here again to check for nor need to install a new update by hand.  It handles it all.  :bowtie: 

![updater](https://cloud.githubusercontent.com/assets/5191497/21296829/92254c16-c542-11e6-9390-b10f190827d1.png)

The plugin folder name still had to be rebranded though because if it was kept as _w3-total-cache_ then WP overrides the Github check and checks its own (the official w3tc version).

I have a few other updates to this repo that i will be pushing but want to do a few more tests.  For example, i added Amazon Web Services v4 Signature support since many of their endpoints/regions only support v4 and more and more people are finding their S3 service was failing.  I will consider adding this update into the v0.9.5.x generation too later.

Cheers
Kimberly :octocat:

**Comment by szepeviktor** [comment]
Thank you for your work.

I am not able to help as the works-for-me&no-one-reports-a-bug workflow knocks me out.

**Comment by amiga-500** [comment]
> _Thank you for your work.  I am not able to help as the works-for-me&no-one-reports-a-bug workflow knocks me out._

Hey, not a problem!  It's always fun! 👍

**Comment by nigrosimone** [comment]
Thanks Kimberly! Great job!
