### ISSUE TITLE
Talk issue

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/fix-w3tc#2]
@nigrosimone All of the todos are one-liners (OK, not 1 but maybe 5) except the OPcache compatibility which needs some research.

Have you met these problems?

You are free to send PR-s!

**Comment by nigrosimone** [comment]
ok, i have fixed all php7 issue and all deprecation issue. i don't understand "OPcache compatibility " w3tc is compatible with OPcache, OPcache improves PHP performance by storing precompiled script bytecode in shared memory, thereby removing the need for PHP to load and parse scripts on each request.

**Comment by szepeviktor** [comment]
If you disable stat-ing php files in opcache there will be issues with W3TC as it stores config in php files.

W3TC solves this on apc opcode cache by flushing these configs,  this needs to be ported to opcache.


-- 
+36204242498
Ezen a készüléken sok az elütés. 
Elnézést!

**Comment by szepeviktor** [comment]
Could you open a PR?
One commit per feature please. 

-- 
+36204242498
Ezen a készüléken sok az elütés. 
Elnézést!

**Comment by szepeviktor** [comment]
@nigrosimone Please show your code as I am into this project right now...

**Comment by nigrosimone** [comment]
@szepeviktor i send a mail viktor [at] szepe [dot] net

**Comment by szepeviktor** [comment]
@nigrosimone You may use https://git-scm.com/downloads on Vista. I hope it works.

I suggest you to switch to Win10: https://github.com/szepeviktor/windows-workstation
