### ISSUE TITLE
Request: add w3tc_pgcache_flush_url to 0.9.5 branch

### ISSUE THREAD

**Issue by smerriman** [szepeviktor/fix-w3tc#205]
In the 0.9.4 branch, there are functions to clear caches programatically:

w3tc_pgcache_flush()
w3tc_pgcache_flush_post($post_id)
w3tc_pgcache_flush_url($url)

When Frederick released 0.9.5, these were deprecated and replaced by:

w3tc_flush_posts()
w3tc_flush_post($post_id)
w3tc_flush_url($url)

The first two have shortcuts in w3-total-cache-api.php so they continue to work - but the **third** was removed entirely, causing a php error on upgrade if used.

Can you add a shortcut for the latter back in?

**Comment by szepeviktor** [comment]
Yes.

**Comment by amiga-500** [comment]
Done
