### ISSUE TITLE
APC vs APCu

### ISSUE THREAD

**Issue by dreadedhamish** [szepeviktor/fix-w3tc#22]
Hi guys,
I noticed APCu support.
Can anyone give any background to this, and what the consequences of using it are?

Is it a safe drop-in to use everywhere I would have used APC in w3tc? (I know enough to know it's different in that it doesn't have an opcode cache itself, but I don't know enought to know the consequences.)

Thanks.

**Comment by nigrosimone** [comment]
- APC is opcode cache and data store
- APCu is only data store
- OPcache is only opcode cache

OPcache improves PHP performance by storing precompiled script bytecode in shared memory. This extension is bundled with PHP 5.5.0 and later, and is » available in PECL for PHP versions 5.2, 5.3 and 5.4.

APCu is APC stripped of opcode caching. APCu can provide a compatibility mode, such that it can provide a drop in replacement for the applicable parts of APC (APCu-BC).
