### ISSUE TITLE
Implementation of modern feature "assets preload"

### ISSUE THREAD

**Issue by nigrosimone** [szepeviktor/fix-w3tc#227]
When one script is loaded in the footer, eg.:

    <script src="/some.js"></script>
    </body>
    </html>

w3tc can put in the head the preload tag, eg.:

    <link rel="preload" href="/some.js" as="script">
    </head>

when the browsers read the head, download in background the script and execute it when found script tag in the footer. 

My proposal https://github.com/szepeviktor/w3-total-cache-fixed/pull/226.

Please help me to test it. It works only with latest chrome (i have windows vista and can't install latest chrome)

**Comment by amiga-500** [comment]
Wow, wonderful new feature!  Thanks. 🙌   I will also test this when i get back later tonight.  I'm at a mall doing xmas shopping at the moment.

**Comment by superpoincare** [comment]
Since there's less support as you point out in https://github.com/szepeviktor/w3-total-cache-fixed/issues/228 this will really need a polyfill. 

I think a genuine polyfill can be made without bugs. 

Also for javascript files - this is not that great an advantage as defer/async can be used for most purposes. I am interested to see cases where preload is better than defer/sync. 

All of this for pull-preload. Push preload (http2 server side push) has genuine advantages. 

Pull Preload is more useful for css files. One needs inline css and then a preload declaration and a polyfill. 

IMO, the only non-buggy way to do it (polyfill) is put a script at the bottom of the body to load in on Domready or use requestAnimationFrame. 

I use polyfill via requestAnimationFrame.

**Comment by superpoincare** [comment]
I do it like this (with optimization added for subsequent visits using sessionStorage, although it's not needed). 

```html
<head>

	<style>
		/*inline styles*/
	</style>
	<script>
		function preloadFinished( el ) {
			var res = document.createElement("link");
			res.rel = "stylesheet";
			res.href = el.href;
			el.parentNode.insertBefore( res, el.nextSibling );
		}
	</script>
	<link rel="preload" href="path/to/style.min.css" as="style" onload="preloadFinished(this)">
	<script>
		var linkSupportsPreload = function() {
			try {
				return document.createElement("link").relList.supports("preload");
			} catch (e) {
				return false;
			}
		}

		var sessionStorageAvailable = function() {
			var x = '__storage_test__';
			try {
				sessionStorage.setItem(x, x);
				sessionStorage.removeItem(x);
				return true;
			} catch (e) {
				return false;
			}
		}

		var cb = function() {
			var links = document.getElementsByTagName("link");
			for (var i = 0; i < links.length; i++ ) {
				var link = links[i];
				if( link.rel === "preload" && link.getAttribute( "as" ) === "style" ) {
					preloadFinished(link);
				}
			}
		}

		if( !linkSupportsPreload()) {
			if (sessionStorageAvailable()) {
				if(sessionStorage.fullcssloaded) {
					cb();
				}
			}
		}
	</script>

</head>
<body>

	<!--Near the footer area-->
	<script>
		var rAF = (function() {
			return window.requestAnimationFrame || window.mozRequestAnimationFrame || window.msRequestAnimationFrame || window.oRequestAnimationFrame || window.webkitRequestAnimationFrame || function( callback ) {
				window.setTimeout(callback, 1000 / 60);
			}
		})();

		if( !linkSupportsPreload() ) {
			if (sessionStorageAvailable()) {
				if(sessionStorage.fullcssloaded) {
					
				} else {
					setTimeout(function() {
						rAF(cb);
						sessionStorage.fullcssloaded = "true";
		
		                        });
				}
			} else {
				setTimeout(function() {
					rAF(cb);
				});
			}
		}
	</script>
</body>
`

**Comment by nigrosimone** [comment]
@vijayaraghavanramanan it seems too specific for css lazy loading in non blocking manner, but it has interesting ideas like a method for checking if browser support preload:
```javascript
function linkSupportsPreload() {
    try {
         return document.createElement("link").relList.supports("preload");
    } catch (e) {
        return false;
    }
}
```

now, the ideas behind "preload" is inform the browser on pre-download some resources that can use later like script, image, video, css... then simply: a polyfill should only download the resource.

i think the only generic polyfill in according with the W3 draft is:

```javascript
function linkSupportsPreload() {
    try {
         return document.createElement("link").relList.supports("preload");
    } catch (e) {
        return false;
    }
}
// if browser doesn't support link preload
if (  !linkSupportsPreload()  ){
   // collect all link element
    var links = document.getElementsByTagName("link");
    for (var i = 0; i < links.length; i++ ) {
        var link = links[i];
        if( link.rel === "preload" ) {
            // use a image for download in a asynchronously manner
            var img = document.createElement("img");
            img.src = link.href;
            img.style.display = "none";
            document.body.appendChild(img);			
        }
    }
}
```

This code must be placed immediately after link preload section, not before and not in the footer (because the point is pre-download in the head).

_Why i use an image for download the resources?_

1. the image is supported from the dawn of the internet, it works on all browser. requestAnimationFrame, sessionStorage are others modern features;

2. the browser just download the image in a asynchronously manner without execute nothing, we can pre-download js, css, video, audio without side effect.

**Comment by superpoincare** [comment]
Not sure I understand this right. Are you downloading css files as image?

Btw, I came across your plugin: https://wordpress.org/plugins/speed-up-optimize-css-delivery/

Does this work with W3TC CSS minification turned on? 

As in does it load the css file which has been minified by W3 Total Cache or w3tc-fixed?

Yeah my code was highly specific: I have used codes from various places: so the feature-detection is from loadCSS's code.

**Comment by nigrosimone** [comment]
> Are you downloading css files as image?

nope... in this PR i download only the scripts as image.

> Btw, I came across your plugin: [...] Does this work with W3TC CSS minification turned on?

nope

> As in does it load the css file which has been minified by W3 Total Cache or w3tc-fixed?

nope

we talking about two different problem: implementing link preload and solve render blocking for css.

My plugin (without w3tc), is a wordpress implementation of current [loadCSS](https://github.com/filamentgroup/loadCSS). It try to solve "render blocking for css".

Side note.... i have play around css render blocking question... 

i have made a basic test page based on my polyfill . In this page i load 9 render blocking css
http://www.sndesign.it/shared/gpsi/

each css responds after some seconds (random from 3 to 9) and make "green" one box when is loaded.

and seem works https://developers.google.com/speed/pagespeed/insights/?hl=en&url=http%3A%2F%2Fwww.sndesign.it%2Fshared%2Fgpsi%2F

google page speed 100/100

**Comment by nigrosimone** [comment]
Side note.... i have play around css render blocking question... 

i make a basic test page based on my polyfill . In this page i load 3 render blocking css
http://www.sndesign.it/shared/gpsi/test1.html

and seem works https://developers.google.com/speed/pagespeed/insights/?hl=it&url=http%3A%2F%2Fwww.sndesign.it%2Fshared%2Fgpsi%2Ftest1.html

google page speed 100/100

**Comment by nigrosimone** [comment]
@vijayaraghavanramanan my idea is totally wrong. Your idea seems better!

test page here:

http://www.sndesign.it/shared/gpsi/test2.html 

google page speed 100/100

https://developers.google.com/speed/pagespeed/insights/?hl=en&url=http%3A%2F%2Fwww.sndesign.it%2Fshared%2Fgpsi%2Ftest2.html

**Comment by nigrosimone** [comment]
I close ... after many tests it is difficult to release a stable version. Better to wait to have a better idea.

**Comment by superpoincare** [comment]
Yeah it's a bit more complicated and site-specific. 

Btw, you can preload scripts as scripts and not image. Not sure still what you were trying with images. 

(I understand that since browsers load images with low priority, preloading images can be good). 

But I think as as far as w3tc is concerned, if there's one js file in the footer, preloading it is a good idea. Just `"as=script"`

**Comment by nigrosimone** [comment]
@vijayaraghavanramanan i have abandoned my primary idea (download as image). I'm concerned on yours idea (use requestAnimationFrame)

you can see my test here:
http://www.sndesign.it/shared/gpsi/test2.html

i want try to preload without side effects.
