### ISSUE TITLE
js-preload branch question

### ISSUE THREAD

**Issue by superpoincare** [szepeviktor/fix-w3tc#228]
May I know what changes are intended in the js-preload branch?

Having a preload feature is super-interesting. 

I do see however that nothing is done for browsers not supporting preload. So you may have to polyfill it. (And also add a code on what happens `onload` once preload is finished).

**Comment by nigrosimone** [comment]
At the moment the preload features is a [draft](https://www.w3.org/TR/preload/) and is a work in progress by World Wide Web Consortium (W3C).

Only [few browser](http://caniuse.com/#feat=link-rel-preload) have implemented it:

- IE/Edge status: Under Consideration
- Chrome status: Enabled by default
 - WebKit/Firefox status: In Development

I have found some polyfill, but all really bugged and i think it's better to realese this feature without polyfill, we are w3-total-cache-**fixed** the basic idea is fix the issues and not introduce a new issues :D

we are under community review https://github.com/szepeviktor/w3-total-cache-fixed/issues/227. If you try it, please give me some feedback.

Thanks,
Simone

**Comment by superpoincare** [comment]
Sure, will comment there
