### ISSUE TITLE
Minor - Icon by Performance disappeared

### ISSUE THREAD

**Issue by Tarun80** [szepeviktor/fix-w3tc#230]
0.9.4.6 - the icon in the WordPress admin panel has disappeared. Cleared cache (site and browser both) though this happens on multiple sites.

![Missing icon](https://i.imgur.com/uqqSG70.png)

**Comment by amiga-500** [comment]
Hi @Tarun80 thanks a bunch for the heads up!  Yea i spotted that last night and put in a commit, fixing it.  Sorry about that!  So it's resolved but you won't see a "_new version available_" in your wp plugin page just yet.  We wanted to add some more things into the next version (e.g. security headers extension, assets preload, etc) first.

However, to make it easy for ya here are those updated files that you can download here and replace on your end.  This will restore the missing icon:


[lib/W3/Plugin/TotalCacheAdmin.php](https://raw.githubusercontent.com/szepeviktor/w3-total-cache-fixed/76d66667fbe06d77c15c2488b39b63be31135536/lib/W3/Plugin/TotalCacheAdmin.php)
[extensions/CloudFlareAdmin.php](https://raw.githubusercontent.com/szepeviktor/w3-total-cache-fixed/76d66667fbe06d77c15c2488b39b63be31135536/extensions/CloudFlareAdmin.php) 
[extensions/FeedBurnerAdmin.php](https://raw.githubusercontent.com/szepeviktor/w3-total-cache-fixed/76d66667fbe06d77c15c2488b39b63be31135536/extensions/FeedBurnerAdmin.php)
[extensions/GenesisAdmin.php](https://raw.githubusercontent.com/szepeviktor/w3-total-cache-fixed/76d66667fbe06d77c15c2488b39b63be31135536/extensions/GenesisAdmin.php)
[extensions/WordPressSEOAdmin.php](https://raw.githubusercontent.com/szepeviktor/w3-total-cache-fixed/76d66667fbe06d77c15c2488b39b63be31135536/extensions/WordPressSEOAdmin.php)
[inc/options/install.php](https://raw.githubusercontent.com/szepeviktor/w3-total-cache-fixed/76d66667fbe06d77c15c2488b39b63be31135536/inc/options/install.php)

Technically, you only need the first file: _lib/W3/Plugin/TotalCacheAdmin.php_ to restore the icon for "_Performance_" but just figured to give you a list of other files that were changed too.

Cheers
Kimberly :octocat:

**Comment by Tarun80** [comment]
Just as a heads up, GenesisAdmin.php is not raw. For anyone viewing the raw [GenesisAdmin.php is here](https://raw.githubusercontent.com/szepeviktor/w3-total-cache-fixed/76d66667fbe06d77c15c2488b39b63be31135536/extensions/GenesisAdmin.php).
