### ISSUE TITLE
[0.9.5.x] Possibly not PHP 7.0 compatible

### ISSUE THREAD

**Issue by RafaelDeJongh** [szepeviktor/fix-w3tc#235]
After being redirected here from the support forum when asking the question if W3TC was PHP7 compatible, I did a new check after that but this resulted in the same problem being it not fully PHP7 compatible:

<pre>FILE: /home/johannes/public_html/rafaeldejongh.com/wp-content/plugins/w3-total-cache/lib/SNS/lib/requestcore/requestcore.class.php
----------------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------------------------------------------------------------------
 650 | WARNING | INI directive 'safe_mode' is deprecated since PHP 5.3 and removed since PHP 5.4.
----------------------------------------------------------------------------------------------------------------------------------

FILE: /home/johannes/public_html/rafaeldejongh.com/wp-content/plugins/w3-total-cache/lib/Nusoap/class.soap_transport_http.php
-----------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 2 WARNINGS AFFECTING 2 LINES
-----------------------------------------------------------------------------------------------------------------------------
 284 | WARNING | INI directive 'safe_mode' is deprecated since PHP 5.3 and removed since PHP 5.4.
 287 | WARNING | INI directive 'safe_mode' is deprecated since PHP 5.3 and removed since PHP 5.4.
-----------------------------------------------------------------------------------------------------------------------------

FILE: /home/johannes/public_html/rafaeldejongh.com/wp-content/plugins/w3-total-cache/lib/Nusoap/nusoap.php
--------------------------------------------------------------------------------------------------------------------------------
FOUND 37 ERRORS AND 2 WARNINGS AFFECTING 31 LINES
--------------------------------------------------------------------------------------------------------------------------------
 2437 | WARNING | INI directive 'safe_mode' is deprecated since PHP 5.3 and removed since PHP 5.4.
 2440 | WARNING | INI directive 'safe_mode' is deprecated since PHP 5.3 and removed since PHP 5.4.
 3635 | ERROR   | The use of long predefined variables has been deprecated in 5.3 and removed in 5.4; Found '$HTTP_SERVER_VARS'
 3640 | ERROR   | The use of long predefined variables has been deprecated in 5.3 and removed in 5.4; Found '$HTTP_SERVER_VARS'
 3642 | ERROR   | The use of long predefined variables has been deprecated in 5.3 and removed in 5.4; Found '$HTTP_SERVER_VARS'
 3658 | ERROR   | The use of long predefined variables has been deprecated in 5.3 and removed in 5.4; Found '$HTTP_SERVER_VARS'
 3659 | ERROR   | The use of long predefined variables has been deprecated in 5.3 and removed in 5.4; Found '$HTTP_SERVER_VARS'
 3695 | ERROR   | The use of long predefined variables has been deprecated in 5.3 and removed in 5.4; Found '$HTTP_SERVER_VARS'
 3699 | ERROR   | The use of long predefined variables has been deprecated in 5.3 and removed in 5.4; Found '$HTTP_SERVER_VARS'
 3700 | ERROR   | The use of long predefined variables has been deprecated in 5.3 and removed in 5.4; Found '$HTTP_SERVER_VARS'
 3707 | ERROR   | The use of long predefined variables has been deprecated in 5.3 and removed in 5.4; Found '$HTTP_SERVER_VARS'
 3708 | ERROR   | The use of long predefined variables has been deprecated in 5.3 and removed in 5.4; Found '$HTTP_SERVER_VARS'
 3779 | ERROR   | The use of long predefined variables has been deprecated in 5.3 and removed in 5.4; Found '$HTTP_SERVER_VARS'
 3842 | ERROR   | The use of long predefined variables has been deprecated in 5.3 and removed in 5.4; Found '$HTTP_SERVER_VARS'
 3844 | ERROR   | The use of long predefined variables has been deprecated in 5.3 and removed in 5.4; Found '$HTTP_SERVER_VARS'
 4419 | ERROR   | The use of long predefined variables has been deprecated in 5.3 and removed in 5.4; Found '$HTTP_SERVER_VARS'
 4439 | ERROR   | The use of long predefined variables has been deprecated in 5.3 and removed in 5.4; Found '$HTTP_SERVER_VARS'
 4439 | ERROR   | The use of long predefined variables has been deprecated in 5.3 and removed in 5.4; Found '$HTTP_SERVER_VARS'
 4440 | ERROR   | The use of long predefined variables has been deprecated in 5.3 and removed in 5.4; Found '$HTTP_SERVER_VARS'
 4441 | ERROR   | The use of long predefined variables has been deprecated in 5.3 and removed in 5.4; Found '$HTTP_SERVER_VARS'
 4442 | ERROR   | The use of long predefined variables has been deprecated in 5.3 and removed in 5.4; Found '$HTTP_SERVER_VARS'
 4442 | ERROR   | The use of long predefined variables has been deprecated in 5.3 and removed in 5.4; Found '$HTTP_SERVER_VARS'
 4442 | ERROR   | The use of long predefined variables has been deprecated in 5.3 and removed in 5.4; Found '$HTTP_SERVER_VARS'
 4443 | ERROR   | The use of long predefined variables has been deprecated in 5.3 and removed in 5.4; Found '$HTTP_SERVER_VARS'
 4443 | ERROR   | The use of long predefined variables has been deprecated in 5.3 and removed in 5.4; Found '$HTTP_SERVER_VARS'
 4508 | ERROR   | The use of long predefined variables has been deprecated in 5.3 and removed in 5.4; Found '$HTTP_SERVER_VARS'
 4514 | ERROR   | The use of long predefined variables has been deprecated in 5.3 and removed in 5.4; Found '$HTTP_SERVER_VARS'
 4514 | ERROR   | The use of long predefined variables has been deprecated in 5.3 and removed in 5.4; Found '$HTTP_SERVER_VARS'
 4515 | ERROR   | The use of long predefined variables has been deprecated in 5.3 and removed in 5.4; Found '$HTTP_SERVER_VARS'
 4516 | ERROR   | The use of long predefined variables has been deprecated in 5.3 and removed in 5.4; Found '$HTTP_SERVER_VARS'
 4517 | ERROR   | The use of long predefined variables has been deprecated in 5.3 and removed in 5.4; Found '$HTTP_SERVER_VARS'
 4518 | ERROR   | The use of long predefined variables has been deprecated in 5.3 and removed in 5.4; Found '$HTTP_SERVER_VARS'
 4518 | ERROR   | The use of long predefined variables has been deprecated in 5.3 and removed in 5.4; Found '$HTTP_SERVER_VARS'
 4518 | ERROR   | The use of long predefined variables has been deprecated in 5.3 and removed in 5.4; Found '$HTTP_SERVER_VARS'
 4519 | ERROR   | The use of long predefined variables has been deprecated in 5.3 and removed in 5.4; Found '$HTTP_SERVER_VARS'
 4519 | ERROR   | The use of long predefined variables has been deprecated in 5.3 and removed in 5.4; Found '$HTTP_SERVER_VARS'
 5339 | ERROR   | The use of long predefined variables has been deprecated in 5.3 and removed in 5.4; Found '$HTTP_SERVER_VARS'
 5343 | ERROR   | The use of long predefined variables has been deprecated in 5.3 and removed in 5.4; Found '$HTTP_SERVER_VARS'
 5344 | ERROR   | The use of long predefined variables has been deprecated in 5.3 and removed in 5.4; Found '$HTTP_SERVER_VARS'
--------------------------------------------------------------------------------------------------------------------------------

FILE: /home/johannes/public_html/rafaeldejongh.com/wp-content/plugins/w3-total-cache/lib/Nusoap/class.wsdl.php
-----------------------------------------------------------------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 3 LINES
-----------------------------------------------------------------------------------------------------------------------------
 758 | ERROR | The use of long predefined variables has been deprecated in 5.3 and removed in 5.4; Found '$HTTP_SERVER_VARS'
 762 | ERROR | The use of long predefined variables has been deprecated in 5.3 and removed in 5.4; Found '$HTTP_SERVER_VARS'
 763 | ERROR | The use of long predefined variables has been deprecated in 5.3 and removed in 5.4; Found '$HTTP_SERVER_VARS'
-----------------------------------------------------------------------------------------------------------------------------

FILE: /home/johannes/public_html/rafaeldejongh.com/wp-content/plugins/w3-total-cache/lib/Db/mssql.php
-----------------------------------------------------------------------------------------------------
FOUND 24 ERRORS AFFECTING 23 LINES
-----------------------------------------------------------------------------------------------------
  530 | ERROR | Extension 'mssql' is removed since PHP 7.0
  531 | ERROR | Extension 'mssql' is removed since PHP 7.0
  532 | ERROR | Extension 'mssql' is removed since PHP 7.0
  553 | ERROR | Extension 'mssql' is removed since PHP 7.0
  758 | ERROR | Extension 'mssql' is removed since PHP 7.0
  936 | ERROR | Extension 'mssql' is removed since PHP 7.0
 1060 | ERROR | Extension 'mssql' is removed since PHP 7.0
 1076 | ERROR | Extension 'mssql' is removed since PHP 7.0
 1077 | ERROR | Extension 'mssql' is removed since PHP 7.0
 1078 | ERROR | Extension 'mssql' is removed since PHP 7.0
 1144 | ERROR | Extension 'mssql' is removed since PHP 7.0
 1147 | ERROR | Extension 'mssql' is removed since PHP 7.0
 1156 | ERROR | Extension 'mssql' is removed since PHP 7.0
 1161 | ERROR | Extension 'mssql' is removed since PHP 7.0
 1168 | ERROR | Extension 'mssql' is removed since PHP 7.0
 1171 | ERROR | Extension 'mssql' is removed since PHP 7.0
 1191 | ERROR | Extension 'mssql' is removed since PHP 7.0
 1205 | ERROR | Extension 'mssql' is removed since PHP 7.0
 1208 | ERROR | Extension 'mssql' is removed since PHP 7.0
 1208 | ERROR | Extension 'mssql' is removed since PHP 7.0
 1216 | ERROR | Extension 'mssql' is removed since PHP 7.0
 1217 | ERROR | Extension 'mssql' is removed since PHP 7.0
 1240 | ERROR | Extension 'mssql' is removed since PHP 7.0
 1251 | ERROR | Extension 'mssql' is removed since PHP 7.0
-----------------------------------------------------------------------------------------------------

FILE: /home/johannes/public_html/rafaeldejongh.com/wp-content/plugins/w3-total-cache/Enterprise_Dbcache_WpdbInjection_Cluster.php
---------------------------------------------------------------------------------------------------------------------------------
FOUND 17 ERRORS AFFECTING 17 LINES
---------------------------------------------------------------------------------------------------------------------------------
 374 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
 444 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
 467 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
 473 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
 516 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
 523 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
 537 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
 543 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
 547 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
 555 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
 556 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
 562 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
 567 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
 642 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
 655 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
 787 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
 793 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
---------------------------------------------------------------------------------------------------------------------------------

FILE: /home/johannes/public_html/rafaeldejongh.com/wp-content/plugins/w3-total-cache/inc/lightbox/self_test.php
---------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
---------------------------------------------------------------------------------------------------------------
 171 | WARNING | INI directive 'safe_mode' is deprecated since PHP 5.3 and removed since PHP 5.4.
---------------------------------------------------------------------------------------------------------------</pre>

This is using the 0.9.5.x version release. So is it or, isn't it PHP7 compatible?

**Comment by nigrosimone** [comment]
There are two actively maintained W3TC (Fixed) generations in this repository: Version 0.9.4.x and Version 0.9.5.x. Only version 0.9.4.x is full PHP7 Compliancy (Passes PHPCompatibility: 100%).

**Comment by RafaelDeJongh** [comment]
Thanks for your fast reply!

And that's a shame that only 9.4 is fully php7 compatible for now at least.
 
In general I do prefer 9.5 as I've been using that one before and wouldn't really want to revert to 9.4.
So my question here then is, would everything still work even with 9.5 and php7 or do I really have to revert to 9.4 to make it work with php7?

And is there any future thought in getting 9.5 also fully php7 compatible?

**Comment by nigrosimone** [comment]
> And is there any future thought in getting 9.5 also fully php7 compatible?

honestly... we are a little group of developers (only two really active) and we are all concentrated on the 9.4. Version 9.4 is stable and ready to use in production, has tons of fix and improvments. 

Side note: "W3 total cache **fixed** 9.4" is totally different from official "w3 total cache" old version. w3 total cache **fixed** 9.5 is a simple copy of last w3 total cache from wordpress repo, with few little fix.

my advice, if you want to use W3TC-FIX, use 9.4. I have totally abandoned the idea to work on 9.5 because has too many bugs and i have to few free time to fix it.

**Comment by RafaelDeJongh** [comment]
That's completely understandable, yet quite unfortunate as 9.4 is rather old already (being from 2015) but well I do understand that with only two developers your main focus would be on something that has been put more work into.

My only question here would then be, would 9.5 still function correctly with PHP7 enabled? Or are there really plugin breaking things that happen when PHP7 is used with either the vanilla 9.5 or your edits?

Thanks for the reply in adavance.

**Comment by amiga-500** [comment]
From what i can see yes 9.5 should still function correctly despite the many, many PHP7 errors.  It's been a while since we fixed all the php7 errors from the 0.9.4.x so i can't give you a precise way to make 9.5 collapse (it's in there but i can't remember) but for general use 9.5 should be fine.  

When things start settling down then at the very least i can go fix all those php7 bugs+warnings from 9.5.

For the fun of it way back in a different thread here people were asking so we ran php7 tests.  Here is a snapshot of those results:

![wordpress_adoption_program_for_abandoned_plugins_issue_57_szepeviktor_w3-total-cache-fixed_-_2017-01-03_16_34_54](https://cloud.githubusercontent.com/assets/5191497/21623887/97439346-d1d2-11e6-89be-445230c90261.png)

Cheers
Kimberly :octocat:

**Comment by RafaelDeJongh** [comment]
That indeed was a nice comparison and thank you for the information! That sure makes me a bit more relieved that I don't really need to mind the function of the plugin now that I've switched to PHP7!

Either way I thank you all for replying to my issue, and wish you the best of luck in the future with this project!

**Comment by nigrosimone** [comment]
@amiga-500 from @RafaelDeJongh [report ](https://github.com/szepeviktor/w3-total-cache-fixed/issues/235#issue-198339147) the major issue are in common lib between v0.9.5.x and v0.9.4.x i think a simple copy/paste make v0.9.5.x compatible. The file are:

- /lib/SNS/lib/requestcore/requestcore.class.php
- /lib/Nusoap/class.soap_transport_http.php
- /lib/Nusoap/nusoap.php
- /lib/Nusoap/class.wsdl.php
- /lib/Db/mssql.php
- /Enterprise_Dbcache_WpdbInjection_Cluster.php **(the only one new)**
- /inc/lightbox/self_test.php

what do you think? you have already fixed in the v0.9.4.x!

**Comment by amiga-500** [comment]
Hey nice catch @nigrosimone !

Yea you're right!  From a quick look it seems these following 4 files can be ported directly from v0.9.4.x into v0.9.5.x right now, as you said, to give it a nice boost in php7 compatibility:

* /lib/SNS/lib/requestcore/requestcore.class.php
* /lib/Nusoap/class.soap_transport_http.php
* /lib/Nusoap/class.wsdl.php
* /lib/Nusoap/nusoap.php

However, the following two files still need some adjusting.  So i figure it would start with a port from the equivalent v0.9.4.x files and then make the changes in them to match what v0.9.5.x needs:

* /lib/Db/mssql.php
* /inc/lightbox/self_test.php

And the last file, as you mentioned, doesnt exist and so this would be the only file that would require its own PHP 7 testing on our part to find what it needs fixing:

* /Enterprise_Dbcache_WpdbInjection_Cluster.php

Awesome!  I'm heading to sleep right now but i can work on this when i get up.  It shouldn't take that long.

Cheers
Kimberly :octocat:

**Comment by nigrosimone** [comment]
@amiga-500 thanks as always!

**Comment by RafaelDeJongh** [comment]
Oh that sounds really promising! Really looking forward for it and thanks for looking into these things everyone! Much appreciated 👍

**Comment by amiga-500** [comment]
Done @RafaelDeJongh - full PHP7 compliancy in v0.9.5.x :bowtie: 
Thanks @nigrosimone for the heads up.  It made a big difference.

**Comment by RafaelDeJongh** [comment]
@amiga-500 

Amazing, I'll get it installed right away! Much appreciated ;)
