### ISSUE TITLE
 Cannot use output buffering in output - AMP plugin compatibility issue

### ISSUE THREAD

**Issue by progcode** [szepeviktor/fix-w3tc#237]
I installed[ WordPress AMP](https://hu.wordpress.org/plugins/amp/) plugin, but I got the following error while minify is enabled:

`Fatal error: Unknown: Cannot use output buffering in output buffering display handlers in Unknown on line 0`

If the minify is disabled the AMP plugin works properly.

**Comment by progcode** [comment]
The problem is here: '**lib/W3/Plugin/Minify.php**' line 131 `function ob_callback($buffer)`

**Comment by amiga-500** [comment]
Much appreicated @progcode!
