### ISSUE TITLE
svg max-age cache header

### ISSUE THREAD

**Issue by superpoincare** [szepeviktor/fix-w3tc#242]
Right now, svg files have the same cache settings as html files for _max-age_. Strangely expiry is that of image files. 

svg fonts are no longer in use but svg's usage is rising both for images and for emoji. (Example usage: self-hosting Twemoji).

So I think it makes sense to make the cache setting for emoji files the same as image files.

**Comment by nigrosimone** [comment]
The **svg** cache expire value is under "Media & Other files" in "Browser cache" section.

**Comment by superpoincare** [comment]
Right, but its max-age is that of html. And if both max-age and expiry are sent, then the browser gives preference to max-age and doesn't cache the svg file.

**Comment by nigrosimone** [comment]
you are right... mhh but why? this is a strange design choice. I don't understand why rtf, rtx and svg are in this list... 

```htaccess
<FilesMatch "\.(html|htm|rtf|rtx|svg|svgz|txt|xsd|xsl|xml|HTML|HTM|RTF|RTX|SVG|SVGZ|TXT|XSD|XSL|XML)$">
    FileETag MTime Size
    <IfModule mod_headers.c>
        Header set Pragma "no-cache"
        Header set Cache-Control "max-age=0, private, no-store, no-cache, must-revalidate"
         Header set X-Powered-By "W3 Total Cache/0.9.4.6"
    </IfModule>
</FilesMatch>
```

**Comment by amiga-500** [comment]
I believe the problem (and solution) revolves aorund  _inc/mime/html.php_.  I notice: `'svg|svgz' => 'image/svg+xml',`  which is causing svg (and svgz) to appear in htaccess twice..one using html's expires/max-age and another (lower in the htaccess) for "Media & Other files" expires/max-age.  Seems one just has to strip out that line from the _html.php_ to fix the problem.  The same is true for rtf and rtx.

**Comment by nigrosimone** [comment]
yes... and i think the correct list is
```php
/**
 * HTML mime types
 */
return array(
    'html|htm' => 'text/html', 
    'txt' => 'text/plain', 
    'xsd' => 'text/xsd', 
    'xsl' => 'text/xsl', 
    'xml' => 'text/xml'
);
```

without rtf and svg.

**Comment by amiga-500** [comment]
✔️  -- looks good...you can do the honors with the PR.

**Comment by nigrosimone** [comment]
Fixed https://github.com/szepeviktor/w3-total-cache-fixed/pull/243

thanks @vijayaraghavanramanan !

**Comment by amiga-500** [comment]
2xthanks @vijayaraghavanramanan

**Comment by superpoincare** [comment]
One more thing; this fix works by replacing the files in the plugins folder and not by installing. How would the change appear? Suppose a user is using this and doesn't know this change has been made, then unless he/she updates something which affects the .htaccess, it won't update - correct?

**Comment by amiga-500** [comment]
The change will take affect (modifies the htaccess automatically) when logging into the admin page and navigating to any of the w3tc sidebar menus (e.g.  _"Performance"_).

**Comment by nigrosimone** [comment]
if **Verify rewrite rules** is checked in the general settings section

**Comment by amiga-500** [comment]
> _if Verify rewrite rules is checked in the general settings section_

The good thing is by default it is checked on. 😀

**Comment by elr0berto** [comment]
i seem to still have this issue somehow, this is from my nginx.conf generated by w3t

svg and html seem to have the same expires and maxe-age 90000s. ... 

 location ~ \.(html|htm|rtf|rtx|svg|svgz|txt|xsd|xsl|xml)$ {  
    expires 90000s;  
    add_header Pragma "public";  
    add_header Cache-Control "max-age=90000, public";  
    add_header X-Powered-By "W3 Total Cache/0.9.4.1";  
}
