### ISSUE TITLE
CSS Tidy minifier not work

### ISSUE THREAD

**Issue by nigrosimone** [szepeviktor/fix-w3tc#249]
just for fun i have switch the minifier from "Default" to "CSS Tidy" and the result is a total disaster.

the problem is "CSSTidy" version is really outdated and not support new css 3 rules.

the "Default" minifier works well. In my opinion we can remove "CSS Tidy" or update at new version, but the best is simple remove the choise.

**Comment by amiga-500** [comment]
A few weeks back i found an updated [version of CSSTidy](https://github.com/Cerdic/CSSTidy/tree/v1.5.5) and it seemed to work on a brief test.  Though i did not check it against css3 rules.  The intent was to replace the old CSSTidy with this new one if it fully worked.  

The new version has the same files names and can replace the same 4 files inside _lib/CSSTidy_.  Give it a try and see if it solves the css3 problem.

**Comment by amiga-500** [comment]
I also found a JSMin replacement since its very old and the author even admits it needs replacing.  I found [JShink](https://github.com/tedivm/JShrink) but i will have to do some code tweaking to get it to work with w3tc.

**Comment by nigrosimone** [comment]
Great! :D

**Comment by amiga-500** [comment]
I should be able to get the new CSSTidy  PR'ed later today.  I am just looking through the code and notice some new features in the latest that i am attaching to w3tc.

**Comment by nigrosimone** [comment]
And also htlm minifier is outdated and break new html5 code.

**Comment by amiga-500** [comment]
CSSTIdy is now updated to the latest :bowtie:  (PR #255) Hopefully it resolves the CSS3 issue.  It claims to fully support it.  

These are the default setting what fresh installers -- no existing config file exists -- will see. 

![csstidy-defaults](https://cloud.githubusercontent.com/assets/5191497/21726816/410f4448-d40c-11e6-8d33-57c88f81091a.png)

Now it's just: JSMin or HTML Tidy ... haven't decided which to tackle next.

**Comment by nigrosimone** [comment]
WOW!!! great work! any plans for update the other minifier (HTML, JS)? i have totally wasted my time today for integrate new [unit testing for advanced cache](https://github.com/szepeviktor/w3-total-cache-fixed/pull/254) :D at the end i have rage-closed the pr

**Comment by amiga-500** [comment]
Yup, will look into HTML and JS soon too. :blush:

**Comment by nigrosimone** [comment]
tested! really great work!

in my opinion, the better settings for the max speed during the css minification (and avoid too render blocking) are:

[![Immagine2.jpg](https://s24.postimg.org/osermuk05/Immagine2.jpg)](https://postimg.org/image/wxwtl088x/)

**Comment by amiga-500** [comment]
Curious @nigrosimone  , should i make your settings the defaults instead?  The original defaults were what w3tc had so i didnt modify them.  They aren't the most favorable for speed so i'm open to change them to be more like your settings.   I notice though from your settings the biggest difference in speed would be to change the _Compression_ from "_Standard_" to "_Highest_".  Should i just change the _Compression_ to _Highest_ and keep the remaining defaults?

Cheers
Kimberly :octocat:

**Comment by nigrosimone** [comment]
The worst setting for speed is "optimize shorthand" because it iterate on each css rule,  for this the better is "don't optimize". the others settings have a minimal impact but at the end my settings are good for minimize and speed. 

Side note: you also uncheck remove space before important.

**Comment by amiga-500** [comment]
Thanks.  Sounds good.  I will modify the defaults to reflect those.
