### ISSUE TITLE
[0.9.5.x] Compatibility check with wordpress 4.7

### ISSUE THREAD

**Issue by nigrosimone** [szepeviktor/fix-w3tc#261]
According to [WordPress 4.7 Master List](https://wordpress.org/support/topic/read-this-first-wordpress-4-7-master-list/#post-8521431), WordPress 4.7 and W3 Total cache – V0.9.5.1 are **NOT** compatible:

> W3 Total cache – Version 0.9.5.1 is incompatible with WordPress 4.7 and you may need to remove it to access your site (Removing the plugin directory is not enough, you also need to remove the db.php, advanced-cache.php and object-cache.php files manually from the wp-content/ directory).
> The other day, I contacted the developers – the next day I got back a short message saying that the plugin was functional and supported.

I have tested and it seems to works. But why WP Core says it's incompatible?

[![Immagine3.jpg](https://s30.postimg.org/4ue0onnxt/Immagine3.jpg)](https://postimg.org/image/hyjl1cfzh/)

any news?

**Comment by amiga-500** [comment]
I think its probably due to so many people being upset with lack of support in the forums with their specific issues so they mark the plugin as broken out of spite.

**Comment by nigrosimone** [comment]
ok for the users! but WordPress Core says V0.9.5.1 is not WP4.7 compatible

**Comment by amiga-500** [comment]
Ahhh...really?  Sorry, i misread your post.  Wow.  How strange.  I will do some extra digging around other places to see what i turn up.  Maybe i'll get lucky.

**Comment by amiga-500** [comment]
Did some roaming and i couldn't find any specific details given by anyone beyond a link back to the WP master list as to why its not compatible.  I emailed some of the WP folks but no reply yet.

**Comment by nolens** [comment]
Just look at the "update frequency" of the original plugin in the wp repository. The fact his release cycles became so slow and infrequent lately may indicate he just has other priorities than to update or even check compatibility with the latest wordpress version...

**Comment by amiga-500** [comment]
Got back this reply from the Master List moderator regarding v0.9.5.1:

> _We can't actually say exactly what the problem is, as we don't know the specifics our selves, what we do know is that this specific version of W3TC causes WSOD/HTTP 500 errors on a noticeable amount of systems after the 4.7 update._
>
> _It seems to be related to a config option, but we've been unable to track down the the specifics cause beyond the plugin and versions in question I'm sorry to say._
>
> _The reason it remains listed is because the plugin has shown no indication of looking into fixing the problem or troubleshooting them selves so there's obviously been no fixes on the official release to address the issue._

**Comment by charlesLF** [comment]
I'm wondering if this could be related to something with the object cache not being cleared properly during upgrades to WP 4.7

See this: https://core.trac.wordpress.org/ticket/39135
And this for the underlying cause (with the `$wp_db_version` variable): https://neutrondev.com/fix-wordpress-admin-panel-inaccessible-wp-upgrade/

Edit: It may very much be (props to @nigrosimone for starting that discussion): https://core.trac.wordpress.org/ticket/36455

**Comment by nigrosimone** [comment]
> Edit: It may very much be (props to @nigrosimone for starting that discussion):

Funny facts:  in the same discussion at 2016-04-09 (more time before W3TC-FIX!) there is also @szepeviktor :D 

I have made a deep investigation and at the end i don't understand what happened at so many users.
So many users says that (after so many topics that i have read): 
1) during the upgrade from wp 4.x to wp 4.7.0 the website crash in the white screen of the dead.
2) only deleteting all w3tc entry (plugin and dropins like object-cache.php, advanced-cache.php and db.php), wp accomplish the upgrade.
3) after upgrade to wp 4.7.0 we can reinstall w3tc without issue.

the logic  will would the plugin is totally inoffensive during wp updating:

advanced-cache.php is ok at https://github.com/szepeviktor/w3-total-cache-fixed/blob/v0.9.5.x/wp-content/advanced-cache.php#L16

db.php maybe at https://github.com/szepeviktor/w3-total-cache-fixed/blob/v0.9.5.x/wp-content/db.php#L27

object-cache.php is without control https://github.com/szepeviktor/w3-total-cache-fixed/blob/v0.9.5.x/wp-content/object-cache.php

could be this the issue?

side note: very happy to see here @charlesLF ( it's been a long time since I saw you!)

**Comment by szepeviktor** [comment]
> object-cache.php is without control

It should be w/o control as transients live inside the object cache.

**Comment by szepeviktor** [comment]
@nigrosimone Did you have - for example - file based object caching turned on before the upgrade?

**Comment by nigrosimone** [comment]
@szepeviktor i have tried only with memory based object caching (apcu and memcache). Do you think the problem are "file based cache"? this has sense, common users are on cheap hosting without memory module and i think they enable the only allowed option: cache on disk.

**Comment by szepeviktor** [comment]
> Do you think the problem are "file based cache"?

No.

**Comment by nigrosimone** [comment]
> It should be w/o control as transients live inside the object cache.
 
ok, but a control is a better: 
```php
/**
 * Abort W3TC loading if WordPress is upgrading
 */
if ( defined( 'WP_INSTALLING' ) && WP_INSTALLING )
	return;
```

**Comment by szepeviktor** [comment]
The object cache should be accessible also during installation.

**Comment by nigrosimone** [comment]
other [plugin ](https://plugins.svn.wordpress.org/memcached/tags/3.0.1/object-cache.php) has curious strategy, during installation delete cache instead of set:

```php
function wp_cache_set($key, $data, $group = '', $expire = 0) {
	global $wp_object_cache;

	if ( defined('WP_INSTALLING') == false )
		return $wp_object_cache->set($key, $data, $group, $expire);
	else
		return $wp_object_cache->delete($key, $group);
}
```

**Comment by szepeviktor** [comment]
You may take wp-redis as the standard.
https://github.com/pantheon-systems/wp-redis/blob/master/object-cache.php

I am using it as it is superior quality.

**Comment by szepeviktor** [comment]
And a proper memcached implementation
https://github.com/tollmanz/wordpress-pecl-memcached-object-cache/blob/master/object-cache.php

**Comment by szepeviktor** [comment]
BTW When you look for WP plugins be very careful.
A plugin without extensive tests is to be avoided. There are the popular guys and the enterprise guys!

**Comment by nigrosimone** [comment]
wp-redis check if wp is installing

```php
/**
	 * Whether or not wakeup flush is enabled
	 *
	 * @return bool
	 */
	private function is_redis_failback_flush_enabled() {
		if ( defined( 'WP_INSTALLING' ) && WP_INSTALLING ) {
			return false;
		} else if ( defined( 'WP_REDIS_DISABLE_FAILBACK_FLUSH' ) && WP_REDIS_DISABLE_FAILBACK_FLUSH ) {
			return false;
		}
		return true;
	}
```

memcached nope.

mhh.

**Comment by szepeviktor** [comment]
> wp-redis check if wp is installing

It is for fallbacks only.

**Comment by nigrosimone** [comment]
I give up 😆

**Comment by charlesLF** [comment]
> side note: very happy to see here @charlesLF ( it's been a long time since I saw you!)

It's good to be back :smile:  ... I have been following closely @amiga-500 and your updates on this repo, but have been too busy with other work. But things have slowed down a bit now, so I can come back and contribute :)

I have tried several different update scenarios on a staging environment, but could not replicate the white screen problem.
I'm still not sure why that is happening :/

**Comment by szepeviktor** [comment]
Pls continue in a specific issue.
