### ISSUE TITLE
Removal of MaxCDN referrer from plugin

### ISSUE THREAD

**Issue by Tarun80** [szepeviktor/fix-w3tc#285]
Figured this might be something W3TC Fixed may want to remove. Seen in several places like General, CDN, etc. and figure this would apply for 0.9.4.x and 0.9.5.x

**Comment by amiga-500** [comment]
I assume you are referring to the "Affiliate Referral" links such as:

   ![general_settings_w3_total_cache_0ssd_wordpress_-_2017-01-15_00_52_28](https://cloud.githubusercontent.com/assets/5191497/21960510/0400d834-dabd-11e6-975a-ad46e0056b43.png)

If so then sure thing.  If it's something else just let me know.

**Comment by nigrosimone** [comment]
before each update on 0.9.5.x, please read https://github.com/szepeviktor/w3-total-cache-fixed/issues/196#issuecomment-272685689

**Comment by szepeviktor** [comment]
I think making less income for Frederick is not fixing w3tc.

**Comment by nigrosimone** [comment]
> I think making less income for Frederick is not fixing w3tc.

maybe... his core business is pay for support, but my core business is make fastest websites without bug. It will a epic battle!
