### ISSUE TITLE
Static function Minify_Inline::minify() should not be abstract

### ISSUE THREAD

**Issue by SirAndrii** [szepeviktor/fix-w3tc#290]
Have a lot of such error messages. Looked for empty strings in minify settings - all is ok.

>Error:  Static function Minify_Inline::minify() should not be abstract
Stack trace
…ww/admin/www/grimuar.ru/wp-content/plugins/w3-total-cache-fixed/inc/
define.php (1504)
…ww/grimuar.ru/wp-content/plugins/w3-total-cache-fixed/lib/W3/Plugin/
Minify.php (552)
…ww/grimuar.ru/wp-content/plugins/w3-total-cache-fixed/lib/W3/Plugin/
Minify.php (301)
in W3_Plugin_Minify::ob_callback called at ? (?)
…ww/grimuar.ru/wp-content/plugins/w3-total-cache-fixed/inc/functions/
plugin.php (23)
…rimuar.ru/wp-content/plugins/w3-total-cache-fixed/lib/W3/Plugin/
TotalCache.php (645)
in W3_Plugin_TotalCache::ob_callback called at ? (?)

**Comment by nigrosimone** [comment]
mhhh an abstract function will never be static, in any kind of language. This is a design pattern bug. Thanks for the report, will be fixed soon.

**Comment by amiga-500** [comment]
@regme07 i am trying to track down the specific error point in code but it doesnt seem to match your stack trace.  What version are you using?

I just noticed u opened a new issue and had updated to v0.9.4.6.1.  Is the problem still occurring?  If so, then can you give me the steps to duplicate it?

**Comment by SirAndrii** [comment]
It appears only when inline CSS minification is enabled:
> PHP Strict Standards:  Static function Minify_Inline::minify() should not be abstract in plugins/w3-total-cache-fixed/lib/Minify/Minify/Inline.php on line 8

**Comment by amiga-500** [comment]
Ahh yes i see the problem now. I forgot that because i am using PHP 7.x, abstract static functions are perfectly allowed to be used, _**however**_, in PHP 5.4-5.6 it is not permitted.  This problem will be taken care of today.  Thanks for the heads up @regme07!
