### ISSUE TITLE
PHP Notice Undefined index: HTTP_USER_AGENT

### ISSUE THREAD

**Issue by SirAndrii** [szepeviktor/fix-w3tc#291]
After update to 9.4.6.1 got such errors in debug.log:
> PHP Notice:  Undefined index: HTTP_USER_AGENT in /var/www/admin/www/grimuar.ru/wp-content/plugins/w3-total-cache-fixed/lib/W3/PgCache.php(1512) : eval()'d code on line 1

**Comment by nigrosimone** [comment]
this isn't a w3tc error. This issue is caused by a plugin or theme that use fragment cache. Fragment cache is a w3tc features that allow third party software (plugin or theme) to override cache layer and excute some code. In your case, is the code passed through the fragment that cause the error.

**Comment by amiga-500** [comment]
@regme07 yup, it sounds like your fragment cache implementation is incorrect.  There are several styles you can use but a common one would be something like:

```html
<!-- mfunc YOUR_FRAG_ID_HERE -->echo $_SERVER['HTTP_USER_AGENT'];<!-- /mfunc YOUR_FRAG_ID_HERE -->
```

**Comment by SirAndrii** [comment]
Thanks fo fast reply! fixed it with your help. 

Find another notice:  

> Notice: is_comments_popup is deprecated since version 4.5.0 with no alternative available ...

function is_comments_popup calls in plugins/w3-total-cache-fixed/lib/W3/Plugin/Minify.php:                

> case (is_comments_popup() && ($template_file = get_comments_popup_template())):

**Comment by amiga-500** [comment]
Thanks for the heads up @regme07 ... i've taken care of the deprecation in #295 now
