### ISSUE TITLE
Review changes

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/fix-w3tc#292]
The Azure lib change is in a separate commit to make it easier to review the rest
https://github.com/szepeviktor/w3-total-cache-fixed/commits/orig

**Comment by szepeviktor** [comment]
The *rest* https://github.com/szepeviktor/w3-total-cache-fixed/commit/3143f556c8ddec20c108616ef32271f2b3f572bb#diff-eb6b6c90251ab33cee784713c451e6d8R770

**Comment by szepeviktor** [comment]
Is someone up to comparing our 0.9.4.x changes to this commit?
How should we complete this and future upstream releases?

**Comment by nigrosimone** [comment]
> How should we complete this and future upstream releases?

i think the better way is move the project on 0.9.5.x and re-implement on it, each 0.9.4.x's feature we have added over the official version.

**Comment by nigrosimone** [comment]
It seems implemented all our fixes.

**Comment by szepeviktor** [comment]
Are we talking about all of your commits?
https://github.com/szepeviktor/w3-total-cache-fixed/compare/d3bcbe069ba408f5bba349aa6cbf73f3582fe961...v0.9.4.x

**Comment by nigrosimone** [comment]
> Are we talking about all of your commits?

on the 0.9.5.x branch! not all, but many of...

**Comment by szepeviktor** [comment]
I thought the v0.9.5.x branch hasn't reached all the features of v0.9.4.x
Am I wrong?

**Comment by szepeviktor** [comment]
These are all the changes in v0.9.5.x
https://github.com/szepeviktor/w3-total-cache-fixed/compare/2b66f897aec1e643144d6dd49f2c1cc49280d5c9...v0.9.5.x

**Comment by nigrosimone** [comment]
> Am I wrong?

you are right!

**Comment by charlesLF** [comment]
Here's some of the files that contain changes from our `0.9.5.x` branch that are not present in the `orig` branch, and the issue number that they're related to:

-  `Minify_MinifiedFileRequestHandler.php`, function `_get_cache()`, commit 1f7de28
- `/inc/mime/html.php`, commit 36ce86c, make sure #242 is still working
- `Util_Environment.php`, commit 14b21da, make sure #270  is still fixed
- `Cdn_Core.php`, commit 2f33f27, make sure #176 is still fixed with 0.9.5.2 (they used a different approach, I think)
- `Generic_Plugin_PageCachePurge.php` and related files from ca88dd0, these are our own files, added upon request in #146 
- `UsageStatistics_ConfigLabels.php` (and related): original w3tc file, deleted in 0.9.5.2
- `Generic_Plugin_WidgetServices.php` (and related): original w3tc file, deleted in 0.9.5.2
- `/lib/EDD/` : deleted in 0.9.5.2

**Comment by nigrosimone** [comment]
@charlesLF from my mails with official support, there are the answer at my request to implement our fixes:

> https://github.com/szepeviktor/w3-total-cache-fixed/pull/147
> paritally fixed already, remaining accepted
> 
> https://github.com/szepeviktor/w3-total-cache-fixed/pull/151
> calls optimization makes sense, accepted
> 
> https://github.com/szepeviktor/w3-total-cache-fixed/pull/218
> accepted
> 
> https://github.com/szepeviktor/w3-total-cache-fixed/pull/232
> paritally fixed already, but good job from your side, thank you
> 
> https://github.com/szepeviktor/w3-total-cache-fixed/pull/268
> fixed already
> 
> https://github.com/szepeviktor/w3-total-cache-fixed/pull/270
> thanks for win-incompatibility tip, applied more correct fix
>                 if ( DIRECTORY_SEPARATOR != '/' )
>                         $uri_from_wp_content = str_replace( DIRECTORY_SEPARATOR, '/',
>                                 $uri_from_wp_content );
> 
> https://github.com/szepeviktor/w3-total-cache-fixed/pull/272
> svgz - accepted
> svg - not accepted since .svg files have regular xml syntax on correctly configured web servers/valid files
> 
> minify library fix accepted
> 
> https://github.com/szepeviktor/w3-total-cache-fixed/pull/273
> accepted
> 
> https://github.com/szepeviktor/w3-total-cache-fixed/pull/276
> thanks for dbcluster and mssql update.
> remaining php7 is not so interesting there since those are false positives from validator, but applied since you did it and there are no cons about those
> 
> https://github.com/szepeviktor/w3-total-cache-fixed/pull/277
> duplicate method, removed entirely (actually you've fixed that win-compatibility problem in Util_Enbvironment already)
> 
> https://github.com/szepeviktor/w3-total-cache-fixed/pull/176
> incorrect workaround fix causing redundant auth calls on each construction.
> valid one has been applied already
> 
> https://github.com/szepeviktor/w3-total-cache-fixed/pull/188
> oh.. thank you
> 
> https://github.com/szepeviktor/w3-total-cache-fixed/pull/269
> js should be blocked instead to not issue ajax call at all, another fix applied
> 
> https://github.com/szepeviktor/w3-total-cache-fixed/pull/263
> accepted
> 
> https://github.com/szepeviktor/w3-total-cache-fixed/pull/233
> makes less maintainable code in a longer term, e.g. you may notice how hierarchy of if's mess is starting to grow even in initial commit.
> no real performance difference.
> cons without pros, not accepted
> 
> if you want to make code shorter - common $config values may be moved to top with further array_merges later.
> 
> https://github.com/szepeviktor/w3-total-cache-fixed/commits/v0.9.5.x
> passed through, most were fixed already. applied
> https://github.com/szepeviktor/w3-total-cache-fixed/commit/c0e9e7faa0c09947c29378db44ad232f0d2563f7
> https://github.com/szepeviktor/w3-total-cache-fixed/commit/aa8979f27eed56e0795a622ba809f31c8351dcc9
> 
> https://github.com/szepeviktor/w3-total-cache-fixed/pull/289
> Yeah, thanks for detailed info. Fix confirmed as a workaround.

**Comment by charlesLF** [comment]
Thanks for the details, @nigrosimone 
In regards to my previous points:

> -  `Minify_MinifiedFileRequestHandler.php`, function `_get_cache()`, commit 1f7de28

This was rejected:
> no real performance difference.
> cons without pros, not accepted

We could ignore this commit when we merge, if everyone here agrees.

> - `/inc/mime/html.php`, commit 36ce86c, make sure #242 is still working

svg was kept. Explanation seems reasonable. We should accept the official fix, if our tests pass correctly (that is, if we confirm that #242 is still fixed)

> - `Util_Environment.php`, commit 14b21da, make sure #270  is still fixed

Official fix should be accepted. More robust.

> - `Cdn_Core.php`, commit 2f33f27, make sure #176 is still fixed with 0.9.5.2 (they used a different approach, I think)

Official fix should be accepted.

> - `Generic_Plugin_PageCachePurge.php` and related files from ca88dd0, these are our own files, added upon request in #146 

This is a good feature that we added, currently still not present on the official branch. We should keep this commit.

>- `UsageStatistics_ConfigLabels.php` (and related): original w3tc file, deleted in 0.9.5.2
> - `Generic_Plugin_WidgetServices.php` (and related): original w3tc file, deleted in 0.9.5.2
> - `/lib/EDD/` : deleted in 0.9.5.2

These are changes that were done solely by the w3tc guys, so we should accept those changes to our branch.

So, #146 (commit 277c42ec1f4dcc98d418534fc14a60674b0968cd) is the only real difference that I can see as of now.

**Comment by szepeviktor** [comment]
Thank you.
Let's continue in #303
