### ISSUE TITLE
Applying our fixes to upstream release v0.9.5.2

### ISSUE THREAD

**Issue by nigrosimone** [szepeviktor/fix-w3tc#293]
From [the changelog](https://wordpress.org/plugins/w3-total-cache/changelog/):

- Fixed security issue by protecting configuration data by adding .php to relevant files
- Fixed security issue with the creation of dot folders that could be abused
- Fixed handling HTTP compression for uncached pages
- Fixed handling of .svgz files
- Added expiration headers to webP images
- Added support for Microsoft Azure’s latest API
- Added ability to cache WP Admin. Recommended setting, is off. (Improved WP Admin performance with object caching enabled)
- Added HTTP/2 Push support for minified files
- Added option management support for wp-cli
- Improved handling of uncompressed minified files
- Improved handling of purging of modified pages / posts
- Improved compatibility with Rackspace Cloud Files
- Improved initial CDN configuration reliability
- Improved reliability of object caching
- Improved PHP 7.0 compatibility
- Improved PHP 4.3 compatibility
- Improved HTTP/2 support
- Improved CSS embed handling
- Improved reliability of object cache, transients now fallback to database
- Improved handling of cached http compressed objects

**Comment by szepeviktor** [comment]
I think our v0.9.5.x branch does not work, it is broken.
What should be the default branch now?
@amiga-500 Please advise.

**Comment by superpoincare** [comment]
How does http2 push work. It says doesn't work for disk enhanced. With which option does it work? With disk:basic?

**Comment by nigrosimone** [comment]
Yes or other caching modules (redis, apcu... )

**Comment by nigrosimone** [comment]
@szepeviktor i think the better idea is sync your v0.9.5.x with the upstream.

**Comment by szepeviktor** [comment]
OK.
Could you apply these with descriptive commit messages?
https://github.com/szepeviktor/w3-total-cache-fixed/issues/292#issuecomment-273320540

**Comment by nigrosimone** [comment]
@szepeviktor too much work! :D it's really important?

**Comment by szepeviktor** [comment]
Anyone up to open 5 PR-s?

**Comment by szepeviktor** [comment]
Continued in #298
