### ISSUE TITLE
How to add tests to an upstream release

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/fix-w3tc#294]
It would be nice to have a Wiki page on how to add tests to **an upstream release.**

- Just
- a short
- list
- of files

https://github.com/szepeviktor/w3-total-cache-fixed/wiki/How-to-add-tests%3F

**Comment by szepeviktor** [comment]
@nigrosimone Please let me know in the Wiki what are the files to copy.

**Comment by nigrosimone** [comment]
if you want add new unit test, just add a php file prefixed by `test-` (eg, `test-foo.php`) files in the `/tests` folder in according with [phpunit.xml.dist](https://github.com/szepeviktor/w3-total-cache-fixed/blob/v0.9.4.x/phpunit.xml.dist).

the `test-foo.php` must include the plugin file `w3-total-cache-fixed.php` and a class (eg. W3_Foo_Test) that extends WP_UnitTestCase, eg:

```php
<?php
require_once dirname(dirname(__FILE__)) . '/w3-total-cache-fixed.php';
class W3_Foo_Test extends WP_UnitTestCase {
```

in the `W3_Foo_Test ` users can insert the test method prefixed by `test_` eg.:
```php
public function test_sum(){
    $this->assertTrue( (1+1) == 2 );
}
```

**side note: my englist is too bad for write a wiki**

**Comment by szepeviktor** [comment]
OK.
Is this list correct?

- .travis.yml
- phpunit.xml.dist
- tests/
- bin/

**Comment by szepeviktor** [comment]
Shouldn't we call phpunit.xml.dist phpunit.xml ?

**Comment by szepeviktor** [comment]
> if you want add new unit test

I am trying to document the *migratrion* of tests to 0.9.5.x

**Comment by nigrosimone** [comment]
just copy

.travis.yml
phpunit.xml.dist
tests/
bin/

**Comment by szepeviktor** [comment]
Thanks.
