### ISSUE TITLE
Accidentally overwritten our v0.9.5.x

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/fix-w3tc#297]
@nigrosimone Could you `git checkout v0.9.5.x; git push -f --set-upstream origin v0.9.5.x-defunct` your v0.9.5.x branch to v0.9.5.x-defunct?

**Comment by nigrosimone** [comment]
[![Immagine2.jpg](https://s28.postimg.org/aw45h2lbx/Immagine2.jpg)](https://postimg.org/image/x81yagkft/)

**Comment by szepeviktor** [comment]
Could you try `git pull origin v0.9.5.x-defunct` beforehand?

**Comment by nigrosimone** [comment]
[![Immagine3.jpg](https://s27.postimg.org/d2emn9reb/Immagine3.jpg)](https://postimg.org/image/5z6r7nlyn/)

**Comment by szepeviktor** [comment]
Then try renaming the local branch `git branch -m v0.9.5.x v0.9.5.x-defunct`
But then do not check out.

**Comment by nigrosimone** [comment]
ok... now?
[![Immagine4.jpg](https://s30.postimg.org/nept19yap/Immagine4.jpg)](https://postimg.org/image/ig2amquhp/)

**Comment by szepeviktor** [comment]
git push now without checking out!

**Comment by szepeviktor** [comment]
If you succeed we will see those commits https://github.com/szepeviktor/w3-total-cache-fixed/commits/v0.9.5.x-defunct

**Comment by nigrosimone** [comment]
[![Immagine5.jpg](https://s24.postimg.org/8vp36fmhx/Immagine5.jpg)](https://postimg.org/image/s0scg715t/)

**Comment by szepeviktor** [comment]
You have to force it.
`git push -f --set-upstream origin v0.9.5.x-defunct`

**Comment by nigrosimone** [comment]
[![Immagine6.jpg](https://s29.postimg.org/772xk5r9z/Immagine6.jpg)](https://postimg.org/image/52ikj2pn7/)

**Comment by szepeviktor** [comment]
I think your v0.9.5.x got overwritten too.
Maybe @amiga-500 has our commits.

**Comment by amiga-500** [comment]
Hey guys!   From what i can see yea i think i still have our commits (see below).   I will push the commits now.

Kimberly :octocat: 

![clipboard01](https://cloud.githubusercontent.com/assets/5191497/22095468/d8b9241e-dde2-11e6-9da2-51fd9dfeecda.png)

**Comment by szepeviktor** [comment]
Thank you. 


-- 
+36204242498
Ezen a készüléken sok az elütés. 
Elnézést!
