### ISSUE TITLE
Rebranding howto

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/fix-w3tc#298]
First. Should we rebrand?

**Comment by szepeviktor** [comment]
There are 37 `w3-total-cache-fixed` in branch v0.9.4.x
https://github.com/szepeviktor/w3-total-cache-fixed/search?utf8=%E2%9C%93&q=w3-total-cache-fixed
(I've used `grep -ri w3-total-cache-fixed *`)

And the updater
first commit: https://github.com/szepeviktor/w3-total-cache-fixed/commit/d7d0058ed1dc70d6359e66b48e1852c539c98c84#diff-f06c29539df14a79ba6e76aa03df9c6c

**Comment by nigrosimone** [comment]
> First. Should we rebrand?

nooo... in my idea v0.9.4.x is a our version (rebrandend). v0.9.5.x is official (fixed) version always synced with the upstream

**Comment by szepeviktor** [comment]
So no fixes for v0.9.5.x?

**Comment by nigrosimone** [comment]
all fixes in the v0.9.5.x are implemented in the official see https://github.com/szepeviktor/w3-total-cache-fixed/issues/292#issuecomment-273583862.

we can restart to work on the official version.

**Comment by szepeviktor** [comment]
So @charlesLF is wrong?
https://github.com/szepeviktor/w3-total-cache-fixed/issues/292#issuecomment-273320540

**Comment by charlesLF** [comment]
@nigrosimone's [reply](https://github.com/szepeviktor/w3-total-cache-fixed/issues/292#issuecomment-273583862) clears it out.
Seems all issues were addressed, except for #146

**Comment by szepeviktor** [comment]
Thank you.

**Comment by nigrosimone** [comment]
> Seems all issues were addressed, except for #146

maybe, i have missed to report it to the official support...

**Comment by szepeviktor** [comment]
I think it is enough to provide a PR (any  code quality, a work-around goes also)
because they - I think - monitor our changes.

Maybe I am wrong.
