### ISSUE TITLE
Main branch?

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/fix-w3tc#305]
Should we leave v0.9.4.x as the main branch?

**Comment by szepeviktor** [comment]
Yes.

**Comment by amiga-500** [comment]
I figure after we get things moving along in v0.9.5.x now that its been updated to v0.9.5.2 i have no problem shifting it to be the main branch.  Assuming everyone else agrees as well.

**Comment by szepeviktor** [comment]
I think we should come up with some fixes before that.
There is only one for the time: https://github.com/szepeviktor/w3-total-cache-fixed/commits/v0.9.5.x

**Comment by nigrosimone** [comment]
> I think we should come up with some fixes before that.

yep
