### ISSUE TITLE
Readd our files and readme

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/fix-w3tc#306]
See https://github.com/szepeviktor/w3-total-cache-fixed/wiki/How-to-add-our-files-to-an-upstream-release

**Comment by szepeviktor** [comment]
See also https://github.com/szepeviktor/w3-total-cache-fixed/wiki/How-to-add-our-files-to-an-upstream-release

**Comment by szepeviktor** [comment]
If someone adds our files back I'll set v0.9.5.x as the default branch.
Readme may need rephrasing.

**Comment by nigrosimone** [comment]
Ok... i close this issue.

**Comment by szepeviktor** [comment]
So we won't switch to 0.9.5.x?

**Comment by amiga-500** [comment]
Whenever you guys want to switch to 0.9.5.x i'm cool with it.

**Comment by szepeviktor** [comment]
How about right now?

**Comment by szepeviktor** [comment]
Please consider adding these files https://github.com/szepeviktor/w3-total-cache-fixed/wiki/How-to-add-our-files-to-an-upstream-release
at least a small README.md.

Thank you.

**Comment by amiga-500** [comment]
I'd like to get nigrosimone feedback too first, in case he has something to add before a switch happens.

**Comment by szepeviktor** [comment]
@nigrosimone Hurry up!
It is too late already: https://github.com/szepeviktor/w3-total-cache-fixed

**Comment by szepeviktor** [comment]
Have you seen this?
![traffic-x](https://cloud.githubusercontent.com/assets/952007/22433160/b4678144-e717-11e6-8dc4-5dc8f40277a6.png)
