### ISSUE TITLE
Add changes in readme.txt not in the old changelog.txt

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/fix-w3tc#308]
Please use the right place to mention changes: `/readme.txt`

**Comment by amiga-500** [comment]
Thanks.  will do.  The _changelog.txt_ needs to carry the change details too because it's displayed on the WP plugin page's Changelog tab when the v0.9.4.x updater is triggered.

**Comment by szepeviktor** [comment]
> it's displayed on the WP plugin page's Changelog tab when the v0.9.4.x updater is triggered.

~~I am sorry to say that readme.txt is parsed and displayed.~~

**Comment by szepeviktor** [comment]
We use a non-WordPress method
https://github.com/szepeviktor/w3-total-cache-fixed/blob/bafb68efdbbc85d6aad6022adb52f4a8271fcf3d/w3-total-cache-fixed.php#L91
