### ISSUE TITLE
DB Cache not properly flushed

### ISSUE THREAD

**Issue by charlesLF** [szepeviktor/fix-w3tc#31]
Hello,

I have noticed that the database cache was not being properly flushed if the cache method is anything other than disk (I tested it with memcached and redis).

The problem is with how flush_cache() is defined in DbCache.php
flush_cache() calls the flush() command defined in the cache engine.
For a disk-based cache, this results in the following line being executed:
```php
        $flush_dir = $group ? $this->_cache_dir . DIRECTORY_SEPARATOR . $group . DIRECTORY_SEPARATOR : $this->_flush_dir;
```
since the flush() command was executed with no argument (ie: $group = ''), the $flush_dir defaults to the entire DB cache directory, which is properly deleted.

In memcached or redis, the flush() function actually increments the key_version for the different groups, but since the $group defaults to 0, the wrong key_version is being selected and incremented.

As a possible fix, we can change the flush_cache() function in DbCache.php to:
```php
    function flush_cache() {
        $this->_flush_cache_group('all');
        return true;
    }
```

This will then loop through the different groups and clear each one of them.
This change can be found in here: https://github.com/charlesLF/fix-w3tc/commit/b9e38ee080910024eccf2c38381e4c53c50985b0

What are your thoughts on this one?

**Comment by nigrosimone** [comment]
but all cache driver have  `function flush($group = '0')`

**Comment by nigrosimone** [comment]
This is related to #32

**Comment by charlesLF** [comment]
It is somehow related, but I believe the fixes can be approached differently.

For the DB cache case, the values of the `$group` variable are already known (all, options, comments, options_comments). These values are correctly being passed to the `get` & `set` functions, and the `key_version` is unique for each group.

For purging the cache, it is therefore sufficient to increment the `key_version` for each group.

In the ObjectCache case, the problem lies in the `$group` and its default values ( empty string, or '0').
Specifically, in `Base.php` the `$group` variable passed to `get_with_old`.

I believe #32 and #33 merit separate fixes.

**Comment by nigrosimone** [comment]
@charlesLF have you a pull request for fix this?
