### ISSUE TITLE
location before </head>

### ISSUE THREAD

**Issue by SirAndrii** [szepeviktor/fix-w3tc#315]
At JS minify settings are three including modes:
Before /head
after body
before /body

But if i choose first variant - link to JS file is placed after |head| and before meta. On a one site it is even before minfied css. 

Is thre way set strict location before |/head|?

**Comment by amiga-500** [comment]
W3TC has special comment tags that you can place in your template wherever you like.  By doing so it should insert the minified files at those spots.
```php
<!-- W3TC-include-js-head -->
<!-- W3TC-include-js-body-start -->
<!-- W3TC-include-js-body-end -->
<!-- W3TC-include-css -->
```
In your case you'd use: `<!-- W3TC-include-js-head -->`
