### ISSUE TITLE
Object Cache not properly flushed

### ISSUE THREAD

**Issue by charlesLF** [szepeviktor/fix-w3tc#32]
This is somehow related to https://github.com/szepeviktor/fix-w3tc/issues/31

The symptoms are the same, and the culprit is in how `flush()` increments the `key_version`.

I found the following threads describing the same issue:

- https://wordpress.org/support/topic/self-diagnosed-and-fixed-w3-total-cache-bug-in-faulty-object-caching
- https://wordpress.org/support/topic/suggested-changes-to-object-caching-and-transients
- https://wordpress.org/support/topic/bug-in-apc-object-cache-wp_cache_set-making-it-fail

I see two possible ways for fixing this behavior:

1. pass the right `$group` value from `ObjectCache.php`, and then figure out a way to increment the key_version for each `$group` when the `flush()` function is called
2. Change the default `$group` value in the Cache folder from `$group = '0'` to `$group = ''` . Then all cache groups will be checking the `key_version` against the same key (i.e.: all `$groups` will be flushed at the same time and there would be no way for flushing just a single group, a functionality that doesn't seem to be implemented anyway)

The 2nd option seems the easiest way to go, as it appears that object cache groups are currently poorly implemented in W3TC. This was also the fix that Frederick Townes suggested in one of the above threads.

Thoughts?

**Comment by nigrosimone** [comment]
what about cache base? implement `set()` and `get()` with default group on `''`

https://github.com/szepeviktor/fix-w3tc/blob/master/lib/W3/Cache/Base.php#L80

```php
/**
     * Sets data
     *
     * @abstract
     * @param string $key
     * @param mixed $data
     * @param integer $expire
     * @param string $group Used to differentiate between groups of cache values
     * @return boolean
     */
    function set($key, $data, $expire = 0, $group = '') {
        return false;
    }
    /**
     * Returns data
     *
     * @param string $key
     * @param string $group Used to differentiate between groups of cache values
     * @return mixed
     */
    function get($key, $group = '') {
        list($data, $has_old) = $this->get_with_old($key, $group);
        return $data;
    }
```

**Comment by nigrosimone** [comment]
[Frederick Townes](https://wordpress.org/support/topic/suggested-changes-to-object-caching-and-transients?replies=9#post-5513870):
> wp_cache_set($id, $data, $group = 'default', $expire = 0) doesn't call w3-total-cache/lib/W3/Cache/Apc.php but lib/ObjectCache.php has no problems with parameters there, but $group = '0' should be replaced with $group = '' in all /Cache/* files to avoid problems with Object cache. that will be fixed in next release.

in https://github.com/szepeviktor/fix-w3tc/blob/master/lib/W3/ObjectCache.php all `$group` pararmeter have default value 'default'

**Comment by charlesLF** [comment]
Here's a rundown of what I believe is happening:

* For a Get call *
- The function `get()` is called in ObjectCache.php
- On line 167, ` $v = $cache->get($key);` is called. Notice that the `$group` variable is not passed
- This takes us to Base.php, which in turn calls `$this->get_with_old($key, $group)` . The `$group` variable here is the function's default value `$group = ''`

* For a Flush call *
- The function `flush()` is called in ObjectCache.php
- This calls `flush()` in the object cache engine (for example, Memcached.php)
- The default `$group` value is '0'
- The `flush` function will increment the `key_version` for group 0, which is not the group that the get functions use

The solution to change all `$group = '0'` to `$group = ''` seems to be the simplest fix.

**Comment by nigrosimone** [comment]
i think we need a @amiga-500's opinion

**Comment by nigrosimone** [comment]
@charlesLF have you a pull request for fix this?
