### ISSUE TITLE
Cloudfront Error 

### ISSUE THREAD

**Issue by nolens** [szepeviktor/fix-w3tc#325]
Hello, 

when testing cloudfront distribution from CDN tab or trying to purge cloudfront files, I receive the following error: 

> Error: Distribution for origin "removed_my_domain.net" not found.

I am using latest version of 0.9.4.x branch. 

Regards
Thomas

**Comment by amiga-500** [comment]
Hi @nolens ... 

1. Are you using Amazon Cloudfront (Origin Pull) or Amazon Cloudfront (Origin Push) ?
2. If its the Origin Push does this error occur when you click the "_Test S3 upload & CloudFront distribution" button_" or does it only happen via the _Purge_ button

Thanks

**Comment by amiga-500** [comment]
Hi Tom @nolens ... i just did an update to the Amazon Cloudfront files.  For your convenience here are those updated files that you can download directly here:

[inc/options/cdn/cf.php](https://raw.githubusercontent.com/szepeviktor/w3-total-cache-fixed/v0.9.4.x/inc/options/cdn/cf.php)
[inc/options/cdn/s3.php](https://raw.githubusercontent.com/szepeviktor/w3-total-cache-fixed/v0.9.4.x/inc/options/cdn/s3.php)
[lib/S3.php](https://raw.githubusercontent.com/szepeviktor/w3-total-cache-fixed/v0.9.4.x/lib/S3.php)
[lib/W3/Cdn/S3.php](https://raw.githubusercontent.com/szepeviktor/w3-total-cache-fixed/v0.9.4.x/lib/W3/Cdn/S3.php)
[lib/W3/Cdn/S3/Cf.php](https://raw.githubusercontent.com/szepeviktor/w3-total-cache-fixed/v0.9.4.x/lib/W3/Cdn/S3/Cf.php)
[pub/css/options.css](https://raw.githubusercontent.com/szepeviktor/w3-total-cache-fixed/v0.9.4.x/pub/css/options.css)
[pub/js/options.js](https://raw.githubusercontent.com/szepeviktor/w3-total-cache-fixed/v0.9.4.x/pub/js/options.js)

Give them a try and see if it solves your problem.  And let me know how it goes.

Thanks
Kimberly :octocat:

**Comment by nolens** [comment]
Hello Kimberly @amiga-500 ,

I have downloaded the whole distribution (not the individual files that you have linked above), activated it on a (different) staging server - and the issues I described above are gone now. 

Thank you for this quick reaction, great.
