### ISSUE TITLE
CloudFlare extension raise exception on save settings

### ISSUE THREAD

**Issue by nigrosimone** [szepeviktor/fix-w3tc#326]
When i change CloudFlare settings in the extension page, after click on "Save all settings", w3tc show an error:
[![Immagine.jpg](https://s28.postimg.org/u3azglvrh/Immagine.jpg)](https://postimg.org/image/nplwdcqvd/)

but SSL is on OFF on w3tc

[![Immagine2.jpg](https://s29.postimg.org/6vhdubd13/Immagine2.jpg)](https://postimg.org/image/o8ro968c3/)

and is off on CloudFlare 

[![Immagine3.jpg](https://s30.postimg.org/uff7xaphd/Immagine3.jpg)](https://postimg.org/image/7dymrjptp/)

**Step to reproduce:**

1) activate a free plan on CloudFlare https://www.cloudflare.com/plans/ and add a website.
2) activate w3tc CloudFlare extension and set up the mail and the api key.
3) play with the settings in the CloudFlare extension page and click on "Save all settings"

**My Environment**

- WP 4.7.1
- W3TC 0.9.5.2 (wp.org version)
- PHP 5.6.29
- Apache

this blog is just for test and is hosted on free platform https://en.altervista.org/ if you want try in the same environment, you can create an account.

**Comment by amiga-500** [comment]
Hi @nigrosimone ... just checked it now and yup it's a bug.  Thanks for explanation.  It helped.  Here is the fix at #334 .

**Comment by nigrosimone** [comment]
Always Thanks!
