### ISSUE TITLE
Use wp_prepare_attachment_for_js hook to rewrite image URLs when CDN is enabled

### ISSUE THREAD

**Issue by andreslucero** [szepeviktor/fix-w3tc#330]
On [the official support forum](https://wordpress.org/support/topic/w3tc-plugin-not-integrating-with-cdn-to-serve-certain-static-image-files/#post-8704172), one user reported that images loaded via JavaScript generated by the Beaver Builder plugin do not get pulled from CDN.

According to the plugin authors, they're using `wp_prepare_attachment_for_js()` prior to generating JS files containing image URLs. Many slideshow plugins appear to use this function to load images dynamically, so this issue affects more than just Beaver Builder users.

I suggest [applying a filter on `wp_prepare_attachment_for_js()`](https://developer.wordpress.org/reference/hooks/wp_prepare_attachment_for_js/) that rewrites image URLs to use the CDN when that setting is enabled. Some things to consider:

* The filter would have to take into account the Custom File List and other rules regarding files/paths that are allowed to be rewritten
* The filter would have to run prior to concatenation/minification of JS files, so that the filtered JS is included in the minified output

I'm probably missing something, but welcome your thoughts and feedback on this.

**Comment by amiga-500** [comment]
Yea that sounds like the right plan for sure.

Right now i'm distracted assisting someone else with what appears to be a very ancient bug in w3tc (re: posts/pages set into drafts/pending review) so i am just hunting it down and fixing it.

Kimberly :octocat:

**Comment by amiga-500** [comment]
Done ... #336
