### ISSUE TITLE
Travis Error

### ISSUE THREAD

**Issue by amiga-500** [szepeviktor/fix-w3tc#333]
Hi @nigrosimone what does this error mean and how does one fix it: https://travis-ci.org/szepeviktor/w3-total-cache-fixed/jobs/196359102

![job_692_19_-_szepeviktor_w3-total-cache-fixed_-_travis_ci_-_2017-01-29_11_19_59](https://cloud.githubusercontent.com/assets/5191497/22405713/e46ec752-e614-11e6-9b98-e96b7bcb66e0.png)

Thanks
Kimberly :octocat:

**Comment by nigrosimone** [comment]
I don't know.... :(

**Comment by szepeviktor** [comment]
> Declaration of SebastianBergmann\Comparator\DOMNodeComparator::assertEquals($expected, $actual, $delta = 0, $canonicalize = false, $ignoreCase = false) must be compatible with SebastianBergmann\Comparator\ObjectComparator::assertEquals($expected, $actual, $delta = 0, $canonicalize = false, $ignoreCase = false, array &$processed = Array) in phar:///home/travis/.phpenv/versions/master/bin/phpunit/sebastian-comparator/DOMNodeComparator.php on line 0

The difference inside phpunit:

- assertEquals($expected, $actual, $delta = 0, $canonicalize = false, $ignoreCase = false)
- assertEquals($expected, $actual, $delta = 0, $canonicalize = false, $ignoreCase = false, array &$processed = Array)

**Comment by szepeviktor** [comment]
See https://github.com/sebastianbergmann/phpunit/issues/2453
and fixed it https://github.com/sebastianbergmann/comparator/pull/30

**Comment by szepeviktor** [comment]
I've restarted https://travis-ci.org/szepeviktor/w3-total-cache-fixed/builds/196545986
