### ISSUE TITLE
Use CDN links for Media Library within wp-admin

### ISSUE THREAD

**Issue by nicbarker** [szepeviktor/fix-w3tc#340]
Hi,
First up, great work fixing some of the issues with w3 total cache.

I've done some digging and there doesn't seem to be any way to preferentially use CDN links when viewing the "Media Library" page within the admin (/wp-admin/upload.php)

We only have a single copy of our uploads on s3, not on the wordpress server. The images work fine for logged out users on the main public site, but all the /uploads links are broken within the admin interface (referring to local rather than CDN links)

I can understand disabling caching generally on admin pages, but the site I'm managing has quite a large media library (around 100 gigs or so) and so it's not feasible to store a copy of all the uploads on the same server as WP. I'm wondering if there is something I've missed, or if I should implement this functionality myself as a PR.

**Comment by amiga-500** [comment]
Hmmmm i think you make a good point.  I don't think there is presently a way to do what you are asking.  I could be wrong.  I'd have to think about it s'more.  If you'd like you can proceed with implementing the functionality.  It'll give me more time to snoop around.

Regards
Kimberly :octocat:

**Comment by nicbarker** [comment]
Hi Kimberly, thanks for the super prompt reply.
It's possible that I've mistaken the initial intention of W3 - I started using it originally _explicitly_ to offload the /uploads directory to s3. It didn't occur to me that the blanket approach of "no caching within the admin page" would make the admin page unusable.
I'll take a look around and see what I can do - I'll have to familiarise myself with the codebase a bit first.

Please let me know if this functionality seems out of scope for W3, I'm sure I can figure out some other way of doing it (even if it's hacky)

**Comment by amiga-500** [comment]
Hi Nic!

Yea, from first thought there should be a clean way to do it.  Recently i wrote up a new w3tc feature to fix an issue for slideshow plugins that use the _wp_prepare_attachment_for_js()_ function by rewriting local urls (in attachments) to CDN.  It would compare the local file against the accepted CDN files list (since w3tc has several filters) before doing the rewrite.  I figure your implementation would do something similar but the tricky part would where to put it.  You mentioned the Media Library.  I figure WP must have a filter that might help for that.  When i'm free i could give you a hand.  Right now i am just finishing up a security headers section for w3tc.  It might take me another day.

Cheers
Kimberly :octocat:

**Comment by nicbarker** [comment]
Great, thanks a lot. No worries about the time.
You're probably right about the filter, from some initial digging it seems that the stuff in the admin media library could be hooked using `add_filter('posts_orderby', foo);` - I've seen a number of other plugins using this filter hook.

**Comment by amiga-500** [comment]
Ahh that's interesting.  Thanks for the info.

Hey btw, i found this:

> _In order to change the default media upload location, you need to edit the **wp-config.php** file located in the root directory of your WordPress installation. If you want upload directory to be wp-content/files then you will need to place the following code in wp-config.php_
>
> _`define( 'UPLOADS', 'wp-content/'.'files' );`_

Curious, does this work if you modified it to your CDN url instead?  I havent looked in the wp code to see if it allows it or if it is only for local.

**Comment by nicbarker** [comment]
I'll check and get back to you.

**Comment by nicbarker** [comment]
I think that variable is relative path, check line 1953 of `wp-includes/functions.php`:

```php
if ( defined( 'UPLOADS' ) && ! ( is_multisite() && get_site_option( 'ms_files_rewriting' ) ) ) {
	$dir = ABSPATH . UPLOADS;
```

**Comment by amiga-500** [comment]
Ahhh....ok.

**Comment by nicbarker** [comment]
Ok here's the first problem, CDN is explicitly disabled on admin pages by W3. This could potentially be turned into a setting rather than just hard coded:

https://github.com/szepeviktor/w3-total-cache-fixed/blob/v0.9.5.x/Cdn_Plugin.php#L505-L509

**Comment by nicbarker** [comment]
Here's a quick, hacky fix to give you an idea of what I'm trying to do:
```php
function convert_attachment_url_to_cdn($url) {
	$common = Dispatcher::component( 'Cdn_Core' );
	$cdn = $common->get_cdn();
	$remote_path = $common->uri_to_cdn_uri( parse_url($url)['path'] );
	$new_url = $cdn->format_url( $remote_path );
	return $new_url;
}

if (is_admin()) {
	add_filter('wp_get_attachment_url', array($this, 'convert_attachment_url_to_cdn'));			
}
```

This was placed in `CDN_Plugin.php`. What remains to be done is make sure that these will only be changed when the CDN is actually active, providing a toggle on and off for the option and deciding if `CDN_Plugin.php` is the right place for this code.

**Comment by amiga-500** [comment]
Hi @nicbarker ... sorry for the delay ... 

It seems you came up with the same solution as i did in #336, as well as using _CDN_Plugin.php_, :rofl: -- mine was related to fixing a flaw for slideshow plugins that use `wp_prepare_attachment_for_js()` to get attachment urls for javascript...i had to convert their local urls to CDN url.

That being said, on closer inspection it seems the `wp_prepare_attachment_for_js()` function uses the `wp_get_attachment_url` filter (which is what you used) and the `attachment_link` filter.  So, fortunately for both of us i could just kill two birds with one stone if i just rewrote my original 336 to filter those two instead (with priority = 0 still, so it executes very early in the chain).  It would take care of your problem and the slideshow plugins problem in one shot :bowtie: 

In 336 i also run a check to verify that the url to convert is indeed part of the CDN allowed list.  W3TC has a _Custom Files List_, among other filters before a url is confirmed as being a legit CDN-bound entry.  If it's not in the list my function returns the url unchanged.

Btw, your choosing _CDN_Plugin.php_ was a correct one.  It only gets triggered if the CDN option is enabled (via General Settings).

I've written up the revised version.  Haven't commit it yet.  The only thing left for me is to add a checkbox under the CDN tab indicating if the Media Library is to use CDN links instead.

Would these words be explanatory enough?

![content_delivery_network_w3_total_cache_0ssd_wordpress_-_2017-02-02_10_01_23](https://cloud.githubusercontent.com/assets/5191497/22554588/a13f8800-e92e-11e6-90f8-5c39cfa8a03f.png)

If not, i'd be happy to take alternatives.

Cheers
Kimberly :octocat:

**Comment by amiga-500** [comment]
## Update

Ahh..just discovered that my #336 indeed could have been used as your solution since the Media Library apparently does call `wp_prepare_attachment_for_js()` too (just checking now).  Whoops!  I guess then i could have proposed you my solution 3 days ago instead :cry:.  Sorry about that.  My mind was just too focused on another part of W3TC to think clearly.

**Comment by amiga-500** [comment]
## Update 2
Hi again Nic ( @nicbarker ) 

Hmm... i just noticed that W3TC has the following option...

![content_delivery_network_w3_total_cache_0ssd_wordpress_-_2017-02-02_11_34_10](https://cloud.githubusercontent.com/assets/5191497/22558409/8e57481a-e93b-11e6-855b-48bfeb9c0a02.png)

I have to figure then naturally CDN is enabled for all logged in roles  but it was just not working for the media library until now.

And so, i guess its not necessary to include a new checkbox to enable CDN for the media library since it seems it was suppose to always be using the CDN in the first place, unless someone makes use of the _Disable CDN for role_ feature.

Let me know if i am misunderstanding this because as of now i guess i won't add the checkbox to disable for the Media Library (see my image 2 replies back) -- it will just always be using the CDN, if enabled, for it (unless one makes use of the _Disable for role_ feature).

Regards
Kimberly :octocat:

**Comment by nicbarker** [comment]
Hi Kimberly,
That solutions sounds perfect! You're right I think in that the media library was just something that was overlooked or forgotten about. It makes sense to have it enabled all the time unless the role is explicitly disabled.

However, I'm not sure if it's the correct thing to do to roll the functionality under the "disable CDN for the following roles". It's worth looking at these lines, that explicitly disable all CDN usage when in the admin interface:
https://github.com/szepeviktor/w3-total-cache-fixed/blob/v0.9.5.x/Cdn_Plugin.php#L505-L509
It seems like the authors original intention was to blanket disable the CDN entirely when you're inside wp-admin, no matter what role you are. I'm not sure if what we're doing now is breaking the convention too much, whether this needs to be rethought etc.

**Comment by amiga-500** [comment]
Ahhh thanks for pointing that out.  I didn't see that.  Ok i will definitely add the checkbox in then.  Easy enough.  I am currently outdoors so when i get back i will pr the final version. 

Once again, thanks for the assist!

**Comment by nicbarker** [comment]
No problem, thanks for your great work on this library.

**Comment by amiga-500** [comment]
Ok it's in #350 .  It requires changing 4 files.  For your convenience here they are:

[Cdn_ConfigLabels.php](https://raw.githubusercontent.com/szepeviktor/w3-total-cache-fixed/v0.9.5.x/Cdn_ConfigLabels.php)
[Cdn_Plugin.php](https://raw.githubusercontent.com/szepeviktor/w3-total-cache-fixed/v0.9.5.x/Cdn_Plugin.php)
[ConfigKeys.php](https://raw.githubusercontent.com/szepeviktor/w3-total-cache-fixed/v0.9.5.x/ConfigKeys.php)
[inc/options/cdn.php](https://raw.githubusercontent.com/szepeviktor/w3-total-cache-fixed/v0.9.5.x/inc/options/cdn.php)

If there are any issues just let me know

Kimberly :octocat:

**Comment by nicbarker** [comment]
Great, thanks so much!

**Comment by osterkraft** [comment]
@nicbarker Have you had any success with this recently? Besides using the latest version of w3tc-fixed and checking the box, did you take any additional steps? Nothing changes in the backend after I activate the option.

**Comment by nicbarker** [comment]
Hi @osterkraft, it seems to still work from my end, although I might have a slightly older version of w3 at the moment as I've done some modifications myself. Perhaps something has regressed in later versions since we made this fix?

**Comment by osterkraft** [comment]
Yeah I suspect something might have changed, or it could be that I'm running a multisite installation which makes it more complicated... Unfortunately I couldn't spend any more time researching it further so I decided to go for a completely different solution and set up a Elastic File System that is accessible from all my EC2 instances.

**Comment by tomellis** [comment]
I can't get this working either, tried reverting back to the commit it was introduced in and an earlier version of wordpress from that time and no luck.
