### ISSUE TITLE
W3TC is Always Tracking Users via Analytics

### ISSUE THREAD

**Issue by amiga-500** [szepeviktor/fix-w3tc#341]
Not sure if this is a bug or intentional but i noticed that at all times w3tc is tracking activity, including when it is immediately installed.  i believe the [WP guidelines](https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/) say this isnt allowed without first notifying the user first -- see # 7's bullet points area).

I know a popup in w3tc appears eventually ("support us")  and there is a checkbox to stop the tracking usage (it is already checked on) but i notice even if you uncheck it the **_common.track_usage_** variable (in master.php) is still set to true and so the following is what is added at all times to the admin page:
```
<script type="text/javascript">
    (function(i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r;
        i[r] = i[r] || function() {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date();
        a = s.createElement(o),
            m = s.getElementsByTagName(o)[0];
        a.async = 1;
        a.src = g;
        m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-2264433-8', 'auto');
    ga('set', {
        'dimension1': 'w3-total-cache',
        'dimension2': '0.9.5.2',
        'dimension3': '4.7.2',
        'dimension4': 'php7.1.1',
        'dimension5': 'Apache/2.4.23 (Unix) OpenSSL/1.0.1e-fips mod_bwlimited/1.4',
        'dimension6': 'mysql10.0.27',
        'dimension7': 'mydomain.com',
        'userId': 'myemail@gmail.com',
        'page': 'w3tc_dashboard'
    });

    ga('send', 'pageview');
```
Give it a try ... maybe i am wrong.

**Comment by nigrosimone** [comment]
This is a bug. In according with wp guidelines W3tc can't collect usage statistics without users approval and (maybe) this has some legal issue with the european privacy/cookie law.

**Comment by nicbarker** [comment]
Great find, this sounds pretty dodgy.

**Comment by amiga-500** [comment]
Fixed. #349
