### ISSUE TITLE
Suggestion: Move the config out of PHP and into the database

### ISSUE THREAD

**Issue by nicbarker** [szepeviktor/fix-w3tc#342]
The configuration settings for w3 are written to the disk in the file `wp-content/w3tc-config/master.php`. This is not only frustrating if you want to use in memory / CDN caches and disable write access to disk for security, but it's also super annoying if like me you have development, staging and production environments that all have different settings (meaning the settings have to be committed to gitignore and regenerated in new environments)

Is there any reason that these settings aren't stored in the database, as seems to be the case for a lot of other plugins?

**Comment by amiga-500** [comment]
Yea, for the life of me i can't figure out why the author had done that.  Since v0.9.5 he has also introduces a State class which allows custom w3tc writing to the db (he uses it to write all kinds of stuff like transients) but he hasn't shifted the config to that.  So it seems there is an important reason he doesn't.  I just don't know what that is.  At least having an option to allow people to write to the db as an alternative would be nice but i'd be in the dark if it would lead to something very nasty under a certain condition.

If you turn up anything new left me know.

**Comment by szepeviktor** [comment]
At the time of loading `advanced-cache.php` the database is not available. See wp-settings.php
Maybe I am wrong.

**Comment by szepeviktor** [comment]
It would be fantastic to keep w3tc configs in transients thus in object cache.

**Comment by nigrosimone** [comment]
> At the time of loading advanced-cache.php the database is not available. See wp-settings.php

This is true

> It would be fantastic to keep w3tc configs in transients

Not bad idea...

**Comment by nicbarker** [comment]
Are transients an appropriate place to store config data for a plugin? I thought transient data was mostly intended for short term cached storage. Like to me, I wouldn't store `post` objects in transients, should I store the config there?

**Comment by szepeviktor** [comment]
You're right.
Configs should be stored as options.

**Comment by nicbarker** [comment]
I guess it's important to give you guys some context about how we actually run WordPress. We run our wordpress installation through AWS elastic beanstalk, which means there is no guarantee that file storage will remain over a long period of time, and it also means that when the nodes managed by EBS get auto scaled, a new machine gets started up (i.e with different disk space and any cache / modified files on disk are lost)

I'm generally opposed to the idea of a plugin writing dynamic data into files on disk at run time, given the recent ops trends towards some variation of immutable infrastructure. Obviously this is unavoidable with a caching plugin that stores files on disk, but I think the difference is this:

- If you lose all your cache files on disk (i.e cached pages), they _can_ all be rebuilt from source files, there's no data loss.
- If you lose your config files on disk (or in transients) they _can't_ be rebuilt from source. They contain user inputted data that if changed can break the site completely.

Storing custom, non derived user data in files on disk inherently breaks multi server, load balanced environments - which are quite common these days especially for wordpress. Just something to think about.

**Comment by szepeviktor** [comment]
I think in this kind of environment you should install a Redis server/cluster/or as a service and store everything in there.

**Comment by nicbarker** [comment]
That's a great idea, as long as no config files end up on the disk :)

**Comment by nicbarker** [comment]
Actually, even still I feel like Redis is an inappropriate place to store config for a plugin like this. Unless you're running Redis in disk backed, recoverable mode you'll still be screwed if the server crashes and you lose all the in memory data.

**Comment by Volnus** [comment]
I think he was more talking about using Redis server side for your caching.
To do something on that scale you would want something like Redis or
Memcache or NGINX cache which is meant to run across multiple servers and
it prevents your cache from getting flushed like it would now.

**Comment by nicbarker** [comment]
Right, my mistake. I totally agree, shared in-memory cache is definitely the way to go for multi server setups, as long as the config itself is also in shared, non volatile storage.

**Comment by nigrosimone** [comment]
Another option is use both database and disk.  When the user saves the config first w3tc update the config stored into the db and after the config on disk. 

At this point when w3tc starts with the default config can check if into the db exists saved config and update disk. 

This allow to use w3tc in environment like AWS elastic beanstalk.

**Comment by nigrosimone** [comment]
if nobody want implement it, we close it?
_(20 days without nothing)_

**Comment by nicbarker** [comment]
Hi, apologies I've been away for a little while.
This is an interesting issue that I think would provide great value for people if we could figure out a solution, but it seems at the moment there needs to be a lot more discussion around potential implementations before we can settle on something.

I'm keen to talk about possibilities some more, but feel free to close the issue if you would rather not have active issues with potentially no solution. Maybe a slack channel for this plugin would work better for these kind of discussions?

**Comment by nigrosimone** [comment]
> but feel free to close the issue if you would rather not have active issues with potentially no solution

@nicbarker feel free to reopen it... thanks for your suggestion.
