### ISSUE TITLE
Fix PHP 7.1 tests

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/fix-w3tc#346]
If done please revert https://github.com/szepeviktor/w3-total-cache-fixed/commit/2cf13746ac5324058d1b61a3809c82ec8d8b2ea6

**Comment by nigrosimone** [comment]
On php 7.1 not works.

**Comment by szepeviktor** [comment]
We shouldn't solve *everything*

Solution: https://github.com/szepeviktor/w3-total-cache-fixed/issues/333#issuecomment-276072061

**Comment by szepeviktor** [comment]
Maybe closing a bug unsolved makes future not-so-bright...

**Comment by nigrosimone** [comment]
But this is a php-unit bug, we can solve it?

**Comment by szepeviktor** [comment]
No. But this bug is a *bug*, isn't it.
Waiting for https://github.com/sebastianbergmann/comparator/pull/30

**Comment by nigrosimone** [comment]
Ok!

**Comment by nigrosimone** [comment]
Maybe you can allow failures for PHP 7.1 (waiting for the fix)

**Comment by szepeviktor** [comment]
> allow failures for PHP 7.1

See the first comment.

**Comment by aelsharawi** [comment]
what is the problem with php 7.1 and is it solved?

**Comment by szepeviktor** [comment]
We welcome PR-s!
Please see https://travis-ci.org/szepeviktor/w3-total-cache-fixed/jobs/235782909

**Comment by nigrosimone** [comment]
https://github.com/szepeviktor/w3-total-cache-fixed/pull/496
