### ISSUE TITLE
Cache for additional home urls is not purged

### ISSUE THREAD

**Issue by nigrosimone** [szepeviktor/fix-w3tc#348]
If in additional home urls field we entered following domains in this way:
http://www.domain.me
http://domain.me
http://m.domain.me
http://www.m.domain.me

The cache is only purged from url from which is accessed.

For example if cache is purged from url http://domain.me everything is fine but on http://www.domain.me / m.domain.me and http://www.m.domain.me is not appearing new content…

**Comment by nicbarker** [comment]
Good catch. This potentially points to another large issue as well - I personally think it's _extremely_ bad practise to have destructive admin actions accessible via a GET request (e.g http://wordpress.com/?w3tc_note=flush_all).

There are so many issues with this, like someone accidentally pressing the back button, browser auto complete, or a malicious user tricking an admin into clicking a link with embedded actions.

Just something to think about if there are other examples of this happening.

**Comment by amiga-500** [comment]
@nigrosimone ... curious...can you try adding a trailing slash to each of your entries and see if caching works?  for example in your additional home urls fields put in:

http://www.domain.me/
http://domain.me/
http://m.domain.me/
http://www.m.domain.me/

**Comment by amiga-500** [comment]
## Update
Ok it seems my hunch may be right.   I think the fix is this: #357

Give it a try @nigrosimone and if it works you can do the honors of merging. :rainbow:

**Comment by nigrosimone** [comment]
Yep! Now works. Always thanks.
