### ISSUE TITLE
Allow PHP7.1 Test Fails for v0.9.4.x too :(

### ISSUE THREAD

**Issue by amiga-500** [szepeviktor/fix-w3tc#354]
Hi @szepeviktor i modified **_travis.yml_** to allow for php7.1 fails for the v0.9.4.x brnach  but because i can't commit it to the branch due to the test fails it is stuck permanently :sob:  . 

 Can you work your voodoo magic to fix this?  I figure you would have to remove the branch protection feature from v0.9.4.x to allow the commit to happen.  

Btw, since v0.9.5.x is now the master branch i guess it can now be the protected one instead, if you can't make both branches protected.

Thanks

**Comment by szepeviktor** [comment]
Done.

**Comment by amiga-500** [comment]
:kissing_heart:
