### ISSUE TITLE
with HTML minify settings enabled, debug info disappear

### ISSUE THREAD

**Issue by nigrosimone** [szepeviktor/fix-w3tc#372]
without HTML minify settings enabled in the html code i see

```html
<!-- Performance optimized by W3 Total Cache. Learn more: https://www.w3-edge.com/products/

Page Caching using disk: enhanced (Requested URI contains query)
Minified using disk

 Served from: sndsgn.altervista.org @ 2017-02-12 02:23:24 by W3 Total Cache -->
```

with HTML minify settings enabled those debug info disappear.

**Comment by nigrosimone** [comment]
if i have a good memory we have fixed the same issue in the 0.9.4.x branch but i don't found the PR....

**Comment by amiga-500** [comment]
Yea we got rid of it in v0.9.4.x somewhere.  In 0.9.5.x shows this intentionally at all times, unless one activates Edge mode.

So one is forced to deactivate it via adding this to a themes functions.php file:
```php
add_filter('w3tc_can_print_comment',function($w3tc_setting){ return false; },10,1);
```

**Comment by nigrosimone** [comment]
But i want it :D

My point is: when enable html minify this info disappear

This info is useful for me for understand the state of the cache

**Comment by amiga-500** [comment]
Oh sorry..i misunderstood.  I believe you can keep it via adding: _`Performance optimized`_ under the **Ignored comment stems** field.

**Comment by nigrosimone** [comment]
Yep it works!  Always thanks!

**Comment by nigrosimone** [comment]
Maybe in the Frederick logic this comment stems should became a default value
; )
