### ISSUE TITLE
Malformed WP Query String

### ISSUE THREAD

**Issue by amiga-500** [szepeviktor/fix-w3tc#385]
This is related to an issue discussed [here](https://github.com/szepeviktor/w3-total-cache-fixed/issues/379#issuecomment-279789498) and [here](https://github.com/szepeviktor/w3-total-cache-fixed/issues/379#issuecomment-279830071).

**Comment by amiga-500** [comment]
Hi @twiginteractive

I fixed your problem :bowtie:.  I haven't committed the changes to the master branch just yet.  I wanted to see if you could try it out and provide confirmation for me. :pray: 

For your convenience here are the changed files:

[inc/define.php](https://raw.githubusercontent.com/szepeviktor/w3-total-cache-fixed/50c9e40f75a7982b894a4292478cbf10df7e30e1/inc/define.php)
[lib/Minify/Minify/CSS/UriRewriter.php](https://raw.githubusercontent.com/szepeviktor/w3-total-cache-fixed/50c9e40f75a7982b894a4292478cbf10df7e30e1/lib/Minify/Minify/CSS/UriRewriter.php)
[lib/W3/DbCacheAdminEnvironment.php](https://raw.githubusercontent.com/szepeviktor/w3-total-cache-fixed/50c9e40f75a7982b894a4292478cbf10df7e30e1/lib/W3/DbCacheAdminEnvironment.php)
[lib/W3/ObjectCacheAdminEnvironment.php](https://raw.githubusercontent.com/szepeviktor/w3-total-cache-fixed/50c9e40f75a7982b894a4292478cbf10df7e30e1/lib/W3/ObjectCacheAdminEnvironment.php)
[lib/W3/Plugin/BrowserCache.php](https://raw.githubusercontent.com/szepeviktor/w3-total-cache-fixed/50c9e40f75a7982b894a4292478cbf10df7e30e1/lib/W3/Plugin/BrowserCache.php)
[lib/W3/Plugin/Cdn.php](https://raw.githubusercontent.com/szepeviktor/w3-total-cache-fixed/50c9e40f75a7982b894a4292478cbf10df7e30e1/lib/W3/Plugin/Cdn.php)

Thanks
Kimberly :octocat:

**Comment by twiginteractive** [comment]
Hi @amiga-500 - 

Tested and confirmed working. Awesome work as always 🥇
