### ISSUE TITLE
Debug Mode Shows No Debug Info in Output

### ISSUE THREAD

**Issue by amiga-500** [szepeviktor/fix-w3tc#390]
Seems this is a bug in v0.9.5.x.  I also verified it in the official release and noticed the same thing:

### **1. When i do this (in v0.9.5.x):**
![debug](https://cloud.githubusercontent.com/assets/5191497/23042952/b2d450e2-f468-11e6-814c-518e84ed2500.png)

### **2. It only shows this:**
![capture_001_16022017_165341](https://cloud.githubusercontent.com/assets/5191497/23042932/9b930090-f468-11e6-943b-d2ccc0ae4984.jpg)

### **3. Instead of this (captured from v0.9.4.6.3):**
![capture_002_16022017_170350](https://cloud.githubusercontent.com/assets/5191497/23043346/ed5fc60a-f469-11e6-83c9-32552b025b53.jpg)

**Comment by charlesLF** [comment]
I believe v0.9.5.x is now saving the debug info to file?
`PgCache_ContentGrabber.php` in function `log`

**Comment by amiga-500** [comment]
Ahh thats interesting to know.  Thanks for the heads up.  I notice though what is saved under e.g., _cache/log/000000/minify.log_ (or _pgcache.log_, etc) seem to be raw php function details, but does not include the summary information (as seen in the pic above).

It seems this missing summary is actually located in the function **`w3tc_footer_comment()`**.  It's set as a filter but there is no related `do_filters()` ever called in W3TC so as to trigger it, preventing it from ever being inserted.  This function exists in: 

`PgCache_ContentGrabber.php`
`Cdn_Plugin.php`
`Minify_Plugin.php`
`DbCache_WpdbInjection_QueryCaching.php`
`Extension_FragmentCache_WpObjectCache.php`
`ObjectCache_WpObjectCache_Regular.php`

When analyzing the code it seems Frederick is still in the process of tying it all together.  So i don't think its a bug, but more of something that will probably be coming in a future official release.  That or he forgot all about it and its orphaned.  We shall see in later releases.

**Comment by charlesLF** [comment]
Ah! Good to know!

Let's keep an eye on it and see if it gets fixed in a future release or if we'll have to do the fix ourselves.
