### ISSUE TITLE
Involving one more active contributor

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/fix-w3tc#392]
Please see https://github.com/szepeviktor/w3-total-cache-fixed/stargazers

What would be the appropriate way to call for a new contributor?

There must be one of the thousands willing to help https://wordpress.org/plugins/w3-total-cache/stats/
Open a support topic on WP.org specifically for this?

**Comment by nigrosimone** [comment]
I'm a bit active on the official forum and when i find a guy with tech skills,  i inform it on this github project.

**Comment by deltafactory** [comment]
After a long time with W3 Total Cache, I plan to fall back to simple modules that provide the exact functionality I need. W3TC is a large beast and I feel that discrete components would be easier to maintain and troubleshoot. Otherwise, I'd be on board.

**Comment by szepeviktor** [comment]
Hello @deltafactory !

Do you have a list of those substitutions?

Here are some

- minify https://github.com/kasparsd/minit
- Redis object cache https://github.com/pantheon-systems/wp-redis
- page cache with Memcached https://wordpress.org/plugins/wp-spider-cache/

Do you have a **lean** page cache solution? Full of hooks and no bloated GUI?
Like https://github.com/petermolnar/wp-ffpc

**Comment by deltafactory** [comment]
I need to explore Redis, the new hotness, vs Memcache. Stability in PHP7+ is a requirement (PECL Memcache(d) is an unknown.)

The standard memcache object cache drop-in was a good starting point for me.
I was going to start with Batcache https://wordpress.org/plugins/batcache/ but I'm open to any.

I also plan to write my own W3TC-inspired CDN-pull plugin that rewrites asset URLs.

**Comment by szepeviktor** [comment]
@amiga-500 Some guys are contributing.
Where are they coming from??

**Comment by amiga-500** [comment]
Not sure.  It wasn't anything i did.  It's really nice though :smiley:   Our links keep getting spread (usually direct links to bug fixes -- stumbled onto a random site today and saw one mentioned in an article) and so i figure it's just a matter of time when new intrigued contributors would pop in who also want to leave their mark.  Let's hope it continues :pray: 

Cheers
Kimberly
