### ISSUE TITLE
Fix feeds on the Dashboard

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/fix-w3tc#396]
This is a report-only issue.

**Comment by nigrosimone** [comment]
- [x] Fix Widget with posts from w3-edge's blog
- [X] [Fix Widget with topics from w3tc's wordpress forum](https://github.com/szepeviktor/w3-total-cache-fixed/pull/413)

**Comment by szepeviktor** [comment]
Fixed! 😉

**Comment by szepeviktor** [comment]
I've added an item to the Wiki changelog.
