### ISSUE TITLE
Add composer support

### ISSUE THREAD

**Issue by archon810** [szepeviktor/fix-w3tc#403]
Hi,

We use composer https://getcomposer.org for plugin and WP management, and usually most plugins reside in WP's svn and can be installed using https://wpackagist.org/ which composerifies them automatically.

Could you please add support for composer in this repo? Should be as simple as adding composer.json file with a few details.

Thanks.

**Comment by archon810** [comment]
PR up. Tested locally, works great.

**Comment by archon810** [comment]
There's one issue with this setup, however. Since the installation dir is w3-total-cache-fixed and not w3-total-cache, the plugin activates fine but then runs into the following issue when you go to Performance:

```
W3 Total Cache Error: some files appear to be missing or out of place. Please re-install plugin or remove /srv/www/htdocs/site/public/wp-content/advanced-cache.php. 
Attempt to create object of class W3TC\Config has been made, but file /srv/www/htdocs/site/public/wp-content/plugins/w3-total-cache/Config.php doesnt exists
#0 w3tc_class_autoload(W3TC\Config)
#1 spl_autoload_call(W3TC\Config) called at [/srv/www/htdocs/site/public/wp-content/plugins/w3-total-cache-fixed/w3-total-cache-api.php:726]
#2 require_once(/srv/www/htdocs/site/public/wp-content/plugins/w3-total-cache-fixed/w3-total-cache-api.php) called at [/srv/www/htdocs/site/public/wp-content/plugins/w3-total-cache-fixed/w3-total-cache.php:60]
#3 include_once(/srv/www/htdocs/site/public/wp-content/plugins/w3-total-cache-fixed/w3-total-cache.php) called at [/srv/www/htdocs/site/public/wordpress/wp-settings.php:304]
#4 require_once(/srv/www/htdocs/site/public/wordpress/wp-settings.php) called at [/srv/www/htdocs/site/public/wp-config.php:200]
#5 require_once(/srv/www/htdocs/site/public/wp-config.php) called at [/srv/www/htdocs/site/public/wordpress/wp-load.php:42]
#6 require_once(/srv/www/htdocs/site/public/wordpress/wp-load.php) called at [/srv/www/htdocs/site/public/wordpress/wp-admin/admin.php:31]
```

Renaming the dir to w3-total-cache fixes the issue.

The check in advanced-cache.php seems to hardcode the plugin dir:
```
  if ( !defined( 'W3TC_DIR' ) ) {
    define( 'W3TC_DIR', ( defined( 'WP_PLUGIN_DIR' ) ? WP_PLUGIN_DIR : WP_CONTENT_DIR . '/plugins' ) . '/w3-total-cache' );
  }
```

Are we always expected to install to w3-total-cache? The README doesn't make a mention of it. If so, it probably should, and I'll tweak the PR.

Or is there a setting that got cached somewhere with the dir name that I'm missing?

**Comment by amiga-500** [comment]
Hi @archon810 

> _Are we always expected to install to w3-total-cache? The README doesn't make a mention of it. If so, it probably should, and I'll tweak the PR._

Yes, for the v095x repo the directory is hardcoded in multiple files of W3TC (not just _advanced-cache.php_) to be _**w3-total-cache**_.

**Comment by archon810** [comment]
PR updated, tested locally and now it activates and works fine.

**Comment by amiga-500** [comment]
Thanks!

**Comment by archon810** [comment]
@amiga-500 Should the docs be updated to account for the very specific plugin dir name? Especially since the git download of the branch doesn't even name it the proper way.

**Comment by amiga-500** [comment]
shame the git download doesnt allow one to assign the proper dir name.  It's only under the releases that the zips we have there correct this issue.  So yes, i will update the readme.txt, and README.MD to mention that the dir should be w3-total-cache since not everyone will be downloading the release zips but instead doing so via the git download button.
