### ISSUE TITLE
Expose Memcached connection persistence configuration

### ISSUE THREAD

**Issue by deltafactory** [szepeviktor/fix-w3tc#416]
Using a cluster of web servers with multiple memcache nodes, I'm seeing persistent connections rise until they hit the server's max connection limits. I've implemented process recycling in PHP and connection timeouts on the memcache server but I think the connection persistence feature might be the better way to resolve this.

I know that there's a trade-off during the re-connection but at least open connections are active ones. This may be mitigated by an idle timeout on the client side though I don't know if that's within the scope of this project.

**Comment by nigrosimone** [comment]
> I think the connection persistence feature might be the better way to resolve this.

hi @deltafactory, maybe i have mistake your question but the persistent connection is already a w3tc 0.9.5.x's feature:

![immagine](https://cloud.githubusercontent.com/assets/310077/23329380/761291b6-fb37-11e6-828e-b10730db88e4.jpg)

Side note: i suppose you use 0.9.5.x version

**UPDATE**

i see https://github.com/szepeviktor/w3-total-cache-fixed/issues/402 and you talking about 0.9.4.x, are you on 0.9.4.x? 

if you are on 0.9.4.x i think it's time to update to 0.9.5.x, we have made tons of fixes on it https://github.com/szepeviktor/w3-total-cache-fixed/wiki/Changelog

**Comment by deltafactory** [comment]
Yes, I'm using 0.9.4.x. We'll need to do some testing before upgrading but I'm glad to see the option is available.

**Comment by nigrosimone** [comment]
@deltafactory yeah, good idea! re-open the issue if you found any problem!
