### ISSUE TITLE
Unit Testing + Travis CI

### ISSUE THREAD

**Issue by nigrosimone** [szepeviktor/fix-w3tc#44]
It’s super nice to have contributions from someone else but it’s hard to see if those changes break existing features. We all do mistakes from time to time and it’s easier to recover if you have good test coverage. Automated integration tests can help you out in these situations.

Is someone available in writing unit tests and integration with Trevis?

**Comment by nigrosimone** [comment]
Guys,  i think this is important :)

**Comment by amiga-500** [comment]
I'll have to go read up... i know nothing about it.

**Comment by nigrosimone** [comment]
you don't know unit testing? Try to google it

In project like this is very useful.

**Comment by cesco69** [comment]
@amiga-500 https://phpunit.de/getting-started.html

**Comment by amiga-500** [comment]
Oh i know unit testing.  I just don't know Travis CI and the whole integration process.
Thanks for the link!  I will do reading about Travis in the coming days.

**Comment by nigrosimone** [comment]
@szepeviktor please, help me...! how confing travis to work with apcu? i want make some unit test!

**Comment by szepeviktor** [comment]
Just install APCu in a shell script depending on the PHP version: `apt-get install -y php5-apcu` and `apt-get install -y php7.0-apcu`

See https://docs.travis-ci.com/user/installing-dependencies/

**Comment by nigrosimone** [comment]
mhhh ok i need to study travis https://github.com/szepeviktor/fix-w3tc/pull/107

if you have time, you can set travis for me?

i have also write some unit tests in test dir.
