### ISSUE TITLE
Error message for WooCommerce stays when updating dbcache.reject.sql option via wp-cli

### ISSUE THREAD

**Issue by theredcat** [szepeviktor/fix-w3tc#443]
Env :
- PHP-FPM 7.0
- Mysql 5.7
- WordPress 4.7.3
- W3 Total Cache 0.9.5.2
- WP CLI 1.1.0 (+ psych 0.8.2)
- WooCommerce 2.6.14

Reproduction: 
Install wordpress
Install wp-cli
Install w3-total-cache
Configure w3-total-cache
Install woocommerce
Update dbcache.reject.sql via wp-cli like this :
```
root@9ec9f2762289:/app/wp# wp --allow-root total-cache option set dbcache.reject.sql "gdsr_                                                                                                                        
wp_rg_
_wp_session_
_wc_session_"
```

When I update the dbcache.reject.sql option to add `_wc_session_` as requested by the wp admin the option is updated, but the error message stays in the admin. If I hit the "Save" button without any modification, the error message goes away

**Comment by nigrosimone** [comment]
> but the error message stays in the admin.

the error message is a woo commerce error message... maybe it's a woo commerce issue... i think woo commerce not handle changes behind wp-cli and the error persists after the change.

> When I update the dbcache.reject.sql option to add _wc_session_ as requested by the wp admin the option is updated

this means: w3tc has handled your change request via cli.

> If I hit the "Save" button without any modification, the error message goes away

maybe, after safe, woo commerce re-check the w3tc's setting and found _wc_session_.

therefore, if you think this is a w3tc issue i can investigate and fix, but from your description it seem a woo commerce issue.

thanks.

**Comment by nigrosimone** [comment]
@theredcat any news?
