### ISSUE TITLE
Purge a specific path - how can it be done?

### ISSUE THREAD

**Issue by danwie** [szepeviktor/fix-w3tc#456]
I have a custom rewrite rule with a dynamic variable. W3TC is caching everything, and that is fine. However, at times I need to purge a specific path, Ex: `isbn/9781118083390/`. I know that it is possible to purge specific posts with `w3tc_pgcache_flush_post()`. I also know that `w3tc_pgcache_flush_url()` is available, and I've tried `w3tc_pgcache_flush_url('isbn/9781118083390/')` but it isn't working.

Is it possible to purge a specific path? If not, would it be possible to implement such a function?

**Comment by charlesLF** [comment]
Hey @danwie:
 The `w3tc_pgcache_flush_url` function expects a full URL for the page.
example: `w3tc_pgcache_flush_url("http://www.example.com/isbn/9781118083390/")`.

Also, in v0.9.5-fix, there's a widget on the dashboard where you can paste a bunch of URL's and purge them from there. Try it out and let me know if it works!

**Comment by danwie** [comment]
It works. Thanks a lot!!
