### ISSUE TITLE
Azure Media Export

### ISSUE THREAD

**Issue by bradcdelaney** [szepeviktor/fix-w3tc#460]
I seem to be experiencing an issue with the Azure CDN Media File Export where the export stops after just 221 files or 30 seconds leaving many files out of the CDN. This same issue does not happen with wp-includes, themes, or other files folders - Only with the media file.

It is helpful if you provide details of your environment:

- Webserver name and version: Ubuntu 16.04
- PHP version and handler type (e.g. mod_php, suPHP, PHP-FPM): PHP 7.0.17
- Database server name and version: MySQL 14.14
- WordPress core version: 4.7.3
- W3 Total Cache plugin version: 0.9.5.2

Any help you can offer would be much appreciated.

Thank you!

-Brad

**Comment by nigrosimone** [comment]
hi @bradcdelaney,
just some day ago @sbutler has fixed a similar issue: [Media Library Export skips files](https://github.com/szepeviktor/w3-total-cache-fixed/pull/452)

this bug fix is included in the [latest release ](https://github.com/szepeviktor/w3-total-cache-fixed/releases/latest)

Thanks and sorry for the long delay.

**Comment by szepeviktor** [comment]
> this bug fix is included in the latest release

We hope it is.
