### ISSUE TITLE
External JS and/or CSS is not combined/minified when minify set to auto mode

### ISSUE THREAD

**Issue by caraffa** [szepeviktor/fix-w3tc#461]
Very simple! In my deve environment I've a bunch of local (to my webserver/domain) JS and a couple of references to external resources (namely: facebook's sdk.js and google's analytics.js).
While the former are packed/combined/gziped neatly, the latter is totally ignored.
Th behavior is totally different if I chose "manual" minify mode. Everything is combined as expected.
The problem is that my set of javascript/js can vary greatly upon different conditions, so I cannot "dynamically" change the w3tc manual minify settings each time my set of JS changes.
Ideal behavior would be, as said, that the "auto" minify option would work as expected.
In the mean time, as a workaround, I'm forced to copy the external resources locally.

Thanks for any suggestion/help and, most of all, thanks for your job. 

- Webserver ngix (ver?) 
- PHP 7.1
- MySQL 5.6
- WordPress 7.1
- W3 Total Cache plugin 0.9.5.2.4

**Comment by nigrosimone** [comment]
In the minify page setting there is the minify option **Include external files/libraries**

**Comment by caraffa** [comment]
It works. Sorry! I didn't notice the option.
Thanks again.
I'm closing the issue
