### ISSUE TITLE
Hyperdb Plugin Conflict

### ISSUE THREAD

**Issue by somadona** [szepeviktor/fix-w3tc#463]
Hello,

Now W3TC is conflicting with hyperdb plugin as they both put "db.php" file in "wp-content" directory.

Can we fix that conflict please ?

**Comment by nigrosimone** [comment]
You can disable db cache and w3tc desn't put db.php in wp-content folder

**Comment by wp-networks** [comment]
Same issue and same solution for LudicrousDB, and likely any other plugins that require a db dropin :)

**Comment by szepeviktor** [comment]
You may use only one of every drop-in kind.

**Comment by somadona** [comment]
Thanks for your replies @nigrosimone @wp-networks @szepeviktor  but I need to use caching for database too is that possible while activating hyperdb ?

**Comment by nigrosimone** [comment]
Nope, because for cache the db,  w3tc need   db.php
