### ISSUE TITLE
Missing fixes

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/fix-w3tc#472]
- [x] https://github.com/szepeviktor/w3-total-cache-fixed/blob/v0.9.5.x/pub/opcache.php
- [x] https://github.com/szepeviktor/w3-total-cache-fixed/blob/v0.9.5.x/readme.txt 
- [x] https://github.com/szepeviktor/w3-total-cache-fixed/blob/v0.9.5.x/w3-total-cache.php
- [x] maybe https://github.com/szepeviktor/w3-total-cache-fixed/blob/v0.9.5.x/w3-total-cache-api.php

There's a list in https://github.com/szepeviktor/w3-total-cache-fixed/issues/468#issuecomment-297788649

Last known state: https://github.com/szepeviktor/w3-total-cache-fixed/tree/3670939bfc5b71ef70f250ae10eafa08c8b57a48
just after #459

**Comment by szepeviktor** [comment]
@Furniel Could you find out how these have been missed?

**Comment by Furniel** [comment]
- Looks like fix to opcache wasn't in list of fixes that missing in official version.
- I didn't updated readme files at all(only code)
- W3-total-cache-fixed.php contains only version number fixes, I didn't changed version.
- Can't compare w3-total-cache-api line by line (from mobile now), but all changes should be there.

**Comment by szepeviktor** [comment]
> Looks like fix to opcache wasn't in list of fixes that missing in official version.

Here it is: https://github.com/szepeviktor/w3-total-cache-fixed/pull/387/files

**Comment by nigrosimone** [comment]
> Looks like fix to opcache wasn't in list of fixes that missing in official version.

because is just a fix into the comment https://github.com/szepeviktor/w3-total-cache-fixed/pull/387/files#diff-8ad3ed895032ad08085373c888610812L3 and i don't have added to the changelog.

**Comment by szepeviktor** [comment]
Here you are in the last row https://github.com/szepeviktor/w3-total-cache-fixed/wiki/Changelog
No need to put it in the readme.

**Comment by nigrosimone** [comment]
* https://github.com/szepeviktor/w3-total-cache-fixed/blob/v0.9.5.x/readme.txt
* https://github.com/szepeviktor/w3-total-cache-fixed/blob/v0.9.5.x/w3-total-cache.php

Fixed by #474

**Comment by nigrosimone** [comment]
It seem all ok https://github.com/szepeviktor/w3-total-cache-fixed/pull/475
