### ISSUE TITLE
Mess in Util_PageUrls.php

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/fix-w3tc#473]
Our history
https://github.com/szepeviktor/w3-total-cache-fixed/commits/v0.9.5.x/Util_PageUrls.php
History of @Furniel
https://github.com/Furniel/W3-Total-Cache/commits/0.9.5.4/Util_PageUrls.php

See whole file and diff: https://github.com/szepeviktor/w3-total-cache-fixed/tree/Util_PageUrls

**Comment by szepeviktor** [comment]
Maybe just an indentation issue?

**Comment by Furniel** [comment]
Looked at your  diff, I see only different number of spaces/tabs.

**Comment by szepeviktor** [comment]
Could you please compare your Util_PageUrls.php and the one in this repo?
Thanks.
