### ISSUE TITLE
get_pages_urls() function prevents single page from PURGE

### ISSUE THREAD

**Issue by Hermsi1337** [szepeviktor/fix-w3tc#481]
Hey folks,

we recently set up a Wordpress 4.7.4 and the latest "W3 Total Cache"-Plugin along with a Varnish 3.

As we all know, W3 Total Cache automatically sends a "PURGE" to Varnish as soon as a new post was published concerning all to that post related URLs. In W3 Total Cache "Page Cache"-Options we configured, that the page "foo" should also be PURGED in addition to the regular URLs.

But even though we configured W3 Total Cache to PURGE our "foo"-page, it was never PURGED.
It took us some time, but we finally figured out why...

Our page "foo" is stored as follows in Varnish:
"www.my.domain/foo"

W3 Total Cache sends a PURGE request for the following URL to our Varnish:
"www.mydomain.com/foo/".

Do you notice the trailing slash at the end? 
Varnish is looking for "www.mydomain.com/foo/" in order to PURGE it, instead of PURGING "www.my.domain/foo".

The consequence is, that our page "foo" remains un-PURGED. 

After investigating this whole thing quite further, we found out where W3TC is adding the trailing slash to the end. 

[This file](../blob/v0.9.5.x/Varnish_Flush.php) is responsible for flushing the varnish cache.
Furthermore, the [line 373](../blob/v0.9.5.x/Varnish_Flush.php#L373) collects the additional pages using the function ```get_pages_urls``` [defined here](../blob/v0.9.5.x/Util_PageUrls.php#L438).
And finally, in [line 446](../blob/v0.9.5.x/Util_PageUrls.php#L446) the trailing slash is added to the end.

We "fixed" the problem by changing [line 446](../blob/v0.9.5.x/Util_PageUrls.php#L446) as follows:
```php
$page_link = get_home_url() . '/' . trim( $page_slug, '/' );
```
I'm not really sure if this is an issue related to W3TC or to the varnish server.

What do you guys think?

Regards,

Hermsi

**Comment by szepeviktor** [comment]
> Our page "foo" is stored as follows in Varnish:
> "www.my.domain/foo"

Please try telling varnish not to normalize URL-s.

**Comment by Hermsi1337** [comment]
> Please try telling varnish not to normalize URL-s.

Some Managed-Varnish-Hostings do that by default and are not permitting to change these settings.

But why is the trailing slash added by W3TC in the first place?

**Comment by szepeviktor** [comment]
WordPress has an URL structure which always includes a trailing slash.

**Comment by szepeviktor** [comment]
~Try cloning `get_pages_urls()`. E.g. `some_prefix_get_pages_urls()`~

Sorry w3tc calls this not you.

**Comment by szepeviktor** [comment]
Got it! Try hooking into `varnish_flush_post_queued_urls` and do the purging yourself with the modified URL -> copy code from w3tc.
