### ISSUE TITLE
WP-CLI differences between 0.9.4.x and 0.9.5.x

### ISSUE THREAD

**Issue by twiginteractive** [szepeviktor/fix-w3tc#492]
Hi! I worked with you on adding the great cache 'prime' feature to the WP-CLI for the 0.9.4.x branch, and I love it. Recently, I started a new project and thought I'd use the newer 0.9.5.x branch - but now I seem to have lost the prime command.

Doing `wp help w3-total-cache` on the two environments returns different info: the 4.x has the prime command listed, but the 5.x line doesn't. I can see from the .5.x changelog that the feature should still be there. Am I missing something?

Thanks!

**Comment by nigrosimone** [comment]
Strange... @amiga-500 has implemented the feature in the https://github.com/szepeviktor/w3-total-cache-fixed/pull/324 maybe , has she missed to update `help`?

if you call:
`wp w3-total-cache prime`

what happens?

**Comment by twiginteractive** [comment]
Hi @nigrosimone - as expected, it returns the correct command prompt in 4.x branch, and the error "prime is not a function" for the 5.x branch.

**Comment by nigrosimone** [comment]
Hi, i have just downloaded the master and on my env (windows) it works:

![immagine](https://cloud.githubusercontent.com/assets/310077/26464034/acea10ca-4186-11e7-82e2-e677992c2256.jpg)

**Comment by twiginteractive** [comment]
Hmm ok. Let me install it on my sandbox and check. I'm hoping this is an error on my side - I can't believe it would have slipped through this long!

**Comment by nigrosimone** [comment]
All right, keep me updated on everything to do with this case.

**Comment by twiginteractive** [comment]
Welp you can put this down to user error :)

Turns out I had a config.yml in the ~/.wp-cli folder that was setting the path to WP to the Prod install (not the Dev install I was actually in). Prod currently has the original W3TC plugin (not this community version) in it! That would explain the lack of prime function.

Sorry for the unnecessary fire-drill.

**Comment by nigrosimone** [comment]
Hey, no problem! you are welcome!
