### ISSUE TITLE
Object cache backends in tests

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/fix-w3tc#494]
I think object cache backends are not installed on Travis (PHP extension + service)

**Comment by nigrosimone** [comment]
in .travis.yml there is

```
services:
    - memcached
    - redis-server
```

and apcu

```
before_script:
  - if [[ $TRAVIS_PHP_VERSION =~ 5.[56] ]] ; then echo yes | pecl install apcu-4.0.10 ; fi
  - if [[ $TRAVIS_PHP_VERSION = 7.* ]] ; then pecl config-set preferred_state beta ; echo yes | pecl install apcu ; fi
```

**Comment by szepeviktor** [comment]
Could we check the PHP extensions and the services during the test?
Maybe the redis and memcached extension is missing. e.g. `php --ri redis`

Note the amount of skipped tests.

**Comment by nigrosimone** [comment]
> Could we check the PHP extensions and the services during the test?

yes, each test check if the relative service is installed, eg.:

```php
if( !class_exists('Memcache',false) && !class_exists('Memcached',false) ){
    $this->markTestSkipped('all tests in W3_Object_Cache_Memcache_Test are invactive because Memcache(d) class not exists!');
    return;
}
```

> Note the amount of skipped tests.

this happened when the relative service isn't installed

**Comment by szepeviktor** [comment]
Could we have all services installed at all times?

**Comment by nigrosimone** [comment]
yes, we have tests on apc, apcu, memcache, redis and file, see: https://github.com/szepeviktor/w3-total-cache-fixed/tree/v0.9.5.x/tests

**Comment by nigrosimone** [comment]
maybe ours test on memcache and redis are always skipped because we don't install and enable the relative pecl library and the check `class_exists('Memcache')` and `class_exists('Redis')` always return false and the test is skipped.

**Comment by szepeviktor** [comment]
Please see https://docs.travis-ci.com/user/languages/php/#Preinstalled-PHP-extensions
and https://docs.travis-ci.com/user/languages/php/#Enabling-preinstalled-PHP-extensions

**Comment by nigrosimone** [comment]
ok... https://github.com/szepeviktor/w3-total-cache-fixed/pull/496/files

**Comment by szepeviktor** [comment]
Thank you.

Do we have much less skips?

**Comment by nigrosimone** [comment]
we skips only the tests for APC when the php version is >5.4 and the tests for APCu when the php version is 5.3 or 5.4, but is normal.

**Comment by nigrosimone** [comment]
side note: i have tried to make tests with mysqli but for some unknown reason it doesn't works.

**Comment by szepeviktor** [comment]
Hello @nigrosimone !
What is happening around this repo?
It seems like we have no more bug reports. Is W3TC completely fixed?

**Comment by nigrosimone** [comment]
No one reproducible! We have 7 mystery bugs https://github.com/szepeviktor/w3-total-cache-fixed/issues?q=is%3Aissue+is%3Aopen+label%3ABug
