### ISSUE TITLE
Call to a member function using_index_permalinks() on a non-object in

### ISSUE THREAD

**Issue by neelgo** [szepeviktor/fix-w3tc#503]
[Fri Jun 16 06:34:13 2017] [warn] [client 115.93.41.195] mod_fcgid: stderr: PHP Fatal error:  Call to a member function using_index_permalinks() on a non-object in /var/www/vhosts/xxxxxxxxx/plugins/w3-total-cache/Util_PageUrls.php on line 503

**Comment by szepeviktor** [comment]
Look @neelgo !
It is fixed here on [GitHub](https://github.com/szepeviktor/w3-total-cache-fixed/blob/v0.9.5.x/README.md)
https://github.com/szepeviktor/w3-total-cache-fixed/commit/5db4cf4b2180095c1c4d3dc343dd26fe2e7c0d04
