### ISSUE TITLE
wrong download link in latest release (0.9.5.4.2) description

### ISSUE THREAD

**Issue by marian-kadanka** [szepeviktor/fix-w3tc#508]
https://github.com/szepeviktor/w3-total-cache-fixed/releases/tag/0.9.5.4.2 description includes "Download Link: w3-total-cache-fixed-(for-v0.9.5.x-users).zip" which refer to old version 0.9.5.2.4 instead of 0.9.5.4.2. Link in the "Downloads" section at the bottom of the page refers to correct version, though.

**Comment by nigrosimone** [comment]
Thanks, fixed.
