### ISSUE TITLE
Undefined property: W3TC\\Extension_Amp_Plugin::$is_amp_endpoint

### ISSUE THREAD

**Issue by ifaist0s** [szepeviktor/fix-w3tc#509]
Hello,

I looked at the issues and it seems this hasn't been reported yet.

The error log is filled with the following notices:

`[Thu Jun 29 09:42:07.473748 2017] [:error] [pid 27221] [client 1.2.3.4:53172] PHP Notice:  Undefined property: W3TC\\Extension_Amp_Plugin::$is_amp_endpoint in /wp-content/plugins/w3-total-cache/Extension_Amp_Plugin.php on line 28, referer: https://www.google.gr/`

`[Thu Jun 29 09:42:07.474463 2017] [:error] [pid 27221] [client 1.2.3.4:53172] PHP Notice:  Undefined property: W3TC\\Extension_Amp_Plugin::$is_amp_endpoint in /wp-content/plugins/w3-total-cache/Extension_Amp_Plugin.php on line 32, referer: https://www.google.gr/`

Is there anything that can be done to fix this?

**Here are all the details:**

- Apache/2.4.7 (Ubuntu)
- PHP 5.5.9-1ubuntu4.21 (Apache 2.0 Handler)
- MySQL 5.5.55-0ubuntu0.14.04.1 (Ubuntu)
- WordPress 4.7.5
- W3 Total Cache (Fixed) Version 0.9.5.4.2 | By W3TC (Fixed) Community

Thanks in advance! :)

**Comment by nigrosimone** [comment]
thanks, fixed in https://github.com/szepeviktor/w3-total-cache-fixed/pull/510
