### ISSUE TITLE
CDN links for Media Library doesn't work yet after #340

### ISSUE THREAD

**Issue by raphaelquati** [szepeviktor/fix-w3tc#515]
The definition o w3tc_attachment_url (https://github.com/szepeviktor/w3-total-cache-fixed/blob/v0.9.5.x/Cdn_Plugin.php#L776) is wrong.

If idea is to work only in ADMIN, and  cdn.admin.media_library=true, the if statement is wrong.

**Comment by nigrosimone** [comment]
merged https://github.com/szepeviktor/w3-total-cache-fixed/issues/516
