### ISSUE TITLE
Cache-control: expires is missing for media files

### ISSUE THREAD

**Issue by nicooprat** [szepeviktor/fix-w3tc#517]
Hi, using latest Wordpress and W3 Total Cache fixed, here are my settings (same for all file types, css, js, ...):

![capture d ecran 2017-07-12 a 12 17 34](https://user-images.githubusercontent.com/645641/28113367-9502542c-66fc-11e7-9984-bbfe5253d1e7.png)

And here are the results in the network panel (1st for media file, 2nd for CSS file):

![capture d ecran 2017-07-12 a 12 16 58](https://user-images.githubusercontent.com/645641/28113398-b121654e-66fc-11e7-869a-48334ec44ce9.png)

![capture d ecran 2017-07-12 a 12 19 59](https://user-images.githubusercontent.com/645641/28113412-bb55b4fc-66fc-11e7-9c8e-80a918c43a99.png)

The `max-age` is not specified as it should. Did I do something wrong?

Thanks in advance,
Regards.

**Comment by longbigbronzeelephantfish** [comment]
Seems to be working fine on mine.

There should be a generated nginx.conf in your wordpress root.
Check the file and verify that the headers are being added.

Then make sure that you include the generated nginx.conf in your site's nginx configuration:
`include     /some/path/to/wordpress/root/nginx.conf;`

In Apache you have the option of reading and using the .htaccess file in the website's directory. But in nginx, you have to manually include the generated file into your configuration.

**Comment by nicooprat** [comment]
I'm actually using Apache, and here's the [generated .htaccess file](https://gist.github.com/nicooprat/cf0a2a166152b0eb3ba8c341dadb9b66). You can see one of the sites here (it's a multisite): http://valmy-park.residence-etudiant-grenoble.com/.

**Comment by nigrosimone** [comment]
> I'm actually using Apache

@nicooprat, in your response header i see:

    Server: nginx/1.10.3

**Comment by nicooprat** [comment]
Ok good catch, I didn't even see that! I'll get in touch with my hosting provider.

1. W3TC is not generating any `nginx.conf` file, even by visiting `/admin.php?page=w3tc_install`, any way to force it to do so?
1. In the meantime, I tried different configurations, and they're actually working (like entirely disabling browser cache). How would it be possible if only the `.htaccess` changes but the server runs on Nginx?

Thanks for your time.

**Comment by nicooprat** [comment]
Ok my hosting provider resolved it:

* Nginx was only the frontal solution, Apache was actually serving the website
* `mod_expire` was missing and has been re-enabled

Would be great to display an error message if this Apache module is disabled? If possible.

**Comment by nigrosimone** [comment]
there is the test page https://github.com/szepeviktor/w3-total-cache-fixed/pull/478
