### ISSUE TITLE
Authorization mechanism not supported (please use AWS4-HMAC-SHA256)

### ISSUE THREAD

**Issue by matvez93** [szepeviktor/fix-w3tc#518]
Hello,

Thanks for the great effort of mantaining this fork.

I have an AWS S3 bucket hosted on **Canada (Center)** and I experienced a problem using the plugin with that bucket. When I test the upload I get the following error:

Error: Unable to put object (S3::putObject(): [InvalidRequest] The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.).

I have no problem uploading to the same S3 bucket via the AWS cli using the same IAM user.

I think it's the same bug that this issue : 
https://github.com/szepeviktor/w3-total-cache-fixed/issues/192

Thanks!

**Comment by szepeviktor** [comment]
This comment: https://github.com/szepeviktor/w3-total-cache-fixed/issues/192#issuecomment-267693331

**Comment by szepeviktor** [comment]
It seems it is already done https://github.com/szepeviktor/w3-total-cache-fixed/pull/332 and https://github.com/szepeviktor/w3-total-cache-fixed/commit/c7f802a868fa775a72e77e89ec7e34280b2b2a89

**Comment by matvez93** [comment]
Ok now it's working, I had made a mistake when a install the plugin!
