### ISSUE TITLE
mfunc removed from ConfigKeys.php?

### ISSUE THREAD

**Issue by amiga-500** [szepeviktor/fix-w3tc#52]
Hi guys!  Just a quesiton...

I was roaming master's _ConfigKeys.php_ and noticed that `mfunc` is [no longer listed](https://github.com/szepeviktor/fix-w3tc/blob/master/lib/W3/ConfigKeys.php#L597).  In _0.9.4.4-ConfigKeys.php_ `mfunc` was listed under the [_minify.html.comments.ignore_](https://github.com/szepeviktor/fix-w3tc/commit/8462d86df256b68bd25745031cff03764a11bbf6#diff-558365adbb4d18f603cb10c2f3cf4896R534) array.  There doesn't seem to be an explanation for its removal.  Just wondering if that is a mistake or if it was done intentionally.

Thanks for the info
Kimberly

**Comment by nigrosimone** [comment]
In the list of w3tc-fix commits never appears mfunc removal. For me it's a mistake.

**Comment by amiga-500** [comment]
ok thanks for letting me know.  i will add it back in.
