### ISSUE TITLE
Redis Server Parameter Config

### ISSUE THREAD

**Issue by todiadiyatmo** [szepeviktor/fix-w3tc#53]
Hi !
Is there any guide to set the redis config parameter ? for example server ip, port, auth, etc ?

**Comment by charlesLF** [comment]
Hey @todiadiyatmo,

You should set the Redis ip:port from the cache's settings page.

For example, let's say you want to cache objects using redis.

1. In Performance => General Settings, set "Object Cache Method" to Redis
2. In Performance => Object Cache, set the Redis hostname:port (if no port is set, the default port 6379)
3. On the same page, set the Redis DB index. The default is 6, but you can safely change that to any other index.

The Redis module does not currently support authentication, but that's something that we can easily add if it's a necessity. However, as per Redis's website : 
> Redis is designed to be accessed by trusted clients inside trusted environments
(http://redis.io/topics/security).  This means that usually it is not a good idea to expose the Redis instance directly to the internet or, in general, to an environment where untrusted clients can directly access the Redis TCP port or UNIX socket.

Note: There's a typo in the settings page where it says "Memcached hostname:port / IP:port:" when it should have been "Redis hostname:port / IP:port". I have created a pull request to fix this typo. https://github.com/szepeviktor/fix-w3tc/pull/55
