### ISSUE TITLE
Cannot activate plugin 0.9.5.4.3 - WordPress database error: max key length is 767 bytes

### ISSUE THREAD

**Issue by eugenepik** [szepeviktor/fix-w3tc#530]
When clicking on the 'activate' on the plugins page (and when the error reporting is switched on), I receive an error message :  
```
"Plugin could not be activated because it triggered a fatal error.
WordPress database error: [Specified key was too long; max key length is 767 bytes]
CREATE TABLE IF NOT EXISTS `wp_w3tc_cdn_google_drive` ( `remote_path` varchar(500) NOT NULL, `id` varchar(64), PRIMARY KEY (`remote_path`) ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
```
**The problem: key was too long. Table: wp_w3tc_cdn_google_drive**

I had a standard W3 Total Cache plugin installed before I tried to install W3 Total Cache Fixed. 
The W3 Total Cache Fixed is installed in the correct directory with correct rights.

**Wordpress** 4.8.2
**OS**: Debian 4.9.30-2+deb9u3 (2017-08-06) x86_64 GNU/Linux
**PHP**: PHP 7.0.19-1 (cli) (built: May 11 2017 14:04:47) ( NTS )
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.19-1, Copyright (c) 1999-2017, by Zend Technologies
**DB**: mysql  Ver 15.1 Distrib 10.1.26-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
**Webserver**: Server version: Apache/2.4.25 (Debian)
Server built:   2017-09-19T18:58:57
**W3 Total Cache plugin version** 0.9.5.4.3

Data from the error log in `/wp-content/debug.log`

```
[22-Sep-2017 12:52:48 UTC] WordPress database error Specified key was too long; max key length is 767 bytes for query CREATE TABLE IF NOT EXISTS `wp_w3tc_cdn_google_drive` (                              
                                `remote_path` varchar(500) NOT NULL,                                                                                                                                       
                                `id` varchar(64),                                                                                                                                                          
                                PRIMARY KEY (`remote_path`)                                                                                                                                                
                ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci; made by activate_plugin, do_action('activate_w3-total-cache/w3-total-cache.php'), WP_Hook->do_action, WP_Hook->apply_filters, W
3TC\Root_Loader->activate, W3TC\Root_AdminActivation::activate, W3TC\Root_Environment->fix_on_event, W3TC\Cdn_Environment->fix_on_event, W3TC\Cdn_Environment->table_create                                
[22-Sep-2017 12:52:49 UTC] WordPress database error Specified key was too long; max key length is 767 bytes for query CREATE TABLE IF NOT EXISTS `wp_w3tc_cdn_google_drive` (                              
                                `remote_path` varchar(500) NOT NULL,                                                                                                                                       
                                `id` varchar(64),                                                                                                                                                          
                                PRIMARY KEY (`remote_path`)                                                                                                                                                
                ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci; made by do_action('activate_w3-total-cache/w3-total-cache.php'), WP_Hook->do_action, WP_Hook->apply_filters, W3TC\Root_Loader->
activate, W3TC\Root_AdminActivation::activate, W3TC\Root_Environment->fix_on_event, W3TC\Cdn_Environment->fix_on_event, W3TC\Cdn_Environment->table_create                                                 
[22-Sep-2017 12:52:49 UTC] WordPress database error Specified key was too long; max key length is 767 bytes for query CREATE TABLE IF NOT EXISTS `wp_w3tc_cdn_google_drive` (                              
                                `remote_path` varchar(500) NOT NULL,                                                                                                                                       
                                `id` varchar(64),                                                                                                                                                          
                                PRIMARY KEY (`remote_path`)                                                                                                                                                
                ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci; made by do_action('activate_w3-total-cache/w3-total-cache.php'), WP_Hook->do_action, WP_Hook->apply_filters, W3TC\Root_Loader->
activate, W3TC\Root_AdminActivation::activate, W3TC\Root_Environment->fix_on_event, W3TC\Cdn_Environment->fix_on_event, W3TC\Cdn_Environment->table_create
```

Google search is pointing that the problem is utf8mb4 in the database, though the server and the DB were recently installed using default proposed configuration. I probably could change the DB to use UTF8, though all new installs will have this issue. Can the length be fixed to pass the limitations of the DB for the default DB configuration with UTF8MB4 ?

**Comment by nigrosimone** [comment]
The number of allowed characters just depends on your character set. UTF8 may use up to 3 bytes per character, utf8mb4 up to 4 bytes, and latin1 only 1 byte. 

PRIMARY KEY remote_path is 500 characters, since 4*500 = 2000 but the limit is 767 bytes. 

Unfortunately there is no real solution to this. Your only options are to either reduce the size of the column, use a different character set (like UTF-8), or use a different engine (like MYISAM).

**Comment by eugenepik** [comment]
Do we really need 500 characters here? How do they do it in the original W3 Total Cache plugin, so it does work with the limits of 767 bytes and utf8mb4? Can the SQL ask to use UTF8 for the table wp_w3tc_cdn_google_drive instead of the default utf8mb4?

I just tried, this worked for me. Do we need more than 255 chars there?

```CREATE TABLE IF NOT EXISTS `wp_w3tc_cdn_google_drive` ( `remote_path` varchar(255) NOT NULL, `id` varchar(64), PRIMARY KEY (`remote_path`) ) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci```

**Comment by nigrosimone** [comment]
> Do we need more than 255 chars there?

yes, because remote path can be very long, but 255 can works. Remote path is the remote url of the file on google drive.

> How do they do it in the original W3 Total Cache plugin, so it does work with the limits of 767 bytes and utf8mb4?

nope, has the same issue. this part isn't a costumization of this community version.

> Can the SQL ask to use UTF8 for the table wp_w3tc_cdn_google_drive instead of the default utf8mb4?

yes, do you need to change the default db collection.

**Comment by eugenepik** [comment]
I see very different table structure in the original W3 plugin and in the W3-fixed.

Original:
```
describe `wp_w3tc_cdn_queue`;
+-------------+---------------------+------+-----+---------------------+----------------+
| Field       | Type                | Null | Key | Default             | Extra          |
+-------------+---------------------+------+-----+---------------------+----------------+
| id          | int(11) unsigned    | NO   | PRI | NULL                | auto_increment |
| local_path  | varchar(500)        | NO   |     |                     |                |
| remote_path | varchar(500)        | NO   |     |                     |                |
| command     | tinyint(1) unsigned | NO   |     | 0                   |                |
| last_error  | varchar(150)        | NO   |     |                     |                |
| date        | datetime            | NO   | MUL | 0000-00-00 00:00:00 |                |
+-------------+---------------------+------+-----+---------------------+----------------+
```

W3-fixed - there is a new table wp_w3tc_cdn_google_drive. The original W3 table wp_w3tc_cdn_queue is not in the DB
```
describe wp_w3tc_cdn_google_drive;
+-------------+--------------+------+-----+---------+-------+
| Field       | Type         | Null | Key | Default | Extra |
+-------------+--------------+------+-----+---------+-------+
| remote_path | varchar(150) | NO   | PRI | NULL    |       |
| id          | varchar(64)  | YES  |     | NULL    |       |
+-------------+--------------+------+-----+---------+-------+
```
(I reduced remote_path length to 150 to avoid the SQL error)

In other words, the original W3 indexes "id" field which is int(11) unsigned. The W3-fixed indexes the "remote_path" field which supposed to be varchar(500). This is the problem.

**Comment by nigrosimone** [comment]
you are right! this issue was introduced by pr https://github.com/szepeviktor/w3-total-cache-fixed/pull/523, see https://github.com/szepeviktor/w3-total-cache-fixed/pull/523/files

**Comment by jikamens** [comment]
The most obvious fix is to specify latin1 as the character set explicitly for the remote_path column when creating the table. I'm pretty certain the Google Drive URLs are guaranteed to be all ASCII, so latin1 should be fine. @szepeviktor @nigrosimone what do you think?

**Comment by nigrosimone** [comment]
i think it's fine. Maybe, also reduce the lenght of the column, 500 seems to long for a remote path... for example, this 500:

    01234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789

**Comment by szepeviktor** [comment]
I vote for two-byte UTF-8.

**Comment by jikamens** [comment]
>I vote for two-byte UTF-8.

Why waste space on UTF-8 for this column when the Google Drive URLs are guaranteed to be ASCII? I don't see the point. What's your logic here?

**Comment by szepeviktor** [comment]
Actually it is up to @nigrosimone 

> Why waste space on UTF-8 for this column

Maybe we will get a two-byte character somehow.

**Comment by jikamens** [comment]
Looking more carefully, you are correct. It should be utf8. I will submit a PR.

**Comment by nigrosimone** [comment]
> It should be utf8

but 2*500=1000 (>767)

**Comment by jikamens** [comment]
Yeah, I'm going to have to reduce the length to 255.

**Comment by szepeviktor** [comment]
Maybe 767/2?


-- 
+36204242498
Ezen a készüléken sok az elütés. 
Elnézést!

**Comment by jikamens** [comment]
With the utf8 character set, mariadb won't let me go above 255 characters. Is there another character set you would recommend instead?

**Comment by jikamens** [comment]
Should I use ucs2 instead of utf8?

**Comment by nigrosimone** [comment]
> Should I use ucs2 instead of utf8?

[RFC 1738](http://www.ietf.org/rfc/rfc1738.txt) specifies the syntax for URL:

> URLs are written only with the graphic printable characters of the
> US-ASCII coded character set. The octets 80-FF hexadecimal are not
> used in US-ASCII, and the octets 00-1F and 7F hexadecimal represent
> control characters; these must be encoded.

URLs are ASCII. that's all.

**Comment by jikamens** [comment]
Ah, but I was confused before when I said this column stored URLs. This column isn't the URL, it's the path within Google Drive. And that could indeed have unicode characters.

(Insert irony here about how I was wrong about the code that I wrote myself just a few weeks ago.)

**Comment by nigrosimone** [comment]
> And that could indeed have unicode characters.

ok... the problem is only if the field is a key, right? we can use utf-8 and add another field for the primary key (eg. auto incremental id)

**Comment by eugenepik** [comment]
​That way it is done in the original W3. The key is int (11)​

**Comment by jikamens** [comment]
I mean sure, we could do that, but are we really expecting there to be paths within a WordPress installation (the path within the WordPress installation is what gets inserted into this column, because we mirror the hierarchy of the WordPress installation in Google Drive) that are more than 383 characters long? That seems highly unlikely.

**Comment by jikamens** [comment]
I guess I just don't see the value in having an auto-incrementing key column that we aren't actually going to use for anything, and I think it's highly unlikely that we'll never need to worry about a path in the WordPress installation that's >383 characters. And if we're worried about that, then what's next? I mean, the maximum path length on Linux is 4k, do we need to make this column that wide?

**Comment by jikamens** [comment]
By way of comparison, the longest path in my WordPress installation is currently 199 characters long.

**Comment by nigrosimone** [comment]
61 for me

`\wp-content\themes\Avada\assets\images\patterns\pattern20.png`

**Comment by eugenepik** [comment]
May be a dumb question but why path in Gdrive should be indexed? It wasnt indexed in the original W3

**Comment by jikamens** [comment]
>May be a dumb question but why path in Gdrive should be indexed? It wasnt indexed in the original W3

...and the original W3 implementation of the Google Drive CDN is completely broken and does not work, so I'm not sure we should learn much from it. ;-)

It is indexed because we need to look up Google Drive file IDs in this table to insert Google Drive URLs into pages we are rendering, and that lookup is based on the path of the file whose URL is being replaced, and table columns you search a lot are supposed to be indexed so MySQL doesn't have to do a table scan for every URL we're substituting.

**Comment by eugenepik** [comment]
@jikamens , makes sense. How did they do it in the original W3?

**Comment by jikamens** [comment]
>How did they do it in the original W3?

The original code used a URL format for Google Drive files that no longer works. When that URL format was supported, it was not necessary to map WordPress file paths to Google Drive file IDs, because the URL format allowed for the path of the file within Google Drive to be specified directly in the URL.

**Comment by eugenepik** [comment]
@jikamens , thanks for the info. 
Then instead of indexing the Gdrive path or introduce an autoincrement you could create an unique identifier for the Gdrive path, for example based on MD5 (Gdrive path). 

That identifier would always be 128 bit long and could be indexed easily. When searching for a Gdrive path, you could search for its indexed MD5 and get the path value from that record.

**Comment by jikamens** [comment]
(FYI, ref https://gsuiteupdates.googleblog.com/2015/08/deprecating-web-hosting-support-in.html for why the URL format in the original code stopped working.)

>Then instead of indexing the Gdrive path or introduce an autoincrement you could create an unique identifier for the Gdrive path, for example based on MD5 (Gdrive path).

Sure, we could do that, but... why?

I'm trying to be agile here. If there is a _bona fide_ need to support local paths longer than 383 characters, then we can write the code to support that, but it seems highly unlikely, and I personally don't feel particularly motivated to spend my time making the code more complex for the sake of a remotely possible eventuality which may never materialize.

**Comment by nigrosimone** [comment]
**support local paths longer than 383 characters**

**Comment by jikamens** [comment]
Fine, but can we please make that a separate issue? I.e., for now I'd like to reduce the length of the field to 383 and set its charset explicitly to ucs2 so that we can fix the fact that the plugin can't be activated. That will be faster than coding and testing changes to the code and data model.

**Comment by jikamens** [comment]
OK, fine, nvm, I went ahead and implemented it.

I've tested this to the best of my ability and read through all of the changes several times in an effort to confirm its correctness, but another set of eyes would be appreciated before merging the PR.

**Comment by eugenepik** [comment]
Thanks!
Do I need to uninstall the original W3 before installation of W3-fixed?

If I read the code correctly, the W3-fixed updates the DB table created by the original W3. If I uninstall the original W3, that table will be deleted

**Comment by eugenepik** [comment]
Uninstalled W3, then properly installed W3-fixed, uploaded files to Gdrive.
The home page works fine, all images come from Gdrive.

For some reason the post pages have broken links to Gdrive, they are missing the file ID...

Example: http://pikva.com/index.php/2013/02/01/dragon-theme-back-quiver-received-best-colour-award-at-cscl-2013-annual-event/

Edit: nevermind, I had checkmarked "Remove query strings from static resources" in the 'browser cache' - it deleted file ID from the Gdrive images. Maybe a good idea to **disable that option when Gdrive is enabled**...

Edit 2: My longest path is 121 character and it is even not my own file: wp-content/plugins/contact-form-7/includes/js/jquery-ui/themes/smoothness/images/ui-bg_highlight-soft_75_cccccc_1x100.png

**The plugin works fine, you guys awesome!**
