### ISSUE TITLE
Does not Combine JS files 

### ISSUE THREAD

**Issue by IkeTen** [szepeviktor/fix-w3tc#538]
Am using the "auto" minify option with minify enabled for CSS and JS. The plugin does a great job combining CSS files into one file. JS on the other hand is still left as individual files like this:

```
http://site.com/wp-content/cache/minify/157cb.js
http://site.com/wp-content/cache/minify/1d743.js
http://site.com/wp-content/cache/minify/73cbe.js
http://site.com/wp-content/cache/minify/7e7b8.js
http://site.com/wp-content/cache/minify/9f110.js
http://site.com/wp-content/cache/minify/df983.js
```

This reduces page speed score drastically (Combine external CSS). Is this how it is designed to work or there is a solution to combine all JS into one (or a few) file(s)? Thanks

**Comment by nigrosimone** [comment]
this happen because something break the flow betwen the scripts, eg. inline script:

```html
<script src="script1.js"></script>
<script src="script2.js"></script>
<script>document.write('Hello');</script> <!-- this break combine flow -->
<script src="script3.js"></script>
```

this produce

```
http://site.com/wp-content/cache/minify/157cb.js (script1.js + script2.js)
http://site.com/wp-content/cache/minify/df983.js (script3.js)
```

**Comment by IkeTen** [comment]
I was surprised why some caching plugins did this by default and W3TC could not. 
Seems it's a known issue. 
Thanks for the explanation.
