### ISSUE TITLE
HTTP/2 PUSH on nginx only works on first load

### ISSUE THREAD

**Issue by edusperoni** [szepeviktor/fix-w3tc#543]
Hello

I'm using nginx+php7.0-fpm;
Similar to #464, my preloading isn't working after the first page load. I've digged a bit and it seems the plugin does not add the headers to the nginx.conf files, just to the .htaccess file (if you're using apache).

Is there a way to enable this functionality for nginx?

**Comment by nigrosimone** [comment]
By design, HTTP/2 PUSH on nginx works only on first load.

Only on Apache HTTP/2 PUSH works for the cached page.
