### ISSUE TITLE
Demo Import

### ISSUE THREAD

**Issue by Sungsah** [szepeviktor/fix-w3tc#547]
https://shweooyin.com/
samjustun@outlook.com
Password: XXXXXXXXXXXXXXXX

I can't import demo. Please hlep  I want to import main demo. Thank you

**Comment by vysegonzo** [comment]
You shouldn't post credential on your website here.

**Comment by nigrosimone** [comment]
this is a public page, now internet has your admin password. Please, change your password.

**Comment by Sungsah** [comment]
All social icons not appear with buttons, what should I do?
