### ISSUE TITLE
Access to global variable $wp_filter

### ISSUE THREAD

**Issue by charlesLF** [szepeviktor/fix-w3tc#56]
As per this article: https://make.wordpress.org/core/2016/09/08/wp_hook-next-generation-actions-and-filters/ , the next WP version (4.7) will introduce changes to the `$wp_filter` global variable.

W3TC accesses this variable in 2 places in `inc/functions/plugin.php`:
```php
$wp_filter[$hook] = array();
```
These seem to be (by default) only used in `Genesis.php`, but could be used by other developers.

I have never made use of this feature in W3TC, so I am not quite familiar with it, but we could either replace the above line with something like:
```php
if(is_object( $wp_filter[$hook])) 
 $wp_filter[$hook]->callbacks = array();
else 
$wp_filter[$hook] = array();
```
or stick to WP standard functions and use [remove_all_filters](https://codex.wordpress.org/Function_Reference/remove_all_filters)

I would prefer sticking to standard WP functions, even if there's a small execution overhead in doing so, but at least there's less chance of breaking things.

**Comment by nigrosimone** [comment]
i vote for standard `remove_all_filters`

**Comment by amiga-500** [comment]
Bonus points for using `remove_all_filters()`.  Fix looks correct.
