### ISSUE TITLE
Opendir(wp-content/cache/db/options_comments/): failed to open dir: No such file or directory in wp-content/plugins/w3-total-cache/Util_File.php:124

### ISSUE THREAD

**Issue by mahakala** [szepeviktor/fix-w3tc#561]
Opendir(wp-content/cache/db/options_comments/): failed to open dir: No such file or directory in wp-content/plugins/w3-total-cache/Util_File.php:124

**Comment by szepeviktor** [comment]
Hello @mahakala !
Could you please open an issue with a bit more details on your problem?
