### ISSUE TITLE
flush pagecache action?

### ISSUE THREAD

**Issue by futtta** [szepeviktor/fix-w3tc#565]
Just a question really; is there an action that fires when the pagecache gets flushed entirely which 3rd parties can hook into? I seem to have found do_actions for db-, object- & fragment-cache but have not found anything for the page cache?

**Comment by szepeviktor** [comment]
Maybe here? https://github.com/szepeviktor/w3-total-cache-fixed/blob/313db334fc8dd7b885cd26bcba4897f9c6403590/CacheFlush_Locally.php#L165-L173

**Comment by futtta** [comment]
that might indeed be it @szepeviktor, I'll give it a try. thanks! :-)

**Comment by szepeviktor** [comment]
OK.

Don't tell anyone I could point that out!

**Comment by futtta** [comment]
Don't tell anyone I could not ;-)
