### ISSUE TITLE
Any reason Dashboard's Buy Now Widget and General Setting's Licensing Widget are still visible?

### ISSUE THREAD

**Issue by amiga-500** [szepeviktor/fix-w3tc#60]
Just curious...

I noticed the Dashboard's Buy Now Premium Service Widget (see 1st attached image) and the General Setting's Licensing widget (see 2nd attached image) are still showing.

Is there any reason for that?

Is it ok for me to remove them?  

For reference, there respective code locations are [here](https://github.com/szepeviktor/fix-w3tc/blob/master/lib/W3/Widget/Services.php#L89-L94) and [here](https://github.com/szepeviktor/fix-w3tc/blob/master/inc/options/general.php#L576-L591).

Because w3tc seems to have abandoned this plugin i fear if someone were using our fork that these two visible widgets would make user's mistakenly think a paid premium service is still offered by them only to find out in a very ugly way (after paying) that no such service exists and the protracted hassle of getting a credit card transaction reversal would have to begin.

_Note:_ **Their removals are part of PR** #61 

### Dashboard: Premium Services Buy Now
![dashboard_premium](https://cloud.githubusercontent.com/assets/5191497/18572092/0383be08-7b86-11e6-86f7-b67ec1546449.jpg)
### General Settings: Licensing
![general_settings_licensing](https://cloud.githubusercontent.com/assets/5191497/18572095/0a6394f0-7b86-11e6-9344-c5bf3392f4f0.jpg)

**Comment by charlesLF** [comment]
I agree with removing the widgets.
I guess we'll also have to remove any other code that goes with it (I saw there's some js code and php logic in a bunch of other files)?

**Comment by nigrosimone** [comment]
Mhhh but is it legal/correct remove the premium widget?

**Comment by nigrosimone** [comment]
I think, we can remove in the admin dashboard all premium parts and add some info on this community version.

**Comment by szepeviktor** [comment]
Licensing should not be visible, but I let the authors earn some money by leaving the support metabox visible.

https://github.com/szepeviktor/fix-w3tc/commit/b60f6ad5ac0eced73c40b61446369bda9b9b2b19#diff-b57a0557c566c854326d83bf04c0700cL60
