### ISSUE TITLE
Halfdone CloudFlare support in trunk?

### ISSUE THREAD

**Issue by nigrosimone** [szepeviktor/fix-w3tc#68]
from `README.md`:

### Fix

- [ ] Halfdone CloudFlare support in trunk

@szepeviktor, it's a last issue to fix, but what does mean?

**Comment by szepeviktor** [comment]
In WP.org SVN's trunk there is a halfdone CloudFlare support (as I remember cache purging some other features)

**Comment by Volnus** [comment]
There are also some bugs in this integration such as it not purging properly or the email not working or it displaying notices improperly. 

Also, the disable minify if CloudFlare minify is on needs to be removed as its a waste.

**Comment by nigrosimone** [comment]
Someone with CloudFlare can write a PR?

**Comment by szepeviktor** [comment]
Ask @thellimist

**Comment by szepeviktor** [comment]
@thellimist Are you willing to contribute?

**Comment by thellimist** [comment]
I thought this was closed. WIll look into it

**Comment by szepeviktor** [comment]
Thank you.

I've found the code in https://plugins.svn.wordpress.org/w3-total-cache/trunk/

**Comment by szepeviktor** [comment]
Could it be that the code was completed? https://github.com/szepeviktor/w3-total-cache-fixed/blob/w3tc-0-9-5/Extension_CloudFlare_Api.php

Thank you.

**Comment by thellimist** [comment]
@szepeviktor looks like it is complete. Can someone confirm?

**Comment by szepeviktor** [comment]
@nigrosimone @amiga-500 Could you confirm?

**Comment by amiga-500** [comment]
Although it's been a while, so my memory is quite hazy, it seems the exposed CloudFlare features made available are quite extensive (see attached image).

![Cloudflare in w3tc](https://cloud.githubusercontent.com/assets/5191497/21318562/b9dde688-c5d7-11e6-8f24-49112f431d10.png)

**Comment by szepeviktor** [comment]
Thank you.
https://github.com/szepeviktor/w3-total-cache-fixed/commit/938cb7ae58a589437dcb0c57dad175f209f231b6
