### ISSUE TITLE
Undefined function apply_filters()

### ISSUE THREAD

**Issue by dmarkowicz** [szepeviktor/fix-w3tc#70]
Hello, I have a problem with #50.
```
( ! ) Fatal error: Uncaught Error: Call to undefined function apply_filters() in C:\myproject\wp-content\plugins\w3-total-cache\lib\W3\PgCache.php on line 152
( ! ) Error: Call to undefined function apply_filters() in C:\myproject\wp-content\plugins\w3-total-cache\lib\W3\PgCache.php on line 152
Call Stack
#	Time	Memory	Function	Location
1	0.2007	386864	{main}( )	...\index.php:0
2	0.2017	434288	require_once( 'C:\myproject\wp-admin\admin.php' )	...\index.php:10
3	0.2025	448320	require_once( 'C:\myproject\wp-load.php' )	...\admin.php:31
4	0.2029	477064	require_once( 'C:\myproject\wp-config.php' )	...\wp-load.php:37
5	0.2036	551784	require_once( 'C:\myproject\wp-settings.php' )	...\wp-config.php:176
6	0.2080	719672	include( 'C:\myproject\wp-content\advanced-cache.php' )	...\wp-settings.php:74
7	0.2270	1542184	w3_instance( )	...\advanced-cache.php:33
8	0.2287	1805152	W3_PgCache->__construct( )	...\define.php:1471
```
`apply_filters` is defined in plugin.php, but no plugin.php in this context.

**Comment by charlesLF** [comment]
Are you using a version of WP < 4.6 ?

**Comment by dmarkowicz** [comment]
Yes, I am using 4.5.3. I can not use 4.6.1 because some bugs: https://core.trac.wordpress.org/query?milestone=4.6.2&order=priority

**Comment by amiga-500** [comment]
Hmm...I suspect this call is being made too early in the stack that wp;s functions may not be included yet.   Recall the access point is  via wp-content/advanced cache.php which is intentionally made early to process caches aasap if my memory serves me.  If true the fix won't be be that bad. Not home so I can't commit a fix yet

**Comment by charlesLF** [comment]
As per this link : https://make.wordpress.org/core/2016/08/13/global-overloading-in-advanced-cache-php/ and this link: https://make.wordpress.org/core/2016/08/13/global-overloading-in-advanced-cache-php/

> If you need to interact with the Plugins API in advanced-cache.php, as of 4.6, you can use the Plugins API (add_action(), add_filter(), etc.).

> Load plugin.php earlier in wp-settings.php
>
> plugin.php contains the functions such as add_filter() and add_action() that form the foundation of the WordPress plugin system. The file (and thus those functions) are now being loaded earlier in wp-settings.php. This allows for some hooks to be placed earlier, but also for advance-cache.php drop-ins to use the plugins API rather than directly manipulating global variables. For more information, see #36819.

So `apply_filters` is not defined in WP 4.5 by the time W3TC is executed.

We should add a version check before using apply_filters.

**Comment by nigrosimone** [comment]
function_exists is the way

**Comment by charlesLF** [comment]
I'll prepare a pull request to fix this.

**Comment by charlesLF** [comment]
On second thought ... I don't think the filter that was added in #50 can actually be used at all.
The `apply_filter` in PgCache.php is called before any theme or plugin (even mu-plugin) code, so the filter will never have any functions hooked to it by the time we call it in PgCache.php

Was anyone actually successful in using the hook?

**Comment by nigrosimone** [comment]
mhhh @todiadiyatmo  it works?

**Comment by nigrosimone** [comment]
i confirm... this hook, can't work.

**Comment by nigrosimone** [comment]
revert https://github.com/szepeviktor/fix-w3tc/pull/72

**Comment by amiga-500** [comment]
It seems it still could be possible to have this feature as long as `$this->_lifetime` was assigned just before the generated cache was written out to disk/memory/cdn ...in other words, just before `$cache->set(..) ` function calls because $cache->set() would have already loaded themes and plugins and had collected the output data and ready to store already -- that means apply_filter() and its companion functions would have to be around, even for <4.6.  In PgCache.php the `$cache->set()` is found in the `_can_cache_buffer()` function.  Just did a quick test and yup the apply_filter(..) was triggering my user function inside my theme's functions.php.  I haven't looked deep into this yet but at least that is promising.

**Comment by nigrosimone** [comment]
when advanced-cache is triggered, wordpress loads only a minimal part of core. I think this is a risk for implement a hook in this point, but if someone make a working PR is welcome.

**Comment by charlesLF** [comment]
Good point, @amiga-500 .

I just checked it and you're right. When `$cache->set()` is called in `_can_cache_buffer`, the plugins and themes would have been loaded by that point (unlike in `__construct()`).

Moving the filter to inside `_can_cache_buffer` would be the way to do it.

**Comment by todiadiyatmo** [comment]
Sorry for causing trouble in my PR, 

Just want to confirm the issue , i have also test it extensively and can confirm : 
1. Apply filter is not defined in WP 4.6 <
2. Apply filter function exist but do not effect anything on the previous commit, it is called to early
3. The solution is to move the apply filter to WP Root Init class 

i do some quick fix here : 
https://github.com/szepeviktor/fix-w3tc/pull/73/files

**Comment by charlesLF** [comment]
My attempt : #74

**Comment by todiadiyatmo** [comment]
@charlesLF i will test it today and share the result

**Comment by nigrosimone** [comment]
#74 merged
