### ISSUE TITLE
Installation instructions generate "Plugin file not found" error

### ISSUE THREAD

**Issue by asadowski** [szepeviktor/fix-w3tc#71]
Followed the install instructions several times.

Tried restarting both nginx and php7 as well.

Each time the plug-in fails to register - If I reload the plugins list, it's not listed.  If I just try to reactivate, I get the plugin file not found error.

**Comment by cesco69** [comment]
work for me...

**Comment by charlesLF** [comment]
@asadowski just double-checking, did you rename the folder to `w3-total-cache`?
Do you have all files (listed here: https://github.com/szepeviktor/fix-w3tc) showing up inside that folder?

**Comment by asadowski** [comment]
Looks like a permissions issue on the unzip on my end... Unzipped as 700 for some reason.  Thanks
