### ISSUE TITLE
Ignore Minify On AMP Pages

### ISSUE THREAD

**Issue by Volnus** [szepeviktor/fix-w3tc#8]
If you are using the CSS/JS minification its injected onto AMP pages there is a fix here: 

https://wordpress.org/support/topic/disable-on-amp-pages?replies=23

We can do this or exclude the entire page automatically by default under the 
Never minify the following pages and set the default to /amp/ either or looking at both solutions.

**Comment by nigrosimone** [comment]
Proposed fix via PR https://github.com/szepeviktor/fix-w3tc/pull/11
