### ISSUE TITLE
Page cache priming does not work when 'priority' is missing in sitemap

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [szepeviktor/fix-w3tc#80]
I am seeing an issue with priming cache. But it's both in the original W3TC and fix-w3tc. 

Earlier, with say, the default setting of priming 10 pages every 900 seconds, I used to see two primining jobs in cron. I use the plugin Crontrol to see cron events. One of these had "arguments" like [10], [20], [30] and so on after each interval of 900 seconds.  But now the priming is not happening in both the W3TC and fix-w3tc. 

Anyone has an idea on how to solve this?

**Comment by charlesLF** [comment]
@vijayaraghavanramanan,

Do you have a [compliant](https://www.xml-sitemaps.com/validate-xml-sitemap.html) sitemap under "Sitemap URL"?
Does the sitemap contain a number of links that is greater than the number you have in "Pages per interval"?

**Comment by vijayaraghavanramanan** [comment]
Hi @charlesLF 

Yeah I use Yoast's SEO plugin and it has the correct address. 

Yeah the sitemap has some 400 links and the pages per interval is just 30. 

The thing is all this was working without any trouble whatsoever till recently. I don't know what happened. I mean I have seen some old forum posts about cron issues but at my side I never had an issue. Maybe it's Wordpress's new version or something. I can't figure. 

I also see the sitemap being loaded in "Recent visitors" in my host's cPanel and also the link with the cron. But the pages aren't primed. Earlier I used to see the pages being visited by W3TC in recent visitors.

**Comment by charlesLF** [comment]
@vijayaraghavanramanan,

Could you post here a link to your sitemap, if you don't mind?
I think it would be helpful in trying to debug this.

Thanks

**Comment by vijayaraghavanramanan** [comment]
Yes. [Here](http://www.concertedaction.com/sitemap_index.xml) it is

**Comment by vijayaraghavanramanan** [comment]
Your intuition turned out to be right! I think it has to do with the priority column missing in Yoast's most recent update which is version 3.5. 

https://kb.yoast.com/kb/can-i-change-the-sitemap-priority/

That explains why I saw the change recently. 3.5 was out only recently. 

I did some experiments and used the Google XML sitemaps temporarily. It seems to work then. 

So I conclude that it is entirely due to the removal of the priority column by Yoast.

**Comment by amiga-500** [comment]
Hey that's awesome to know!  Thanks @vijayaraghavanramanan and @charlesLF 

> So I conclude that it is entirely due to the removal of the priority column by Yoast. 

Although sitemap's `priority` attribute is indeed optional i notice w3tc [makes it a requirement](https://github.com/szepeviktor/fix-w3tc/blob/master/lib/W3/Plugin/PgCacheAdmin.php#L188-L189).  It seems w3tc should by default assume the priority is 0.5 (the standard default value for this attribute) instead of 0.  This should solve the problem for sitemap generators like the new version of Yoast who have understandably dropped this attribute.

I'll commit this fix, unless there is an issue i'm unaware of by doing so.

Kimberly

**Comment by vijayaraghavanramanan** [comment]
Thanks.

I don't understand Github much. There are two branches: master and sitemap_patch. Will they be merged into one?

**Comment by amiga-500** [comment]
@vijayaraghavanramanan  yes they will be merged into one some time today.  At present sitemap_patch actually already includes everything in master, so if you don't want to wait you can just download the zip now (after selecting the sitemap_patch branch of course).

**Comment by charlesLF** [comment]
@amiga-500, you beat me to the fix! :smile: 

Thanks for reporting this, @vijayaraghavanramanan ! Nice catch :)

**Comment by vijayaraghavanramanan** [comment]
Great. Done. Priming working now!
