### ISSUE TITLE
AMP Errors Revisited

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [szepeviktor/fix-w3tc#83]
Since I am not sure if the developers get notifications to closed issues, I am reopening https://github.com/szepeviktor/fix-w3tc/pull/11 here. 

I am still getting AMP errors. 

A demo is [here](http://www.concertedaction.com/2016/09/16/target2-balances-and-qe-recycling/amp)

**Comment by charlesLF** [comment]
It seems line 145 in /lib/w3

```php
                if (function_exists('is_feed') && !is_feed()) {
```

should be changed to:

```php
                if (function_exists('is_feed') && !is_feed()  && $add_script_and_style) {
```

@vijayaraghavanramanan, could you try this change on your website then clear the cache and see if this fixes the problem?

If it does, I will push the fix to the master branch.

**Comment by vijayaraghavanramanan** [comment]
Yes, that fixes it!

**Comment by charlesLF** [comment]
Awesome. Fix merged onto master branch.

Thanks for reporting it, @vijayaraghavanramanan :)
