### ISSUE TITLE
Does this fork include auto pilot cache clearing?

### ISSUE THREAD

**Issue by MarceloPedra** [szepeviktor/fix-w3tc#87]
Hello guys. I didn't entirely review your code changes but I'm just wondering if you have integrated useful hooks like the ones by [w3tc-auto-pilot](https://github.com/wp-plugins/w3tc-auto-pilot/blob/master/w3tc-auto-pilot.php), or do I still need that other plugin to help yours to be in autopilot?

Thanks in advance!

**Comment by nigrosimone** [comment]
No, fix-w3tc not integrate w3tc-auto-pilot.
