### ISSUE TITLE
Add mfunc to ignored comment strings automaticallyc

### ISSUE THREAD

**Issue by Volnus** [szepeviktor/fix-w3tc#9]
If you are using the premium version of the plugin users will have the mfunc minified when using the HTML compressor this needs to be added by default in order to prevent user's fragment caching from not working. 

Needs to be added to the Ignored comment stems

Looking for a solution now.

**Comment by Volnus** [comment]
Proposed fix via pull request

**Comment by szepeviktor** [comment]
Closed by #10
